<?php

namespace Wellbeing\Bundle\ErgonomicsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserErgonomicsMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserErgonomicsMessageRepository extends EntityRepository
{
    /**
     * Get all not processed tasks
     * @param $queryBuilder
     * @return mixed
     */
    protected function getExprProcessed($queryBuilder)
    {
        $queryBuilder->setParameter(':processed', true);
        return $queryBuilder->expr()->eq('UserErgonomicsMessage.processed', ':processed');
    }

    /**
     * Get all not processed tasks
     * @param $queryBuilder
     * @return mixed
     */
    protected function  getExprNotProcessed($queryBuilder)
    {
        $queryBuilder->setParameter(':processed', 0);
        return $queryBuilder->expr()->orX(
            $queryBuilder->expr()->eq('UserErgonomicsMessage.processed', ':processed'),
            $queryBuilder->expr()->isNull('UserErgonomicsMessage.processed')
        );
    }


    /**
     * Get expression by user id
     * @param $queryBuilder
     * @param $user
     * @return mixed
     */
    protected function getExprUser($queryBuilder, $user = null)
    {
        if (!empty($user)) {
            $queryBuilder->setParameter('user', $user->getId());
            return $queryBuilder->expr()->eq('UserErgonomicsMessage.user', ':user');
        }
        return $queryBuilder->expr()->eq('0', '1');
    }

    /**
     * @param $queryBuilder
     * @param $datetime
     * @return mixed
     */
    protected function getExprDateTimeGt($queryBuilder, $datetime)
    {
        if (!empty($datetime)) {
            $queryBuilder->setParameter('datetimegt', $datetime);
            return $queryBuilder->expr()->gte('UserErgonomicsMessage.date', ':datetimegt');
        }
        return $queryBuilder->expr()->eq('0', '1');
    }


    /**
     * Find last not processed message
     * @param $user
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findLastNotProcessedByUser($user, $date)
    {
        $queryBuilder = $this->createQueryBuilder("UserErgonomicsMessage");
        $queryBuilder->where($queryBuilder->expr()->andX(
            $this->getExprUser($queryBuilder, $user),
            $this->getExprDateTimeGt($queryBuilder, $date),
            $this->getExprNotProcessed($queryBuilder)
        ));

        $queryBuilder->orderBy('UserErgonomicsMessage.id', 'DESC');
        $queryBuilder->setMaxResults(1);

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }

    /**
     * @param $user
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findLastProcessedByUser($user)
    {
        $queryBuilder = $this->createQueryBuilder("UserErgonomicsMessage");
        $queryBuilder->where($queryBuilder->expr()->andX(
            $this->getExprUser($queryBuilder, $user),
            $this->getExprProcessed($queryBuilder)
        ));

        $queryBuilder->orderBy('UserErgonomicsMessage.id', 'DESC');
        $queryBuilder->setMaxResults(1);

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }

    /**
     * Get last processed elements
     * @param $user
     * @param int $limit
     * @return array
     */
    public function findProcessedByUser($user, $limit = 10)
    {
        $queryBuilder = $this->createQueryBuilder("UserErgonomicsMessage");
        $queryBuilder->where($queryBuilder->expr()->andX(
            $this->getExprUser($queryBuilder, $user),
            $this->getExprProcessed($queryBuilder)
        ));

        $queryBuilder->setMaxResults($limit);
        $queryBuilder->orderBy('UserErgonomicsMessage.id', 'DESC');

        return $queryBuilder->getQuery()->getResult();
    }

}
