<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\MediaBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Sonata\MediaBundle\Entity\BaseGallery as BaseGallery;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Gallery extends BaseGallery
{

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $galleryHasGallery;

    /**
     * Get galleryHasGallery
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getGalleryHasGallery()
    {
        return $this->galleryHasGallery;
    }

    /**
     * Remove children
     *
     * @param \Application\Sonata\MediaBundle\Entity\Gallery $children
     */
    public function removeChild(\Application\Sonata\MediaBundle\Entity\Gallery $children)
    {
        $this->children->removeElement($children);
    }


    /**
     * Add galleryHasGallery
     *
     * @param \Application\Sonata\MediaBundle\Entity\GalleryHasGallery $galleryHasGallery
     * @return Gallery
     */
    public function addGalleryHasGallery(\Application\Sonata\MediaBundle\Entity\GalleryHasGallery $galleryHasGallery)
    {
        $galleryHasGallery->setGallery($this);

        $this->galleryHasGallery[] = $galleryHasGallery;

        return $this;
    }

    /**
     * Remove galleryHasGallery
     *
     * @param \Application\Sonata\MediaBundle\Entity\GalleryHasGallery $galleryHasGallery
     */
    public function removeGalleryHasGallery(\Application\Sonata\MediaBundle\Entity\GalleryHasGallery $galleryHasGallery)
    {
        $this->galleryHasGallery->removeElement($galleryHasGallery);
    }

    /**
     * {@inheritdoc}
     */
    public function setGalleryHasGallery($galleryHasGalleries)
    {
        $this->galleryHasGallery = new ArrayCollection();

        foreach ($galleryHasGalleries as $galleryHasGallery) {
            $this->addGalleryHasGallery($galleryHasGallery);
        }
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        parent::__construct();

        $this->galleryHasGallery = new \Doctrine\Common\Collections\ArrayCollection();
    }
}
