be_simple_soap:
    cache:
        type:     disk
        lifetime: 86400
        limit:    5
    clients:
        user:
          wsdl: http://app.fitbase.de/api/wsdl/user?wsdl
    services:
        user:
            namespace:     http://localhost:8000/api/wsdl/user
            binding:       rpc-literal
            resource:      "@FitbaseUserBundle/Controller/WsdlController.php"
            resource_type: annotation