be_simple_soap:
    wsdl_dumper:
        stylesheet: "/api.xsl"

    cache:
        type:     disk
        lifetime: 86400
        limit:    5
    clients:
        fitbase:
          wsdl: https://www.fitbase.de/api/api.wsdl

    services:
        user:
            namespace: "http://localhost:8000/api/wsdl/user/1.0/"
            binding: "rpc-literal"
            resource: "@FitbaseUserBundle/Controller/WsdlController.php"
            resource_type: "annotation"