be_simple_soap:
    wsdl_dumper:
        stylesheet: "/api.xsl"

    cache:
        type:     disk
        lifetime: 86400
        limit:    5
    clients:
        fitbase:
          wsdl: https://www.fitbase.de/wsdl/api.xml

    services:
        user:
            namespace: "http://app.fitbase.de/api/wsdl/user/1.0/"
            binding: "rpc-literal"
            resource: "@WellbeingApiBundle/Controller/WSDLController.php"
            resource_type: "annotation"