be_simple_soap:
    wsdl_dumper:
        stylesheet: "/api.xsl"

    cache:
        type:     disk
        lifetime: 86400
        limit:    5
    clients:
        fitbase:
          wsdl: "https://coaches.fitbase.de/wsdl/api.wsdl"
        wellbeing:
          wsdl: "https://wellbeing.fitbase.de/api/wsdl/user"

    services:
        user:
            namespace: "https://wellbeing.fitbase.de/api/wsdl/user/1.0/"
            binding: "rpc-literal"
            resource: "@WellbeingApiBundle/Controller/WsdlApiController.php"
            resource_type: "annotation"