<?php

namespace Wellbeing\Bundle\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStateRepository extends EntityRepository
{
    /**
     * Find last user state
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findLast()
    {
        $queryBuilder = $this->createQueryBuilder('UserState');

        $queryBuilder->addOrderBy('UserState.id', 'DESC');
        $queryBuilder->setMaxResults(1);

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }
}
