<?php

namespace Wellbeing\Bundle\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserAuthenticationKeyRepository extends EntityRepository
{

}
