<?php

namespace Wellbeing\Bundle\ApiBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStateRepository extends EntityRepository
{
    /**
     * Get expression by user id
     * @param $queryBuilder
     * @param $user
     * @return mixed
     */
    protected function getExprUser($queryBuilder, $user = null)
    {
        if (!empty($user)) {
            $queryBuilder->setParameter('user', $user->getId());
            return $queryBuilder->expr()->eq('UserState.user', ':user');
        }
        return $queryBuilder->expr()->eq('0', '1');
    }

    /**
     * Find last user state
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findLast()
    {
        $queryBuilder = $this->createQueryBuilder('UserState');

        $queryBuilder->addOrderBy('UserState.id', 'DESC');
        $queryBuilder->setMaxResults(1);

        return $queryBuilder->getQuery()->getOneOrNullResult();
    }


    public function findByUser($user, $limit = 100)
    {
        $queryBuilder = $this->createQueryBuilder('UserState');

        $queryBuilder->where($queryBuilder->expr()->andX(
            $this->getExprUser($queryBuilder, $user)
        ));

        $queryBuilder->addOrderBy('UserState.id', 'DESC');
        $queryBuilder->setMaxResults($limit);

        return $queryBuilder->getQuery()->getResult();
    }
}
