# cross links between kernels
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'

_sonata_admin:
    resource: .
    type:     sonata_admin

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /

fitbase_sonata_user:
    resource: "@FitbaseUserBundle/Resources/config/routing_sonata.xml"
    prefix:   /user

sonata_user_admin:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'

sonata_media_pixlr:
    resource: '@SonataMediaBundle/Resources/config/routing/pixlr.xml'
    prefix:   /media

fitbase_email:
    resource: "@FitbaseEmailBundle/Resources/config/routing_sonata.xml"
    prefix:   /email

fitbase_weeklytask:
    resource: "@FitbaseWeeklytaskBundle/Resources/config/routing_sonata.xml"
    prefix:   /infoeinheit

Wellbeing:
    prefix:       /wellbeing
    resource:     "@WellbeingApiBundle/Resources/config/routing.xml"
