<?php

namespace Fitbase\Bundle\GamificationBundle\DataFixture\ORM;
;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Fitbase\Bundle\GamificationBundle\Entity\GamificationDialogQuestion;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadGamificationDialogQuestionData extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetaData(get_class(new GamificationDialogQuestion()))->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item7 = new GamificationDialogQuestion();
        $item7->setText("Sieh deinen Baum, hat er schon neue Blätter bekommen?");
        $item7->setType("finish");
        $item7->setStart(0);
        $manager->persist($item7);
        $manager->flush();

        $this->addReference('GamificationDialogQuestion7', $item7);

        $item21 = new GamificationDialogQuestion();
        $item21->setQuestionTrue($this->getReference('GamificationDialogQuestion7'));
        $item21->setText("Sehr gut! Dann dir noch einen schönen Tag!");
        $item21->setType("notice");
        $item21->setStart(0);
        $item21->setDescription("Direkt danach wird die neue \"Frage\" angezeigt!");
        $manager->persist($item21);
        $manager->flush();

        $this->addReference('GamificationDialogQuestion21', $item21);

        $item9 = new GamificationDialogQuestion();
        $item9->setId(9);
        $item9->setQuestionTrue($this->getReference('GamificationDialogQuestion21'));
        $item9->setText("Was macht dich heute glücklich?");
        $item9->setType("text");
        $item9->setStart(0);
        $item9->setDescription("Text wird in Datenbank gespeichert!");
        $item9->setPositive(0);
        $manager->persist($item9);
        $manager->flush();

        $this->addReference('GamificationDialogQuestion9', $item9);


        $item10 = new GamificationDialogQuestion();
        $item10->setQuestionTrue($this->getReference('GamificationDialogQuestion9'));
        $item10->setText("Denke nun an eine Situation, die dich bereits glücklich gemacht hat, wie...");
        $item10->setType("feedback");
        $item10->setStart(0);
        $manager->persist($item10);
        $manager->flush();

        $this->addReference('GamificationDialogQuestion10', $item10);

        $item11 = new GamificationDialogQuestion();
        $item11->setQuestionTrue($this->getReference('GamificationDialogQuestion10'));
        $item11->setText("Nun klicke auf den Papierkorb, damit wir deine Belastung ein für alle Mal wegschmeißen.");
        $item11->setType("trash");
        $item11->setStart(0);
        $manager->persist($item11);
        $manager->flush();

        $this->addReference('GamificationDialogQuestion11', $item11);

        $item12 = new GamificationDialogQuestion();
        $item12->setQuestionTrue($this->getReference('GamificationDialogQuestion11'));
        $item12->setText("Klicke auf das Video! Du siehst dort eine Wassersäule. Sie füllt sich langsam und leert sich anschließend wieder. Atme in Ihrem Tempo tief ein und aus. Stelle dir dabei vor, wie bei jedem Ausatmen deine Belastung von dir weicht.");
        $item12->setType("notice");
        $item12->setStart(0);
        $item12->setDescription("So sollte die Wassersäule ausschauen: http://www.praxiskoloczek.de/atem.html");
        $manager->persist($item12);
        $manager->flush();

        $this->addReference('GamificationDialogQuestion12', $item12);

        $item14 = new GamificationDialogQuestion();
        $item14->setQuestionTrue($this->getReference('GamificationDialogQuestion12'));
        $item14->setText("Wie kann man die Situation noch sehen?");
        $item14->setType("text");
        $item14->setStart(0);
        $item14->setDescription("");
        $item14->setPositive(0);
        $manager->persist($item14);
        $manager->flush();

        $this->addReference('GamificationDialogQuestion14', $item14);

        $item17 = new GamificationDialogQuestion();
        $item17->setQuestionTrue($this->getReference('GamificationDialogQuestion7'));
        $item17->setText("Dann setze es jetzt um! Viel Erfolg dabei und noch einen schönenTag!");
        $item17->setType("notice");
        $item17->setStart(0);
        $item17->setDescription("Darauf folgt direkt die neue \"Frage\"!");
        $manager->persist($item17);
        $manager->flush();

        $this->addReference('GamificationDialogQuestion17', $item17);

        $item20 = new GamificationDialogQuestion();
        $item20->setQuestionTrue($this->getReference('GamificationDialogQuestion17'));
        $item20->setText("Was kannst du daran ändern?");
        $item20->setType("text");
        $item20->setStart(0);
        $item20->setPositive(0);
        $manager->persist($item20);
        $manager->flush();

        $this->addReference('GamificationDialogQuestion20', $item20);

        $item15 = new GamificationDialogQuestion();
        $item15->setQuestionTrue($this->getReference('GamificationDialogQuestion20'));
        $item15->setQuestionFalse($this->getReference('GamificationDialogQuestion14'));
        $item15->setText("Kannst du daran etwas ändern?");
        $item15->setType("boolean");
        $item15->setStart(0);
        $manager->persist($item15);
        $manager->flush();

        $this->addReference('GamificationDialogQuestion15', $item15);

        $item18 = new GamificationDialogQuestion();
        $item18->setQuestionTrue($this->getReference('GamificationDialogQuestion15'));
        $item18->setText("Was belastet dich?");
        $item18->setType("text");
        $item18->setStart(0);
        $item18->setPositive(0);
        $manager->persist($item18);
        $manager->flush();

        $this->addReference('GamificationDialogQuestion18', $item18);


        $item8 = new GamificationDialogQuestion();
        $item8->setQuestionTrue($this->getReference('GamificationDialogQuestion18'));
        $item8->setQuestionFalse($this->getReference('GamificationDialogQuestion9'));
        $item8->setText("Belastet dich heute etwas?");
        $item8->setType("boolean");
        $item8->setStart(1);
        $item8->setPositive(0);
        $manager->persist($item8);

        $this->addReference('GamificationDialogQuestion8', $item8);

        $item13 = new GamificationDialogQuestion();
        $item13->setQuestionTrue($this->getReference('GamificationDialogQuestion12'));
        $item13->setText("Was ist an der Situation positiv?");
        $item13->setType("text");
        $item13->setStart(0);
        $item13->setPositive(0);
        $manager->persist($item13);
        $manager->flush();

        $this->addReference('GamificationDialogQuestion13', $item13);
    }

}
