ci_rest_client:
    curl:
      defaults:
        CURLOPT_HTTPHEADER:     [ 'Content-Type: application/json', 'Authorization: Basic QWxhZGRpbjpvcGVuIHNlc2FtZQ==' ]
        CURLOPT_FOLLOWLOCATION: true