<?php

namespace Fitbase\Bundle\QuestionnaireBundle\DataFixture\ORM;
;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Fitbase\Bundle\QuestionnaireBundle\Entity\QuestionnaireQuestion;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadQuestionnaireQuestionData extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 2;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetaData(get_class(new QuestionnaireQuestion()))->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new QuestionnaireQuestion();
        $item1->setName("Wie würden Sie Ihren Gesundheitszustand im Allgemeinen beschreiben?");
        $item1->setType("radiobutton");
        $item1->setDescription("");
        $item1->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item1);
        $manager->flush();

        $this->addReference('questionnaire_question_1', $item1);

        $item2 = new QuestionnaireQuestion();
        $item2->setName("Haben sie eine akute oder eine chronische Erkrankung?");
        $item2->setType("checkbox");
        $item2->setDescription("");
        $item2->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item2);
        $manager->flush();

        $this->addReference('questionnaire_question_2', $item2);


        $item3 = new QuestionnaireQuestion();
        $item3->setName("Wurden Sie in den letzten 6 Monaten an der Wirbelsäule operiert?");
        $item3->setType("radiobutton");
        $item3->setDescription("");
        $item3->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item3);
        $manager->flush();

        $this->addReference('questionnaire_question_3', $item3);

        $item4 = new QuestionnaireQuestion();
        $item4->setName("Haben Sie aktuell Rückenschmerzen und/oder Verspannungen?");
        $item4->setType("radiobutton");
        $item4->setDescription("");
        $item4->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item4);
        $manager->flush();

        $this->addReference('questionnaire_question_4', $item4);

        $item5 = new QuestionnaireQuestion();
        $item5->setName("Wie stark schätzen Sie ihre momentanen Rückenschmerzen und/oder Verspannungen ein.");
        $item5->setType("slider");
        $item5->setDescription("Auf einer Skala von 0 (kein Schmerz) bis 10 (stärkster vorstellbarer Schmerz)");
        $item5->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item5);
        $manager->flush();

        $this->addReference('questionnaire_question_5', $item5);

        $item6 = new QuestionnaireQuestion();
        $item6->setName("An wie vielen Tagen hatten Sie innerhalb der letzten 4 Wochen Rückenschmerzen und/oder Verspannungen?");
        $item6->setType("selectbox");
        $item6->setDescription("");
        $item6->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item6);
        $manager->flush();

        $this->addReference('questionnaire_question_6', $item6);

        $item7 = new QuestionnaireQuestion();
        $item7->setName("Wie groß sind Sie (Meters)?");
        $item7->setType("text");
        $item7->setDescription("");
        $item7->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item7);
        $manager->flush();

        $this->addReference('questionnaire_question_7', $item7);

        $item8 = new QuestionnaireQuestion();
        $item8->setName("Wie schwer sind Sie (Kg)?");
        $item8->setType("text");
        $item8->setDescription("");
        $item8->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item8);
        $manager->flush();

        $this->addReference('questionnaire_question_8', $item8);

        $item9 = new QuestionnaireQuestion();
        $item9->setName("Wie stark empfinden Sie die Stressbelastung an ihrem Arbeitsplatz?");
        $item9->setType("slider");
        $item9->setDescription("Auf einer Skala von 0 (sehr gering) bis 5 (sehr stark)");
        $item9->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item9);
        $manager->flush();

        $this->addReference('questionnaire_question_9', $item9);

        $item10 = new QuestionnaireQuestion();
        $item10->setName("Ich bin in der Lage, mit den Stressbelastungen am Arbeitsplatz umzugehen.");
        $item10->setType("slider");
        $item10->setDescription("Auf einer Skala von 0 (stimmt vollkommen) bis 5 (stimmt überhaupt nicht)");
        $item10->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item10);
        $manager->flush();

        $this->addReference('questionnaire_question_10', $item10);

        $item11 = new QuestionnaireQuestion();
        $item11->setName("Wie stark empfinden Sie die Belastung durch körperliche einseitige Arbeitsabläufe an Ihrem Arbeitsplatz?");
        $item11->setType("slider");
        $item11->setDescription("Auf einer Skala von 0 (sehr gering) bis 5 (sehr stark)");
        $item11->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item11);
        $manager->flush();

        $this->addReference('questionnaire_question_11', $item11);

        $item12 = new QuestionnaireQuestion();
        $item12->setName("Ich bin in der Lage, mit den Belastungen durch körperliche einseitige Arbeitsabläufe am Arbeitsplatz umzugehen.");
        $item12->setType("slider");
        $item12->setDescription("Auf einer Skala von 0 (stimmt vollkommen) bis 5 (stimmt überhaupt nicht)");
        $item12->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item12);
        $manager->flush();

        $this->addReference('questionnaire_question_12', $item12);

        $item13 = new QuestionnaireQuestion();
        $item13->setName("Wie viel Stunden Ihrer Arbeitszeit verbringen Sie im Stehen?");
        $item13->setType("selectbox");
        $item13->setDescription("");
        $item13->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item13);
        $manager->flush();

        $this->addReference('questionnaire_question_13', $item13);

        $item14 = new QuestionnaireQuestion();
        $item14->setName("Wie viele Stunden verbringen Sie an einem normalen Werktag im Sitzen?");
        $item14->setType("selectbox");
        $item14->setDescription("Dazu zählen Zeiten beim Essen, Wegezeiten, Arbeitszeit im Sitzen, Freizeit im Sitzen (TV, PC)");
        $item14->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item14);
        $manager->flush();

        $this->addReference('questionnaire_question_14', $item14);

        $item15 = new QuestionnaireQuestion();
        $item15->setName("Wie viele  Punkte würden Sie dann für ihre derzeitige Arbeitsfähigkeit geben?");
        $item15->setType("selectbox");
        $item15->setDescription("Auf einer Skala von 0 (voll arbeitsunfähig) bis 5 (derzeit die beste)");
        $item15->setQuestionnaire($this->getReference('questionnaire_1'));
        $manager->persist($item15);
        $manager->flush();

        $this->addReference('questionnaire_question_15', $item15);
    }
}
