<?php

namespace Fitbase\Bundle\QuestionnaireBundle\DataFixture\ORM;
;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Fitbase\Bundle\QuestionnaireBundle\Entity\QuestionnaireAnswer;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadQuestionnaireAnswerData extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 3;
    }

    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetaData(get_class(new QuestionnaireAnswer()))->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new QuestionnaireAnswer();
        $item1->setName("ausgezeichnet");
        $item1->setDescription("");
        $item1->setQuestion($this->getReference('questionnaire_question_1'));
        $item1->setCountPointStrain(0);
        $item1->setCountPointHealth(10);
        $manager->persist($item1);

        $item2 = new QuestionnaireAnswer();
        $item2->setName("sehr gut");
        $item2->setDescription("");
        $item2->setQuestion($this->getReference('questionnaire_question_1'));
        $item2->setCountPointStrain(0);
        $item2->setCountPointHealth(5);
        $manager->persist($item2);

        $item3 = new QuestionnaireAnswer();
        $item3->setName("gut");
        $item3->setDescription("");
        $item3->setQuestion($this->getReference('questionnaire_question_1'));
        $item3->setCountPointStrain(0);
        $item3->setCountPointHealth(0);
        $manager->persist($item3);

        $item4 = new QuestionnaireAnswer();
        $item4->setName("weniger gut");
        $item4->setDescription("");
        $item4->setQuestion($this->getReference('questionnaire_question_1'));
        $item4->setCountPointStrain(0);
        $item4->setCountPointHealth(-5);
        $manager->persist($item4);

        $item5 = new QuestionnaireAnswer();
        $item5->setName("schlecht");
        $item5->setDescription("");
        $item5->setQuestion($this->getReference('questionnaire_question_1'));
        $item5->setCountPointStrain(0);
        $item5->setCountPointHealth(-10);
        $manager->persist($item5);

        $item6 = new QuestionnaireAnswer();
        $item6->setName("Herz-Kreislaufsystem");
        $item6->setDescription("");
        $item6->setQuestion($this->getReference('questionnaire_question_2'));
        $item6->setCountPointStrain(0);
        $item6->setCountPointHealth(-5);
        $manager->persist($item6);

        $item7 = new QuestionnaireAnswer();
        $item7->setName("Muskel-Skelettsystem");
        $item7->setDescription("");
        $item7->setQuestion($this->getReference('questionnaire_question_2'));
        $item7->setCountPointStrain(0);
        $item7->setCountPointHealth(-5);
        $manager->persist($item7);

        $item8 = new QuestionnaireAnswer();
        $item8->setName("Psyche");
        $item8->setDescription("");
        $item8->setQuestion($this->getReference('questionnaire_question_2'));
        $item8->setCountPointStrain(0);
        $item8->setCountPointHealth(-5);
        $manager->persist($item8);

        $item9 = new QuestionnaireAnswer();
        $item9->setName("Atmungsorgane");
        $item9->setDescription("");
        $item9->setQuestion($this->getReference('questionnaire_question_2'));
        $item9->setCountPointStrain(0);
        $item9->setCountPointHealth(-5);
        $manager->persist($item9);

        $item10 = new QuestionnaireAnswer();
        $item10->setName("Magen-Darm-System");
        $item10->setDescription("");
        $item10->setQuestion($this->getReference('questionnaire_question_2'));
        $item10->setCountPointStrain(0);
        $item10->setCountPointHealth(-5);
        $manager->persist($item10);

        $item11 = new QuestionnaireAnswer();
        $item11->setName("Stoffwechselsystem");
        $item11->setDescription("");
        $item11->setQuestion($this->getReference('questionnaire_question_2'));
        $item11->setCountPointStrain(0);
        $item11->setCountPointHealth(-5);
        $manager->persist($item11);

        $item12 = new QuestionnaireAnswer();
        $item12->setName("keine Erkrankung");
        $item12->setDescription("");
        $item12->setQuestion($this->getReference('questionnaire_question_2'));
        $item12->setCountPointStrain(0);
        $item12->setCountPointHealth(15);
        $manager->persist($item12);

        $item13 = new QuestionnaireAnswer();
        $item13->setName("ja");
        $item13->setDescription("");
        $item13->setQuestion($this->getReference('questionnaire_question_3'));
        $item13->setCountPointStrain(0);
        $item13->setCountPointHealth(-5);
        $manager->persist($item13);

        $item14 = new QuestionnaireAnswer();
        $item14->setName("nein");
        $item14->setDescription("");
        $item14->setQuestion($this->getReference('questionnaire_question_3'));
        $item14->setCountPointStrain(0);
        $item14->setCountPointHealth(5);
        $manager->persist($item14);

        $item15 = new QuestionnaireAnswer();
        $item15->setName("ja");
        $item15->setDescription("");
        $item15->setQuestion($this->getReference('questionnaire_question_4'));
        $item15->setCountPointStrain(0);
        $item15->setCountPointHealth(-5);
        $manager->persist($item15);

        $item16 = new QuestionnaireAnswer();
        $item16->setName("nein");
        $item16->setDescription("");
        $item16->setQuestion($this->getReference('questionnaire_question_4'));
        $item16->setCountPointStrain(0);
        $item16->setCountPointHealth(5);
        $manager->persist($item16);

        $item17 = new QuestionnaireAnswer();
        $item17->setName("0");
        $item17->setDescription("");
        $item17->setQuestion($this->getReference('questionnaire_question_5'));
        $item17->setCountPointStrain(0);
        $item17->setCountPointHealth(10);
        $manager->persist($item17);

        $item18 = new QuestionnaireAnswer();
        $item18->setName("1");
        $item18->setDescription("");
        $item18->setQuestion($this->getReference('questionnaire_question_5'));
        $item18->setCountPointStrain(0);
        $item18->setCountPointHealth(10);
        $manager->persist($item18);

        $item19 = new QuestionnaireAnswer();
        $item19->setName("2");
        $item19->setDescription("");
        $item19->setQuestion($this->getReference('questionnaire_question_5'));
        $item19->setCountPointStrain(0);
        $item19->setCountPointHealth(5);
        $manager->persist($item19);

        $item20 = new QuestionnaireAnswer();
        $item20->setName("3");
        $item20->setDescription("");
        $item20->setQuestion($this->getReference('questionnaire_question_5'));
        $item20->setCountPointStrain(0);
        $item20->setCountPointHealth(5);
        $manager->persist($item20);

        $item21 = new QuestionnaireAnswer();
        $item21->setName("4");
        $item21->setDescription("");
        $item21->setQuestion($this->getReference('questionnaire_question_5'));
        $item21->setCountPointStrain(0);
        $item21->setCountPointHealth(0);
        $manager->persist($item21);

        $item22 = new QuestionnaireAnswer();
        $item22->setName("5");
        $item22->setDescription("");
        $item22->setQuestion($this->getReference('questionnaire_question_5'));
        $item22->setCountPointStrain(0);
        $item22->setCountPointHealth(0);
        $manager->persist($item22);

        $item23 = new QuestionnaireAnswer();
        $item23->setName("6");
        $item23->setDescription("");
        $item23->setQuestion($this->getReference('questionnaire_question_5'));
        $item23->setCountPointStrain(0);
        $item23->setCountPointHealth(-5);
        $manager->persist($item23);

        $item24 = new QuestionnaireAnswer();
        $item24->setName("7");
        $item24->setDescription("");
        $item24->setQuestion($this->getReference('questionnaire_question_5'));
        $item24->setCountPointStrain(0);
        $item24->setCountPointHealth(-5);
        $manager->persist($item24);

        $item25 = new QuestionnaireAnswer();
        $item25->setName("8");
        $item25->setDescription("");
        $item25->setQuestion($this->getReference('questionnaire_question_5'));
        $item25->setCountPointStrain(0);
        $item25->setCountPointHealth(-15);
        $manager->persist($item25);

        $item26 = new QuestionnaireAnswer();
        $item26->setName("9");
        $item26->setDescription("");
        $item26->setQuestion($this->getReference('questionnaire_question_5'));
        $item26->setCountPointStrain(0);
        $item26->setCountPointHealth(-15);
        $manager->persist($item26);

        $item27 = new QuestionnaireAnswer();
        $item27->setName("10");
        $item27->setDescription("");
        $item27->setQuestion($this->getReference('questionnaire_question_5'));
        $item27->setCountPointStrain(0);
        $item27->setCountPointHealth(-15);
        $manager->persist($item27);

        $item28 = new QuestionnaireAnswer();
        $item28->setName("0");
        $item28->setDescription("");
        $item28->setQuestion($this->getReference('questionnaire_question_6'));
        $item28->setCountPointStrain(0);
        $item28->setCountPointHealth(10);
        $manager->persist($item28);

        $item29 = new QuestionnaireAnswer();
        $item29->setName("1");
        $item29->setDescription("");
        $item29->setQuestion($this->getReference('questionnaire_question_6'));
        $item29->setCountPointStrain(0);
        $item29->setCountPointHealth(10);
        $manager->persist($item29);

        $item30 = new QuestionnaireAnswer();
        $item30->setName("2");
        $item30->setDescription("");
        $item30->setQuestion($this->getReference('questionnaire_question_6'));
        $item30->setCountPointStrain(0);
        $item30->setCountPointHealth(5);
        $manager->persist($item30);

        $item31 = new QuestionnaireAnswer();
        $item31->setName("3");
        $item31->setDescription("");
        $item31->setQuestion($this->getReference('questionnaire_question_6'));
        $item31->setCountPointStrain(0);
        $item31->setCountPointHealth(5);
        $manager->persist($item31);

        $item32 = new QuestionnaireAnswer();
        $item32->setName("4");
        $item32->setDescription("");
        $item32->setQuestion($this->getReference('questionnaire_question_6'));
        $item32->setCountPointStrain(0);
        $item32->setCountPointHealth(0);
        $manager->persist($item32);

        $item33 = new QuestionnaireAnswer();
        $item33->setName("5");
        $item33->setDescription("");
        $item33->setQuestion($this->getReference('questionnaire_question_6'));
        $item33->setCountPointStrain(0);
        $item33->setCountPointHealth(0);
        $manager->persist($item33);

        $item34 = new QuestionnaireAnswer();
        $item34->setName("6");
        $item34->setDescription("");
        $item34->setQuestion($this->getReference('questionnaire_question_6'));
        $item34->setCountPointStrain(0);
        $item34->setCountPointHealth(-5);
        $manager->persist($item34);

        $item35 = new QuestionnaireAnswer();
        $item35->setName("7");
        $item35->setDescription("");
        $item35->setQuestion($this->getReference('questionnaire_question_6'));
        $item35->setCountPointStrain(0);
        $item35->setCountPointHealth(-5);
        $manager->persist($item35);

        $item36 = new QuestionnaireAnswer();
        $item36->setName("8");
        $item36->setDescription("");
        $item36->setQuestion($this->getReference('questionnaire_question_6'));
        $item36->setCountPointStrain(0);
        $item36->setCountPointHealth(-15);
        $manager->persist($item36);

        $item37 = new QuestionnaireAnswer();
        $item37->setName("9");
        $item37->setDescription("");
        $item37->setQuestion($this->getReference('questionnaire_question_6'));
        $item37->setCountPointStrain(0);
        $item37->setCountPointHealth(-15);
        $manager->persist($item37);

        $item38 = new QuestionnaireAnswer();
        $item38->setName("10");
        $item38->setDescription("");
        $item38->setQuestion($this->getReference('questionnaire_question_6'));
        $item38->setCountPointStrain(0);
        $item38->setCountPointHealth(-15);
        $manager->persist($item38);

        $item39 = new QuestionnaireAnswer();
        $item39->setName("0");
        $item39->setDescription("");
        $item39->setQuestion($this->getReference('questionnaire_question_9'));
        $item39->setCountPointStrain(10);
        $item39->setCountPointHealth(0);
        $manager->persist($item39);

        $item40 = new QuestionnaireAnswer();
        $item40->setName("1");
        $item40->setDescription("");
        $item40->setQuestion($this->getReference('questionnaire_question_9'));
        $item40->setCountPointStrain(5);
        $item40->setCountPointHealth(0);
        $manager->persist($item40);

        $item41 = new QuestionnaireAnswer();
        $item41->setName("2");
        $item41->setDescription("");
        $item41->setQuestion($this->getReference('questionnaire_question_9'));
        $item41->setCountPointStrain(0);
        $item41->setCountPointHealth(0);
        $manager->persist($item41);

        $item42 = new QuestionnaireAnswer();
        $item42->setName("3");
        $item42->setDescription("");
        $item42->setQuestion($this->getReference('questionnaire_question_9'));
        $item42->setCountPointStrain(0);
        $item42->setCountPointHealth(0);
        $manager->persist($item42);

        $item43 = new QuestionnaireAnswer();
        $item43->setName("4");
        $item43->setDescription("");
        $item43->setQuestion($this->getReference('questionnaire_question_9'));
        $item43->setCountPointStrain(-5);
        $item43->setCountPointHealth(0);
        $manager->persist($item43);

        $item44 = new QuestionnaireAnswer();
        $item44->setName("5");
        $item44->setDescription("");
        $item44->setQuestion($this->getReference('questionnaire_question_9'));
        $item44->setCountPointStrain(-10);
        $item44->setCountPointHealth(0);
        $manager->persist($item44);

        $item45 = new QuestionnaireAnswer();
        $item45->setName("0");
        $item45->setDescription("");
        $item45->setQuestion($this->getReference('questionnaire_question_10'));
        $item45->setCountPointStrain(10);
        $item45->setCountPointHealth(0);
        $manager->persist($item45);

        $item46 = new QuestionnaireAnswer();
        $item46->setName("1");
        $item46->setDescription("");
        $item46->setQuestion($this->getReference('questionnaire_question_10'));
        $item46->setCountPointStrain(5);
        $item46->setCountPointHealth(0);
        $manager->persist($item46);

        $item47 = new QuestionnaireAnswer();
        $item47->setName("2");
        $item47->setDescription("");
        $item47->setQuestion($this->getReference('questionnaire_question_10'));
        $item47->setCountPointStrain(0);
        $item47->setCountPointHealth(0);
        $manager->persist($item47);

        $item48 = new QuestionnaireAnswer();
        $item48->setName("3");
        $item48->setDescription("");
        $item48->setQuestion($this->getReference('questionnaire_question_10'));
        $item48->setCountPointStrain(0);
        $item48->setCountPointHealth(0);
        $manager->persist($item48);

        $item49 = new QuestionnaireAnswer();
        $item49->setName("4");
        $item49->setDescription("");
        $item49->setQuestion($this->getReference('questionnaire_question_10'));
        $item49->setCountPointStrain(-5);
        $item49->setCountPointHealth(0);
        $manager->persist($item49);

        $item50 = new QuestionnaireAnswer();
        $item50->setName("5");
        $item50->setDescription("");
        $item50->setQuestion($this->getReference('questionnaire_question_10'));
        $item50->setCountPointStrain(-10);
        $item50->setCountPointHealth(0);
        $manager->persist($item50);

        $item51 = new QuestionnaireAnswer();
        $item51->setId(51);
        $item51->setName("0");
        $item51->setDescription("");
        $item51->setQuestion($this->getReference('questionnaire_question_11'));
        $item51->setCountPointStrain(10);
        $item51->setCountPointHealth(0);
        $manager->persist($item51);

        $item52 = new QuestionnaireAnswer();
        $item52->setName("1");
        $item52->setDescription("");
        $item52->setQuestion($this->getReference('questionnaire_question_11'));
        $item52->setCountPointStrain(5);
        $item52->setCountPointHealth(0);
        $manager->persist($item52);

        $item53 = new QuestionnaireAnswer();
        $item53->setName("2");
        $item53->setDescription("");
        $item53->setQuestion($this->getReference('questionnaire_question_11'));
        $item53->setCountPointStrain(0);
        $item53->setCountPointHealth(0);
        $manager->persist($item53);

        $item54 = new QuestionnaireAnswer();
        $item54->setName("3");
        $item54->setDescription("");
        $item54->setQuestion($this->getReference('questionnaire_question_11'));
        $item54->setCountPointStrain(0);
        $item54->setCountPointHealth(0);
        $manager->persist($item54);

        $item55 = new QuestionnaireAnswer();
        $item55->setName("4");
        $item55->setDescription("");
        $item55->setQuestion($this->getReference('questionnaire_question_11'));
        $item55->setCountPointStrain(-5);
        $item55->setCountPointHealth(0);
        $manager->persist($item55);

        $item56 = new QuestionnaireAnswer();
        $item56->setName("5");
        $item56->setDescription("");
        $item56->setQuestion($this->getReference('questionnaire_question_11'));
        $item56->setCountPointStrain(-10);
        $item56->setCountPointHealth(0);
        $manager->persist($item56);

        $item57 = new QuestionnaireAnswer();
        $item57->setName("0");
        $item57->setDescription("");
        $item57->setQuestion($this->getReference('questionnaire_question_12'));
        $item57->setCountPointStrain(10);
        $item57->setCountPointHealth(0);
        $manager->persist($item57);

        $item58 = new QuestionnaireAnswer();
        $item58->setName("1");
        $item58->setDescription("");
        $item58->setQuestion($this->getReference('questionnaire_question_12'));
        $item58->setCountPointStrain(5);
        $item58->setCountPointHealth(0);
        $manager->persist($item58);

        $item59 = new QuestionnaireAnswer();
        $item59->setName("2");
        $item59->setDescription("");
        $item59->setQuestion($this->getReference('questionnaire_question_12'));
        $item59->setCountPointStrain(0);
        $item59->setCountPointHealth(0);
        $manager->persist($item59);

        $item60 = new QuestionnaireAnswer();
        $item60->setName("3");
        $item60->setDescription("");
        $item60->setQuestion($this->getReference('questionnaire_question_12'));
        $item60->setCountPointStrain(0);
        $item60->setCountPointHealth(0);
        $manager->persist($item60);

        $item61 = new QuestionnaireAnswer();
        $item61->setName("4");
        $item61->setDescription("");
        $item61->setQuestion($this->getReference('questionnaire_question_12'));
        $item61->setCountPointStrain(-5);
        $item61->setCountPointHealth(0);
        $manager->persist($item61);

        $item62 = new QuestionnaireAnswer();
        $item62->setName("5");
        $item62->setDescription("");
        $item62->setQuestion($this->getReference('questionnaire_question_12'));
        $item62->setCountPointStrain(-10);
        $item62->setCountPointHealth(0);
        $manager->persist($item62);

        $item64 = new QuestionnaireAnswer();
        $item64->setName("ich sitze immer");
        $item64->setDescription("");
        $item64->setQuestion($this->getReference('questionnaire_question_13'));
        $item64->setCountPointStrain(0);
        $item64->setCountPointHealth(0);
        $manager->persist($item64);

        $item65 = new QuestionnaireAnswer();
        $item65->setName("1 Stunde oder mehr");
        $item65->setDescription("");
        $item65->setQuestion($this->getReference('questionnaire_question_13'));
        $item65->setCountPointStrain(0);
        $item65->setCountPointHealth(0);
        $manager->persist($item65);

        $item66 = new QuestionnaireAnswer();
        $item66->setName("2 Stunden oder mehr");
        $item66->setDescription("");
        $item66->setQuestion($this->getReference('questionnaire_question_13'));
        $item66->setCountPointStrain(0);
        $item66->setCountPointHealth(0);
        $manager->persist($item66);

        $item67 = new QuestionnaireAnswer();
        $item67->setName("3 Stunden oder mehr");
        $item67->setDescription("");
        $item67->setQuestion($this->getReference('questionnaire_question_13'));
        $item67->setCountPointStrain(0);
        $item67->setCountPointHealth(0);
        $manager->persist($item67);

        $item68 = new QuestionnaireAnswer();
        $item68->setName("4 Stunden oder mehr");
        $item68->setDescription("");
        $item68->setQuestion($this->getReference('questionnaire_question_13'));
        $item68->setCountPointStrain(-10);
        $item68->setCountPointHealth(0);
        $manager->persist($item68);

        $item69 = new QuestionnaireAnswer();
        $item69->setName("5 Stunden oder mehr");
        $item69->setDescription("");
        $item69->setQuestion($this->getReference('questionnaire_question_13'));
        $item69->setCountPointStrain(-10);
        $item69->setCountPointHealth(0);
        $manager->persist($item69);

        $item70 = new QuestionnaireAnswer();
        $item70->setName("6 Stunden oder mehr");
        $item70->setDescription("");
        $item70->setQuestion($this->getReference('questionnaire_question_13'));
        $item70->setCountPointStrain(-10);
        $item70->setCountPointHealth(0);
        $manager->persist($item70);

        $item71 = new QuestionnaireAnswer();
        $item71->setName("7 Stunden oder mehr");
        $item71->setDescription("");
        $item71->setQuestion($this->getReference('questionnaire_question_13'));
        $item71->setCountPointStrain(-10);
        $item71->setCountPointHealth(0);
        $manager->persist($item71);

        $item72 = new QuestionnaireAnswer();
        $item72->setName("ich stehe immer");
        $item72->setDescription("");
        $item72->setQuestion($this->getReference('questionnaire_question_14'));
        $item72->setCountPointStrain(0);
        $item72->setCountPointHealth(0);
        $manager->persist($item72);

        $item73 = new QuestionnaireAnswer();
        $item73->setName("1 Stunde oder mehr");
        $item73->setDescription("");
        $item73->setQuestion($this->getReference('questionnaire_question_14'));
        $item73->setCountPointStrain(0);
        $item73->setCountPointHealth(0);
        $manager->persist($item73);

        $item74 = new QuestionnaireAnswer();
        $item74->setName("2 Stunden oder mehr");
        $item74->setDescription("");
        $item74->setQuestion($this->getReference('questionnaire_question_14'));
        $item74->setCountPointStrain(0);
        $item74->setCountPointHealth(0);
        $manager->persist($item74);

        $item75 = new QuestionnaireAnswer();
        $item75->setName("3 Stunden oder mehr");
        $item75->setDescription("");
        $item75->setQuestion($this->getReference('questionnaire_question_14'));
        $item75->setCountPointStrain(0);
        $item75->setCountPointHealth(0);
        $manager->persist($item75);

        $item76 = new QuestionnaireAnswer();
        $item76->setName("4 Stunden oder mehr");
        $item76->setDescription("");
        $item76->setQuestion($this->getReference('questionnaire_question_14'));
        $item76->setCountPointStrain(-10);
        $item76->setCountPointHealth(0);
        $manager->persist($item76);

        $item77 = new QuestionnaireAnswer();
        $item77->setName("5 Stunden oder mehr");
        $item77->setDescription("");
        $item77->setQuestion($this->getReference('questionnaire_question_14'));
        $item77->setCountPointStrain(-10);
        $item77->setCountPointHealth(0);
        $manager->persist($item77);

        $item78 = new QuestionnaireAnswer();
        $item78->setName("6 Stunden oder mehr");
        $item78->setDescription("");
        $item78->setQuestion($this->getReference('questionnaire_question_14'));
        $item78->setCountPointStrain(-10);
        $item78->setCountPointHealth(0);
        $manager->persist($item78);

        $item79 = new QuestionnaireAnswer();
        $item79->setName("7 Stunden oder mehr");
        $item79->setDescription("");
        $item79->setQuestion($this->getReference('questionnaire_question_14'));
        $item79->setCountPointStrain(-10);
        $item79->setCountPointHealth(0);
        $manager->persist($item79);

        $item81 = new QuestionnaireAnswer();
        $item81->setName("0");
        $item81->setDescription("");
        $item81->setQuestion($this->getReference('questionnaire_question_15'));
        $item81->setCountPointStrain(-10);
        $item81->setCountPointHealth(0);
        $manager->persist($item81);

        $item82 = new QuestionnaireAnswer();
        $item82->setName("1");
        $item82->setDescription("");
        $item82->setQuestion($this->getReference('questionnaire_question_15'));
        $item82->setCountPointStrain(-5);
        $item82->setCountPointHealth(0);
        $manager->persist($item82);

        $item83 = new QuestionnaireAnswer();
        $item83->setName("2");
        $item83->setDescription("");
        $item83->setQuestion($this->getReference('questionnaire_question_15'));
        $item83->setCountPointStrain(0);
        $item83->setCountPointHealth(0);
        $manager->persist($item83);

        $item84 = new QuestionnaireAnswer();
        $item84->setName("3");
        $item84->setDescription("");
        $item84->setQuestion($this->getReference('questionnaire_question_15'));
        $item84->setCountPointStrain(0);
        $item84->setCountPointHealth(0);
        $manager->persist($item84);

        $item85 = new QuestionnaireAnswer();
        $item85->setName("4");
        $item85->setDescription("");
        $item85->setQuestion($this->getReference('questionnaire_question_15'));
        $item85->setCountPointStrain(5);
        $item85->setCountPointHealth(0);
        $manager->persist($item85);

        $item86 = new QuestionnaireAnswer();
        $item86->setName("5");
        $item86->setDescription("");
        $item86->setQuestion($this->getReference('questionnaire_question_15'));
        $item86->setCountPointStrain(10);
        $item86->setCountPointHealth(0);
        $manager->persist($item86);

        $manager->flush();
    }

}
