<?php

namespace Fitbase\Bundle\QuestionnaireBundle\DataFixture\ORM;
;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Fitbase\Bundle\QuestionnaireBundle\Entity\Questionnaire;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadQuestionnaireData extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetaData(get_class(new Questionnaire()))->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item1 = new Questionnaire();
        $item1->setName("Das erste Fragebogen");
        $item1->setDescription(<<<CONTENT
Bitte neu programmieren wie angedacht, so dass man Fragen ergänzen und ändern und gut auswerten kann. Wir wollen Unternehmen über die Auswertung einen Rücken-Score zur Verfügung stellen können, der einen groben Überblick über den Zustand der Mitarbeiter im Bereich Rückengesundheit gibt.

Später brauchen wir die Fragebogen-Funktion für die Weiterentwicklung von Fitbase. Vielleicht kannst Du Teile von der Quiz-Funktion verwenden, aber wir benötigen dennoch verschiedene Antwortmöglichkeiten. Wichtiger als der Zeitaufwand ist eine gute Usability.
Vielleicht kannst Du schon anfangen, auch wenn der Fragebogen noch nicht final steht.
CONTENT
        );
        $manager->persist($item1);
        $manager->flush();

        $this->addReference('questionnaire_1', $item1);
    }

}
