<?php

namespace Fitbase\Bundle\GamificationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AvatarHasGalleryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AvatarHasGalleryRepository extends EntityRepository
{
}
