<?php

namespace Fitbase\Bundle\GamificationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GamificationSettingsGalleryTreeHasMediaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamificationSettingsGalleryTreeHasMediaRepository extends EntityRepository
{
}
