<?php

namespace Fitbase\Bundle\WeeklytaskBundle\DataFixture\ORM;
;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Fitbase\Bundle\WeeklytaskBundle\Entity\Weeklytask;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadWeeklytaskAugenData extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 2;
    }


    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetaData(get_class(new Weeklytask()))->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);


        $item2066 = new Weeklytask();
        $item2066->setFormat("richhtml");
        $item2066->setTag("Augen");
        $item2066->setWeekId(47);
        $item2066->setCountPoint(1);
        $item2066->setName("Wochenaufgabe 47");
        $item2066->setCategory($this->getReference('category_augen'));
        $item2066->setContent(<<<EOT
<em> Wir haben bereits verschiedene körperliche Symptome betrachtet, die durch Stress verursacht werden und uns zudem angeschaut, mit welchen Sofortmaßnahmen man dem entgegen wirken kann. In den kommenden Einheiten werfen wir einen Blick auf unsere Augen und die Auswirkungen von Stress auf das Sehen.</em>
<strong> Warum strengt Bildschirmarbeit die Augen an ?</strong>
<a href = "http://online-rueckenschule.de/wp-content/uploads/WA-47.png"><img src = "http://online-rueckenschule.de/wp-content/uploads/WA-47.png" alt = "WA 47" width = "254" height = "228" class="alignright wp-image-2124 size-full" /></a> Ursprünglich ist das Sehen in der Nähe an den Entspannungszustand des vegetativen Nervensystems gekoppelt(vgl. <a href = "http://online-rueckenschule.de/mitgliederbereich/wochenaufgaben/wochenaufgabe-41/" target = "_blank"> Wochenaufgabe 41 </a>).
Bildschirmarbeit zwingt den Menschen oft durch statische  Körperhaltung und starre Blickposition in eine unbewegte und damit nicht entspannte Haltung. Zeitdruck oder hohe nervliche Beanspruchung verursachen Anspannungen, der Körper reagiert mit Stressphänomenen, d. h. Hormonausschüttungen, Veränderung von Herzschlag und Atmung.
Bei der Arbeit am Bildschirm sind die Augenlinse und die Augenmuskeln über lange Zeit auf einen kleinen Raum und eine gleiche Entfernung fixiert. Lidschläge erfolgen nicht mehr so häufig, dadurch werden die Sauerstoffversorgung und der Stoffwechsel des Auges reduziert. Die Augenlinse, zuständig für die Scharfeinstellung, verkrampft und verhärtet. Lesebrillen werden früher erforderlich.
Klassisches räumliches Sehen bedeutet, dass die Seheindrücke von rechtem und linkem Augen im Gehirn zu einem Bild fusioniert werden. Die Zweidimensionalität des Bildschirms erfordert nicht unbedingt räumliches Sehen und die Augen stellen sich darauf ein. Häufig übernimmt dann nur ein Auge die anstrengenden Sehaufgaben in der Nähe.
Gute Koordination der Augen und abwechslungsreiches, entspanntes  Sehen sind eine Voraussetzungen für  langanhaltende Konzentration und Erhalt der Arbeitsfähigkeit am Bildschirm. Nutzen Sie daher unsere Augenübungen, vor allem die folgende Übung: <a href = "http://online-rueckenschule.de/mitgliederbereich/uebungen/augen-entspannung/augenbewegung/" target = "_blank"> Link zur Übung </a>
<strong> Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie einige Minuten in Ihre Augengesundheit. Vielen Dank!</strong>
Interesse geweckt ? Mehr dazu finden Sie auf unserer ganzheitlichen Gesundheits - Plattform <a href = "http://www.fitbase.de/"> www. fitbase. de</a>. Hier finden Sie z. B. ein interaktives Sehtraining…
EOT
        );
        $manager->persist($item2066);


        $item2069 = new Weeklytask();
        $item2069->setFormat("richhtml");
        $item2069->setTag("Augen");
        $item2069->setWeekId(48);
        $item2069->setCountPoint(1);
        $item2069->setName("Wochenaufgabe 48");
        $item2069->setCategory($this->getReference('category_augen'));
        $item2069->setContent(<<<EOT
<em> Die heutige Wochenaufgabe beschäftigt sich mit dem Zusammenhang von Stress und Sehen, erklärt wie trockene und müde Augen enstehen und wie Sie sie vermeiden.</em><strong></strong>
<a href = "http://online-rueckenschule.de/wp-content/uploads/WA-48.png"><img src = "http://online-rueckenschule.de/wp-content/uploads/WA-48-300x198.png" alt = "WA 48" width = "300" height = "198" class="alignright wp-image-2126 size-medium" /></a><a href = "http://www.officephysio.de/memberarea/weeklytask/weeklytask48/augen/" rel = "attachment wp-att-5989"></a> Die meisten inneren Vorgänge des Körpers werden vom vegetativen, nicht willentlich beeinflussbaren, Nervensystem gesteuert. Ursprünglich gepolt als Kampf - und Fluchtmuster reagiert der Körper blitzschnell auf wahrgenommene Bedrohungen durch Ausschüttung von Hormonen und bestimmten Körperreaktionen(vgl. Wochenaufgaben 41 - 43).
Man unterscheidet zwischen <strong>Sympathikus </strong>, dem Anspannungszustand  und <strong>Parasympathikus </strong>, dem Entspannungszustand, die als Gegenspieler fungieren. Auch das Sehen in Ferne und Nähe ist abhängig von den Zuständen des Nervensystems(vgl. kommende Einheit).
Normalerweise ist das Sehen in der Nähe mit Entspannung verbunden, die Atmung wird ruhiger, weniger Adrenalin wird produziert und die Tränenproduktion steigt. Wenn wir nun aber angespannt vor dem Computer sitzen wird der Sympathikus aktiviert und aus dem Ruhezustand wird ein Anspannungszustand: die Augen bewegen sich wenig, mehr Adrenalin wird freigesetzt und es werden kaum Tränen produziert. Das führt zu trockenen und müden Augen.
Folgende Tabelle zeigt eine Auswahl der Zusammenhänge:
<a href = "http://online-rueckenschule.de/wp-content/uploads/WA-48-Tabelle.png"><img src = "http://online-rueckenschule.de/wp-content/uploads/WA-48-Tabelle.png" alt = "WA 48 Tabelle" width = "509" height = "375" class="alignleft wp-image-2127 size-full" /></a>
<strong>
Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie wenige Minuten in Ihre Augengesundheit. Vielen Dank!</strong> Um diesem Effekt entgegenzuwirken, empfiehlt es sich, zwischendurch eine Entspannungsübung durchzuführen, den starren Blick auf den Bildschirm zu unterbrechen und bewusst zu blinzeln.
<em> Wie geht es weiter ? Wir vertiefen die Thematik und stellen einen Zusammenhang zwischen Stress und Sehen her…</em>
EOT
        );
        $manager->persist($item2069);


        $item2071 = new Weeklytask();
        $item2071->setFormat("richhtml");
        $item2071->setTag("Augen");
        $item2071->setWeekId(49);
        $item2071->setCountPoint(1);
        $item2071->setName("Wochenaufgabe 49");
        $item2071->setCategory($this->getReference('category_augen'));
        $item2071->setContent(<<<EOT
Herzlich Willkommen zur 49. Wochenaufgabe, die sich erneut mit dem Zusammenhang von Sehen und Stress beschäftigt und der Frage auf den Grund geht, warum man bei Stress schlechter sieht.
<span style = "color: #808080"> Eine kurze Wiederholung: Im vegetativen Nervensystem sprechen wir von zwei gegensätzlichen Funktionen:  </span>
<strong> 1. sympathisches Nervensystem für Aktivität und Leistung </strong>
<strong> 2. parasympathisches Nervensystem für Erholung, Entspannung und Energieaufbau. </strong>
Beide Systeme sind im Normalzustand in einer natürlichen Balance, d. h. der Sympathikus wird durch den Parasympathikus abgelöst und umgekehrt.
Bei Stress ist diese Balance gestört: So bewirkt das <strong>sympathische Nervensystem </strong> -neben vielen weiteren Auswirkungen wie Adrenalinausschüttung, Muskelanspannung, Steigerung des Herzschlages etc. -eine Erweiterung der Pupillen. Dadurch wird mehr Licht durchgelassen, die Augen sind lichtempfindlicher gleichzeitig schränkt sich aber das Gesichtsfeld ein.
Das <strong>sympathische </strong> <strong>  Nervensystem </strong> steuert<strong> </strong> die Scharfeinstellung der Augenlinse auf Entfernungen, dabei kommt es zu einer Abflachung der Augenlinsen in der Ferne. Vor allem Objekte ab 6 Meter Entfernung werden dann besonders gut wahrgenommen – also in der Entfernung, in der während der menschlichen Entwicklung akute Gefahr z. B. in Form eines Angreifers erschienen ist.
In einer Entspannungsphase bewirkt das <strong>parasympathische Nervensystem </strong> eine Krümmung der Augenlinsen, was eine verbesserte Nahsicht ermöglicht.
Das Problem ist, dass wir heutzutage visuellen Stress fast ausschließlich in der Nähe erleben, nämlich auf dem Bildschirm oder im Gesprächspartner gegenüber und kaum in einer Entfernung ab 6 Metern, so wie es unser vegetatives Nervensystem nach Jahrtausenden der Entwicklung vorsieht.
Um es noch deutlicher zu machen: In einer akuten Stresssituation können wir schlecht Lesen, was auf dem Bildschirm steht, da der Körper die Augen so einstellt, dass sie Dinge in der Entfernung scharf sehen. Wir schauen aber meist nicht in die Ferne sondern auf den Bildschirm.
Folglich müssen wir in Stresssituationen die Augen mit Entspannungsübungen entlasten und den Stresspegel senken, um entspannt am Bildschirm weiter arbeiten zu können.
<strong> Augenbewegung</strong>
<a href = "http://online-rueckenschule.de/wp-content/uploads/augenbewegung.jpg"><img src = "http://online-rueckenschule.de/wp-content/uploads/augenbewegung.jpg" alt = "augenbewegung" width = "229" height = "231" class="alignright wp-image-1004 size-full" /></a><a href = "http://www.officephysio.de/memberarea/weeklytask/weeklytask49/augenbewegung/" rel = "attachment wp-att-6014"></a> Eine praktische Übung, die zur Anspannung und Entspannung der Augenmuskulatur führt erreichen Sie über folgenden Link: <a href = "http://www.officephysio.de/memberarea/exercises/eye-relaxation/eye-8/" target = "_blank"> Übung</a>
Zudem wird auch hier die Körpermitte überschritten, was zu einem besseren Zusammenspiel der beiden Gehirnhälften führt(vgl. Wochenaufgabe 19 - 23).
<strong> Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie einige Minuten in Ihre Augengesundheit. Vielen Dank!</strong>
EOT
        );
        $manager->persist($item2071);


        $item531 = new Weeklytask();
        $item531->setFormat("richhtml");
        $item531->setTag("Augen");
        $item531->setCountPoint(1);
        $item531->setName("Sehen mit dem ganzen Gehirn ");
        $item531->setCategory($this->getReference('category_augen'));
        $item531->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur zweiten Einheit Ihres Sehtrainings. Um die Chancen und Möglichkeiten des Sehtrainings kennen zu lernen, ist es wichtig, sich zuerst vor Augen zu führen, wie Sehen funktioniert.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Rein organisch gesehen  trifft dazu Licht auf das Auge und durchläuft mehrere lichtbrechende optische Medien, bevor es auf die hinten im Augapfel gelegene Netzhaut mit  lichtempfindlichen Zellen trifft. Im zentralen Bereich der Netzhaut ist eine scharfe, im umgebenden Areal unscharfe Abbildung vorhanden.  Im Idealfall sehen beide Augen ähnliche und gleichwertige Eindrücke.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Die Zapfen und Stäbchen genannten Sehzellen der Netzhaut verwandeln das Licht in elektrische Impulse, die über den Sehnerven ins Gehirn geleitet werden.</p>
<p style="text-align: center"><a href="https://www.fitbase.de/mitgliederbereich/module/augenfit/e-mails/1-sehen-mit-dem-ganzen-gehirn/af_1-2/" rel="attachment wp-att-551"><img class=" wp-image-551 aligncenter" title="af_1" alt="" src="https://www.fitbase.de/wp-content/uploads/af_11.png" width="286" height="324" /></a></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Dort erfolgt die Verarbeitung auf neuronaler Ebene und besonders in den beiden unterschiedlichen Gehirnhälften verteilt. Das scharfe (<b>fokussierte</b>) Sehen  wird von beiden Augen in die linke Gehirnhälfte, die <b>"Verstandesgehirnhälfte"</b>  geleitet. Das unscharfe (<b>periphere</b>) Sehen aus den Bereichen neben der Netzhautgrube, landet im  rechten Teil, der <b>"Emotionsgehirnhälfte". </b>Wir können unsere Umwelt am besten verstandesmäßig beurteilen und vom Gefühl erfassen, wenn beide  Anteile des Sehens ausgewogen vorhanden sind.</p>
<strong>Die Gehirnhälften:Rechts wird gelacht, Links wird gedacht.</strong>
<b>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</b>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? Wir beschäftigen uns mit den vier Bereichen des Sehens…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item531);

        $item532 = new Weeklytask();
        $item532->setFormat("richhtml");
        $item532->setTag("Augen");
        $item532->setCountPoint(1);
        $item532->setName("Sehen - ein fast olympische Disziplin ");
        $item532->setCategory($this->getReference('category_augen'));
        $item532->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur dritten Lektion Ihres Sehtrainings, die sich mit den unterschiedlichen Bereichen des Sehens beschäftigt.
Von der Kindheit bis zum Erwachsenenalter durchläuft unser Sehen verschiedene Entwicklungsschritte, die mit der Verarbeitung der Seheindrücke im Gehirn korrespondieren.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Nach dem amerikanischen Optometristen Arthur Skeffington sind sie bezeichnet als die <strong>"Vier Kreise von Skeffington".</strong></p>
<p style="margin: 0px;font-size: 14px;color: #333333;font-weight: normal;padding: 0px 0px 20px;line-height: 22px;text-align: center"><img class="size-medium wp-image-6420 aligncenter" alt="af_2" src="https://www.fitbase.de/wp-content/uploads/af_21-300x265.png" width="300" height="265" /></p>
<h1 style="font-weight: bold;padding: 0;margin: 0;font-size: 14px;color: #6d8295">Die Entwicklung des Sehens</h1>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Augenbewegungen</strong> sind in der Entwicklung des Sehens der erste Schritt mit der Umwelt Kontakt aufzunehmen. Das Sehen ist noch unscharf und unkoordiniert. Das Ausrichten des Körpers gegen die Schwerkraft , Finden der Körperbalance und das Unterscheiden von Vorder- und Hintergrund entwickeln sich. Die Augenbeweglichkeit wird als Grundlage der eigenen Orientierung im Raum angesehen, kurz mit der Frage: <strong>Wo bin ich?</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Beidäugigkeit</strong> bedeutet das gezielte Ausrichten beider Augen auf ein Objekt des Interesses. Die Sehschärfe entwickelt sich langsam und räumliches Sehen entsteht durch Fusion der Bilder von rechtem und linkem Auge. Sich selbst im Raum erleben und sowohl körperlich als auch visuell zu begreifen mit der Frage: <strong>Wo ist der/das Andere?</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Scharf Sehen</strong> durch die Möglichkeit der Augenlinsen zu "Akkommodieren" heißt, das Gesehene genauer erfassen und unterscheiden zu können. Die Seheindrücke bekommen Bedeutung und Wiedererkennungswert korrespondierend mit der Entwicklung des Gehirns diese Eindrücke zu verarbeiten. <strong>Was ist es?</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Wahrnehmung</strong> bedeutet ein eigenes Bewerten aufgrund von Emotionen und Assoziationen. Zusammenhänge zwischen Sprache und Hören werden integriert und die Fähigkeit zur Visualisation schafft die Möglichkeit, sich ein geistiges Bild von der Welt zu machen, verbunden mit der Frage: <strong>Wie ist es?</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Im Folgenden werden Übungen aus den vier Bereichen des Sehens vorgestellt, da sie auch im Erwachsenenalter zu den Grundfunktionen des Sehens gehören und als Voraussetzung für störungsfreies und entspanntes Sehen gelten.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? In der kommenden Einheit befassen wir uns mit der Augenbeweglichkeit…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item532);

        $item533 = new Weeklytask();
        $item533->setFormat("richhtml");
        $item533->setTag("Augen");
        $item533->setCountPoint(1);
        $item533->setName("Augenbeweglichkeit");
        $item533->setCategory($this->getReference('category_augen'));
        $item533->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur vierten Einheit Ihres Sehtrainings, die sich mit der Augenbeweglichkeit beschäftigt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Hoffentlich haben Sie in den vergangenen Tagen bereits unseren Email-Service genutzt und tägliche Übungen für die Augen gemacht. Die folgende Übung möchten wir heute einmal vertiefen:<span style="font-size: 13px"> </span></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Übung: Die liegende Acht</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Bitte sitzen oder stehen Sie aufrecht für diese Übung</p>
<ul>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Strecken Sie einen Arm vor sich in der Körpermitte aus und halten Sie den Daumen hoch, so als ob Sie das "Top"- Zeichen zeigen würden.</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Der Blick richtet sich auf den Daumen und Sie beginnen, mit dem Daumen eine liegende Acht (∞) in die Luft zu zeichnen.</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Nur der Blick folgt der Bewegung des Daumens, dabei bleibt der Kopf entspannt aber unbewegt.</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Nehmen Sie sowohl den Daumen wahr, wie auch den unscharfen, sich bewegenden Hintergrund. Die "Acht" sollte so groß sein, dass sich Ihre Augen bis zum Rand des Gesichtsfeldes bewegen aber der Bewegung des Daumens noch folgen können.</li>
</ul>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Dauer: ca. 1 Minute</p>
<p style="margin: 0px;font-size: 14px;color: #333333;font-weight: normal;padding: 0px 0px 20px;line-height: 22px;text-align: center"><img class="size-full wp-image-6424 aligncenter" alt="af_4" src="https://www.fitbase.de/wp-content/uploads/af_4.png" width="231" height="207" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Hintergrund:</strong> Sechs äußere Augenmuskeln pro Auge steuern eine fließende und von beiden Augen koordinierte Bewegung. Die sich gegenüber liegenden Muskelgruppen werden abwechselnd gedehnt und angespannt, so dass Flexibilität entsteht und die Muskeln mit Sauerstoff versorgt werden. Die Seheindrücke von rechtem und linkem Auge werden im Gehirn koordiniert, was gleichzeitig die Gehirnintegration trainiert und Konzentration und Erinnerungsvermögen stärkt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Hinweis:</strong></p>
<ul>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Verspannte Augenmuskeln können eine Ursache für Hornhautverkrümmung sein</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Diese Übung eignet sich vor allem zur Fixierung bei Weitsichtigkeit.</li>
</ul>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Diese Übung dient der Lockerung der Augenmuskulatur und verbessert die Gehirnintegration.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? Mit der Frage „Warum strengt Bildschirmarbeit an?“…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item533);

        $item558 = new Weeklytask();
        $item558->setFormat("richhtml");
        $item558->setTag("Augen");
        $item558->setCountPoint(1);
        $item558->setName("Anstrengung durch Bildschirmarbeit");
        $item558->setCategory($this->getReference('category_augen'));
        $item558->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur fünften Einheit Ihres Sehtrainings, die sich mit der Frage beschäftigt, <strong>warum Bildschirmarbeit besonders anstrengend ist.</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Das Sehen geschieht in wechselseitiger Beeinflussung von Auge, Körper und Psyche des Menschen. Ursprünglich ist <strong>das Sehen in der Nähe</strong> an den Entspannungszustand des vegetativen Nervensystems gekoppelt.</p>
<p style="margin: 0px;font-size: 14px;color: #333333;font-weight: normal;padding: 0px 0px 20px;line-height: 22px;text-align: center"><img class=" wp-image-4999 aligncenter" alt="kf10" src="https://www.fitbase.de/wp-content/uploads/kf10.png" width="225" height="341" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Bildschirmarbeit zwingt den Menschen oft durch <strong>statische Körperhaltung</strong> und starre Blickposition in eine unbewegte und damit nicht entspannte Haltung. Zeitdruck oder hohe nervliche Beanspruchung verursachen Anspannung. Der Körper reagiert mit Stressphänomenen, d.h. Hormonausschüttungen, Veränderung von Herzschlag und Atmung.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Die Augenlinse und die Augenmuskeln sind über lange Zeit auf einen kleinen Raum und eine gleiche Entfernung fixiert. Lidschläge erfolgen nicht mehr so häufig. Folglich werden die Sauerstoffversorgung und der Stoffwechsel des Auges reduziert. Die <strong>Augenlinse</strong>, zuständig für die Scharfeinstellung, <strong>verkrampft</strong> <strong>und verhärtet</strong>. Lesebrillen werden früher erforderlich.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Klassisches räumliches Sehen bedeutet, dass die Seheindrücke von rechtem und linkem Augen im Gehirn zu einem Bild fusioniert werden. Die Zweidimensionalität des Bildschirms erfordert nicht unbedingt räumliches Sehen und die Augen stellen sich darauf ein. Häufig übernimmt dann nur ein Auge die anstrengenden Sehaufgaben in der Nähe.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Gute Koordination der Augen und abwechslungsreiches, entspanntes Sehen sind eine Voraussetzungen für langanhaltende Konzentration und Erhalt der Arbeitsfähigkeit am Bildschirm. Stärkeren Augenproblematiken wird vorgebeugt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? Wir befassen uns mit dem „Beidäugigen Sehen“…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
&nbsp;
EOT
        );
        $manager->persist($item558);

        $item559 = new Weeklytask();
        $item559->setFormat("richhtml");
        $item559->setTag("Augen");
        $item559->setCountPoint(1);
        $item559->setName("Beidäugiges Sehen");
        $item559->setCategory($this->getReference('category_augen'));
        $item559->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur sechstenEinheit Ihres Sehtrainings, die sich mit dem beidäugigen Sehen beschäftigt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Hoffentlich haben Sie in den vergangenen Tagen bereits unseren Email-Service genutzt und tägliche Übungen für die Augen gemacht. Die folgende Übung möchten wir heute einmal vertiefen:</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Das Daumentor</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Bitte sitzen oder stehen Sie aufrecht für diese Übung.</p>

<ul>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Halten Sie Ihren Daumen in ca. 30cm Entfernung in der Körpermitte vor sich.</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Nehmen Sie nun einen Stift und halten Sie ihn mit der anderen Hand etwa 10 cm mittig dahinter in einer Flucht mit dem Daumen.</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Fixieren Sie den Stift mit den Augen, nehmen aber den Daumen, ohne ihn direkt anzublicken, auch wahr.</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Wenn Sie einen zweiten imaginären Daumen sehen, der den Stift wie ein Tor umrahmt, sehen sie mit beiden Augen gleichzeitig.</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Wechseln Sie nun mit dem Blick auf den Daumen und lassen Sie den Stift doppelt werden.</li>
</ul>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Dauer:</strong> 2x den Daumen und 2x den Stift fokussieren.</p>
<p style="margin: 0px;font-size: 14px;color: #333333;font-weight: normal;padding: 0px 0px 20px;line-height: 22px;text-align: center"><img class="size-full wp-image-6950 aligncenter" alt="daumentor" src="https://www.fitbase.de/wp-content/uploads/daumentor.png" width="290" height="186" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Hintergrund:</strong> Dass beide Augen ihre Seheindrücke gleichzeitig an das Gehirn liefern ist eine Voraussetzung für räumliches Sehen. Dieses fusionierte Sehen ist im zentralen Bereich vor uns möglich und kann durch diese Übung trainiert und überprüft werden.Beidäugiges Sehen wird trainiert.Zentrale und periphere Netzhautzellen werden stimuliert.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Hinweis: Diese Übung eignet sich vor allem bei Kursichtigkeit zur Stärkung der Peripheriewahrnehmung.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Merkbox:</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">- Beidäugiges Sehen wird trainiert.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">- Zentrale und periphere Netzhautzellen werden stimuliert.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">- Die Gehirnbereiche, die Seheindrücke fusionieren werden trainiert.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? In der kommenden Einheit befassen wir uns mit Tränen…</em></p>
EOT
        );
        $manager->persist($item559);

        $item560 = new Weeklytask();
        $item560->setFormat("richhtml");
        $item560->setTag("Augen");
        $item560->setCountPoint(1);
        $item560->setName("Der Tränenfilm");
        $item560->setCategory($this->getReference('category_augen'));
        $item560->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur siebten Einheit Ihres Sehtrainings, die sich mit dem Tränenfilm beschäftigt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Der Tränenfilm besteht aus drei verschiedenen Schichten. Die mittlere, wässrige Schicht ist die dickste und enthält Nähstoffe, antibakterielle Substanzen und Sauerstoff zur Versorgung der vorderen Augenfläche, der Hornhaut.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Die Tränenfilm produzierenden Drüsen liegen im Oberlid. Durch Lidschläge und Augenbewegungen wird der Tränenfilm ausgeschüttet und über die Hornhaut verteilt. Alle zehn Minuten wird er erneuert.</p>
<p style="margin: 0px;font-size: 14px;color: #333333;font-weight: normal;padding: 0px 0px 20px;line-height: 22px;text-align: center"><img class="size-medium wp-image-6956 aligncenter" alt="af_11" src="https://www.fitbase.de/wp-content/uploads/af_112-263x300.png" width="263" height="300" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Die Oberfläche des Tränenfilms besteht aus einer öligen Schicht, die vor zu schneller Austrocknung und Verdunstung der wässrigen Schicht schützt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Werden zu wenige Lidschläge gemacht, reißt der Tränenfilm auf und die Hornhaut läuft Gefahr, auszutrocknen. Das Sehen wird unscharf und die Versorgung mit Sauerstoff ist nicht mehr ausreichend. Die Folge sind müde, rote oder brennende Augen.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Die normale Anzahl der Lidschläge beträgt ungefähr 15 pro Minute. Bei starrem Blick z. B. am Computer oder angestrengter Naharbeit verringert sie sich häufig auf 3-4 pro Minute!</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Äußere Faktoren wie Luftfeuchtigkeit, Staub, Medikamente oder falsche Kontaktlinsen beeinflussen den Tränenfilm zusätzlich.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em id="__mceDel">Wie geht es weiter? Mit der Flexibilität der Augenlinse…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item560);

        $item595 = new Weeklytask();
        $item595->setFormat("richhtml");
        $item595->setTag("Augen");
        $item595->setCountPoint(1);
        $item595->setName("Willkommensemail");
        $item595->setCategory($this->getReference('category_augen'));
        $item595->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Herzlich willkommen zu unserem AugenCoach, dem Online-Sehtraining. Im Rahmen dieses Coaches möchten wir Ihnen Gesundheitskompetenz für gesundes Sehen vermitteln und Antworten auf die folgenden Fragen liefern:</p>

<ul>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Wie halte ich meine Augen gesund?</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Wie kann ich meine Sehkraft erhalten bzw. steigern?</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Was kann ich gegen trockene, brennende Augen tun?</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Warum können Brillen nicht alle Sehprobleme korrigieren?</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Warum ist Naharbeit besonders anstrengend?</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Welche Zusammenhänge bestehen zwischen Sehen und Stress?</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Wie kann ich meine Augen am Bildschirm entspannen?</li>
</ul>
<p style="text-align: center"><img class=" wp-image-3770 aligncenter" alt="augen" src="https://www.fitbase.de/wp-content/uploads/augen.jpg" width="360" height="240" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Mit unserem Online-Sehtraining lernen Sie praxisnahes Know-how für Ihre Augengesundheit sowie praktische Übungen zum Erhalt Ihrer Sehkraft. Die Übungen können Sie überall und ohne Hilfsmittel durchführen, Sie müssen sich lediglich 4 Minuten Zeit nehmen.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><b style="font-size: 13px">Ablauf: </b>Die erste Einheit erhalten Sie am nächsten Werktag automatisch an Ihre hinterlegte Emailadresse. Anschließend erhalten Sie jede Woche zwei Informationseinheiten per Mail sowie jeden Tag einen Reminder für Ihr tägliches Augentraining. Einstellungen dazu können Sie jederzeit vornehmen.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><b style="font-size: 13px">Ziel:</b> Nach 8 Wochen haben Sie praxisnahes Know-how zum Thema <i style="font-size: 13px">Sehen</i> aufgebaut und wissen, mit welchen Übungen Sie Ihre Augengesundheit stärken können.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><b style="font-size: 13px">Vorab:</b> Bitte notieren Sie sich auf einem Blatt Papier, welche Probleme Sie mit den Augen haben und wann, z.B. Brennende Augen nach der Arbeit am PC oder Verschwommenes Sehen auf dem Weg in den Feierabend. Bewahren Sie dieses Blatt gut auf, denn wir benötigen es am Ende des Kurses noch einmal.</p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item595);

        $item6395 = new Weeklytask();
        $item6395->setFormat("richhtml");
        $item6395->setTag("Augen");
        $item6395->setCountPoint(1);
        $item6395->setName("Sehtraining");
        $item6395->setCategory($this->getReference('category_augen'));
        $item6395->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur ersten Einheit im AugenCoach, dem Online-Sehtraining auf fitbase.de.
Wir gehen heute folgender Frage nach:</p>

<h1 style="font-weight: bold;padding: 0;margin: 0;font-size: 14px;color: #6d8295">Warum Sehtraining?</h1>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Informationen über unsere Umwelt nehmen wir zum größten Teil mit den Augen auf. Das Sehen ist aber viel mehr als scharfes Erkennen. Es beinhaltet außerdem Augenbeweglichkeit, räumliches Sehen und individuelle Wahrnehmung. Um die Seheindrücke optimal aufzunehmen sollten beide Augen perfekt aufeinander abgestimmt sein und sich gut koordiniert bewegen können. Die Voraussetzung dazu sind bewegliche Muskeln im Auge und am Augapfel, vgl. Abbildung.</p>
<p style="margin: 0px;font-size: 14px;color: #333333;font-weight: normal;padding: 0px 0px 20px;line-height: 22px;text-align: center"><img class="size-medium wp-image-6406 aligncenter" alt="af_01" src="https://www.fitbase.de/wp-content/uploads/af_01-300x193.png" width="377" height="242" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Einseitige Sehgewohnheiten- oder Bedingungen wie zum Beispiel am Computer schränken die Beweglichkeit und das Zusammenspiel beider Augen ein und können weitreichende körperliche Folgen wie Kopf- und Nackenschmerzen, Ermüdungserscheinungen oder trockene Augen zur Folge haben.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Die Verarbeitung der Seheindrücke im Gehirn geschieht auf neuronaler Ebene. Wir sehen zu 80% mit dem Gehirn und neue Sehgewohnheiten können auch im erwachsenen Alter erlernt werden. Unser Sehen besteht gleichzeitig aus scharfem und unscharfem Sehen, die im Gehirn in den verschiedenen Gehirnhälften getrennt verarbeitet werden. Dazu sind körperliche Zustände des Vegetativen Nervensystems in Anspannung und Entspannung gekoppelt. Das Sehen hat Einfluss auf Atmung, Herzschlagfrequenz und Muskeltonus. Sehtraining bietet mit einfachen Mitteln Entspannung, kraftvolles, scharfes Sehen und erweiterte Wahrnehmung. Mehr dazu in den kommenden Wochen.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Nutzen Sie die heutige Erinnerungsmail für eine erste praktische Übungseinheit.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? Die nächste Einheit heißt „Sehen mit dem ganzen Gehirn“…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item6395);

        $item6969 = new Weeklytask();
        $item6969->setFormat("richhtml");
        $item6969->setTag("Augen");
        $item6969->setCountPoint(1);
        $item6969->setName("Flexibilität für die Augenlinse");
        $item6969->setCategory($this->getReference('category_augen'));
        $item6969->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur achten Einheit Ihres Sehtrainings, die sich mit der Flexibilität der Augenlinse beschäftigt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Hoffentlich haben Sie in den vergangenen Tagen bereits unseren Email-Service genutzt und tägliche Übungen für die Augen gemacht. Die folgende Übung möchten wir heute einmal vertiefen:</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Der Fern-Nah-Schwung</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Bitte sitzen oder stehen Sie aufrecht für diese Übung.</p>

<ul>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Halten Sie einen Daumen eine Armlänge entfernt in der Körpermitte vor sich.</p>
</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Blicken Sie nun abwechselnd den Daumen und ein Objekt in der Ferne (mindestens 6 Meter entfernt) an, das kann ein Baum, der Himmel oder auch die gegenüberliegende Wand sein.</p>
</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Wechseln Sie im Sekundentakt zwischen Ferne und Nähe</p>
</li>
</ul>
<strong>Dauer: ca. 1 Minute.</strong>
<p style="text-align: center"><img class="size-medium wp-image-3770 aligncenter" alt="augen" src="https://www.fitbase.de/wp-content/uploads/augen-300x200.jpg" width="300" height="200" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Hintergrund</strong>: Ein leichtes Druckgefühl um die Augen herum signalisiert Ihnen, dass Ihre sechs Augenmuskeln und die Ziliarmuskeln aktiviert sind. Dabei wird die Augenlinse, die für das scharfe Sehen verantwortlich ist, flexibel gehalten.Der Wechsel zwischen Anspannung und Entspannung in den Augen bringt Bewegung ins Sehen und versorgt die Augenmuskeln mit Sauerstoff.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><span style="font-size: 13px"> </span></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Aufgabe: Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? Wir beleuchten typische Fehlsichtigkeiten und empfehlen Ihnen Übungen dazu…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item6969);

        $item6986 = new Weeklytask();
        $item6986->setFormat("richhtml");
        $item6986->setTag("Augen");
        $item6986->setCountPoint(1);
        $item6986->setName("Verschiedene Sichtweisen");
        $item6986->setCategory($this->getReference('category_augen'));
        $item6986->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur neunten Einheit Ihres Sehtrainings, die sich mit Fehlsichtigkeiten beschäftigt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Abweichungen im optischen System des Auges bezeichnet man als Fehlsichtigkeit. Es gibt verschiedene Ursachen, die sowohl vererbt als auch erworben sein können. Auch im Erwachsenenalter lässt sich das Sehen aber verändern und viele nicht gut gelaufene Entwicklungsschritte können wieder rückgängig gemacht werden.</p>
<p style="margin: 0px;font-size: 14px;color: #333333;font-weight: normal;padding: 0px 0px 20px;line-height: 22px;text-align: center"><img class="size-medium wp-image-6987 aligncenter" alt="myopia" src="https://www.fitbase.de/wp-content/uploads/myopia-300x195.png" width="300" height="195" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Kurzsichtigkeit - Myopie</strong> bedeutet in der Regel, dass der Augapfel zu lang gewachsen ist, d.h. die Abbildung auf der Netzhaut ist unscharf. Nahe Dinge können klar erkannt werden, weit entfernte Gegenstände sind unscharf. Eine Brillenkorrektion lenkt das Licht fokussiert in die Netzhautgrube, wo scharfes Sehen möglich ist. Die Weiterleitung dieser Impulse ins Gehirn erfolgt zum überwiegenden Teil in die "Logik-Gehirnhälfte“. Kurzsichtige sollten Stress vermeiden und das periphere, unscharfe Sehen zulassen.Menschen mit Kurzsichtigkeit können folgende Übungen empfohlen werden:</p>

<ul>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Akupressur der Augenbrauenmitte</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Palmieren</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Daumentor</li>
</ul>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Weitsichtigkeit - Hyperopie </strong>heißt, der Punkt des scharfen Sehens liegt hinter der Netzhaut und muss durch Akkommodation (Einstellung der Augenlinse) in eine scharfe Abbildung gebracht werden. Das bedeutet Anstrengung und beeinflusst gleichzeitig die Stellung der Augen zueinander. In der Nähe ist diese Aufgabe oft besonders anstrengend. Weitsichtige sollten "auf den Punkt kommen", das heißt für die Augen direkt zu fixieren. Fokussiertes Handeln und sich selbst und den Menschen nahe bleiben ist die Aufgabe.Menschen mit Weitsichtigkeit können folgende Übungen empfohlen werden:</p>

<ul>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Fern-Nah-Schwung</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Umfahren von Umrissen mit den Augen</li>
</ul>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Hornhautverkrümmung - Astigmatismus</strong> lässt zwei Brennlinien im Auge entstehen, die keine punktförmige Abbildung, sondern unscharfes, verzerrtes Sehen entstehen lassen. Korrigierende Brillengläser beinhalten zwei unterschiedliche Stärken. Es entstehen Schwierigkeiten, sich zu entscheiden oder das eine mit dem anderen zu verbinden. Übungen, die Gehirnintegration trainieren, z. B. das Kreuzen der Körpermittellinie mit Augen und Gliedern, sind förderlich. Die Aufgabe besteht darin, Denken und Fühlen zu verbinden.Menschen mit einer Hornhautverkrümmung können folgende Übungen empfohlen werden:</p>

<ul>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Die Fingerspitzen beider Hände aneinander legen</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Die liegende Acht</li>
</ul>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Alterssichtigkeit - Presbyopie </strong>ist eine besondere Form der Weitsichtigkeit mit zunehmendem Alter.Scharfes Sehen in der Nähe fällt schwer. Ursache ist die Unflexibilität der Augenlinse, die sich nicht mehr so wölben kann, dass eine scharfe Abbildung möglich ist. Durch einseitige Sehbedingungen in Nahbereichen verkrampft die Augenlinse oft vorzeitig und Lesebrillen sind früher erforderlich. Die Augenbeweglichkeit der äußeren und inneren Augenmuskeln muss gefördert werden. Hier helfen Blickwechsel von Ferne zu Nähe und in alle Richtungen im Raum.Menschen mit Alterssichtigkeit können folgende Übungen empfohlen werden:</p>

<ul>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Fern- Nah-Schwung mit schnellen Blickwechseln zwischen Ferne und Nähe</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Augenbeweglichkeitsübung</li>
</ul>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? Wir beschäftigen uns mit der Frage „Ist es wahr, was ich sehe?“ und vertiefen eine Übung, die Sie hoffentlich schon gemacht haben…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item6986);

        $item6990 = new Weeklytask();
        $item6990->setFormat("richhtml");
        $item6990->setTag("Augen");
        $item6990->setCountPoint(1);
        $item6990->setName("Wahrnehmung");
        $item6990->setCategory($this->getReference('category_augen'));
        $item6990->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur zehnten Einheit Ihres Sehtrainings, die sich heute mit der Wahrnehmung beschäftigt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Wahrnehmung - ist es wahr, was ich sehe?</strong>
Während sich unser Sehen entwickelt, beeinflussen uns unzählige Eindrücke, die bewusst oder unbewusst gespeichert werden. Bevor die Seheindrücke das Gehirn auf neuronaler Ebene durchlaufen haben, werden sie aufgrund dieser persönlichen Erfahrungen und Empfindungen bewertet. Dies geschieht über das Limbische System, das jedem Seheindruck Assoziationen zuordnet. Dabei werden auch Sprache und Hören integriert.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Über das limbische System werden sowohl Seheindrücke selektiert als auch individuell bewertet, was ein einzigartiges, von der Persönlichkeit abhängiges Wahrnehmen erschafft. Visualisation schafft die Möglichkeit, sich ein geistiges Bild von der Welt zu machen und die individuelle Sichtweise zu erschaffen.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Die Wahrnehmung ist die am höchsten entwickelte Stufe des Sehens und dem vierten Bereich der Kreise von Skeffington zuzuordnen.
Bitte sitzen oder stehen Sie aufrecht für diese Übung und schauen Sie die beiden farbigen Kreise an.</p>

<ul>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Trainieren Sie ihre Wahrnehmung, indem Sie die beiden Punkte so ansehen, dass dreiPunkte daraus entstehen.</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Schauen Sie dafür durch das Bild hindurch oder "schielen" Sie darauf.</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Sie können auch den Zeigefinger vor das Bild halten, ihn fixieren und die Kreise im Hintergrund unscharf werden lassen.</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Sind drei Kreise entstanden, schauen Sie sich die Farbe des mittleren Kreises an. Sie kann Rot, Blau oder auch Lila sein.</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Denken Sie sich nun den mittleren Kreis Rot und beobachten Sie, was ihre Augen Ihnen zeigen. Ebenso können Sie den Kreis Blau denken.</li>
</ul>
<p style="margin: 0px;font-size: 14px;color: #333333;font-weight: normal;padding: 0px 0px 20px;line-height: 22px;text-align: center"><img class="aligncenter  wp-image-6991" alt="af_6" src="https://www.fitbase.de/wp-content/uploads/af_61.png" width="387" height="164" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? Mit den allgemeinen Körperzuständen Sympathikus und Parasympathikus…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item6990);

        $item6995 = new Weeklytask();
        $item6995->setFormat("richhtml");
        $item6995->setTag("Augen");
        $item6995->setCountPoint(1);
        $item6995->setName("Sehen im vegetativen Nervensystem");
        $item6995->setCategory($this->getReference('category_augen'));
        $item6995->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur zwölften Einheit Ihres Sehtrainings, die sich erneut mit dem Sehen im vegetativen Nervensystem beschäftigt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Die meisten inneren Vorgänge des Körpers werden vom vegetativen, nicht willentlich beeinflussbaren, Nervensystem gesteuert. Ursprünglich gepolt als Kampf- und Fluchtmuster reagiert der Körper blitzschnell auf wahrgenommene Bedrohungen durch Ausschüttung von Hormonen und bestimmten Körperreaktionen.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Man unterscheidet zwischen <strong>Sympathikus</strong>, dem Anspannungszustand und <strong>Parasympathikus</strong>, dem Entspannungszustand, die als Gegenspieler fungieren. Auch das Sehen in Ferne und Nähe ist abhängig von den Zuständen des Nervensystems (vgl. kommendeEinheit).</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Erfolgt das Sehen in der Nähe nicht in entspanntem Zustand,</strong> sind vielfältige körperliche Stresssymptome zu beobachten. Folgende Tabelle zeigt eine Auswahl der Zusammenhänge:</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><img class="aligncenter size-full wp-image-6996" alt="nervensystem" src="https://www.fitbase.de/wp-content/uploads/nervensystem.png" width="410" height="287" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? Wir vertiefen die Thematik und stellen einen Zusammenhang zwischen Stress und Sehen her…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item6995);

        $item7001 = new Weeklytask();
        $item7001->setFormat("richhtml");
        $item7001->setTag("Augen");
        $item7001->setCountPoint(1);
        $item7001->setName("Sehen und Stress");
        $item7001->setCategory($this->getReference('category_augen'));
        $item7001->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur elften Einheit Ihres Sehtrainings, die sich erneut mit dem Zusammenhang von Sehen und Stress beschäftigt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Auswirkung von Stress auf die Sehkraft</strong>
Das vegetative Nervensystem besteht aus zwei Teilen mit gegensätzlichen Funktionen:</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">1. sympathisches Nervensystem für Aktivität und Leistung
2. parasympathisches Nervensystem für Erholung, Entspannung und Energieaufbau.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Bei Aufregung und Stress bewirkt das sympathische Nervensystem - neben vielen weiteren Auswirkungen wie Adrenalinausschüttung, Muskelanspannung, Steigerung des Herzschlages etc. - eine Erweiterung der Pupillen. Dadurch wird mehr Licht durchgelassen, die Augen sind lichtempfindlicher und das Sehfeld wird größer.</p>
<p style="margin: 0px;font-size: 14px;color: #333333;font-weight: normal;padding: 0px 0px 20px;line-height: 22px;text-align: center"><img class="wp-image-5006 aligncenter" alt="kf11" src="https://www.fitbase.de/wp-content/uploads/kf11.png" width="479" height="300" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Außerdem kommt es zu einer Abflachung der Augenlinsen, die eine verbesserte Fernsicht ermöglicht. Vor allem Objekte ab 6 Meter Entfernung werden dann besonders gut wahrgenommen – also in der Entfernung, in der während der menschlichen Entwicklung akute Gefahr z.B. in Form eines Angreifers erschienen ist.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">In einer Entspannungsphase bewirkt das parasympathische Nervensystem eine Krümmung der Augenlinsen, was eine verbesserte Nahsicht ermöglicht.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Das Problem ist, dass wir heutzutage visuellen Stress fast ausschließlich in der Nähe erleben, nämlich auf dem Bildschirm oder im Gesprächspartner gegenüber und kaum in einer Entfernung ab 6 Metern, so wie es unser vegetatives Nervensystem nach Jahrtausenden der Entwicklung vorsieht.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Um es noch deutlicher zu machen: In einer akuten Stresssituation können wir schlecht Lesen, was auf dem Bildschirm steht, da der Körper die Augen so einstellt, dass sie Dinge in der Entfernung scharf sehen. Wir schauen aber meist nicht in die Ferne sondern auf den Bildschirm.
Folglich müssen wir in Stresssituationen die Augen mit Entspannungsübungen entlasten und den Stresspegel senken, um konzentriert am Bildschirm weiter arbeiten zu können.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Augenbewegung</strong>
Eine praktische Übung, die zur Anspannung und Entspannung der Augenmuskulatur führt erreichen Sie über folgenden Link:</p>
<p style="text-align: center"><a href="https://www.fitbase.de/mitgliederbereich/module/augenfit/videos/augenbewegung/?%%login_string%%"><img class="aligncenter" title="Zur Übungseinheit" alt="Zur Übungseinheit" src="https://www.fitbase.de/wp-content/uploads/button_sn.png" width="189" height="39" /></a></p>
&nbsp;
<em style="font-size: 14px">(Zudem wird auch hier die Körpermitte überschritten, was zu einem besseren Zusammenspiel der beiden Gehirnhälften führt.)</em>
&nbsp;
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong></strong><em>Wie geht es weiter? Wir vertiefen die Entspannungsübung La Palma…</em></p>
&nbsp;
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em> </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em> </em></p>
EOT
        );
        $manager->persist($item7001);

        $item7004 = new Weeklytask();
        $item7004->setFormat("richhtml");
        $item7004->setTag("Augen");
        $item7004->setCountPoint(1);
        $item7004->setName("La Palma");
        $item7004->setCategory($this->getReference('category_augen'));
        $item7004->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur 13. Einheit Ihres Sehtrainings, die sich mit einer Entspannungsübung beschäftigt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>La Palma für eine kurze Reise…</strong>
Eine wirksame Entspannungsübung für die Augen trägt den Namen "<strong>Palmieren</strong>". Palma ist der lateinische Begriff für die Handfläche.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Setzen Sie sich bequem und stützen Sie die Ellenbogen auf einem Tisch oder den Knien auf. Bedecken Sie nun die geschlossenen Augen mit den gewölbten Handflächen, so dass kein Druck auf den Augapfel ausgeübt wird. Dabei werden die Fingerspitzen leicht überkreuzt gehalten.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Entspannen Sie bewusst die Augenmuskeln, den Augapfel und die Augenlinse und lassen Sie Dunkelheit einkehren. So können alle Sehzellen der Netzhaut neue Reserven von Sehpurpur auftanken und regenerieren. Die Atmung ist ruhig und tief und Sie genießen den Schutz und die Wärme der Hände. Auch der Verstand darf ruhen, lassen Sie alle Gedanken wie Wolken am Himmel vorüberziehen und entspannen Sie. Die Vorstellung eines Wasserfalls oder saurer Speisen hilft bei Bedarf, Tränen zu produzieren.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Über den folgenden Link erreichen Sie ein Video zu dieser Übung:</p>
<p style="margin: 0px;font-size: 14px;color: #333333;font-weight: normal;padding: 0px 0px 20px;line-height: 22px;text-align: center"><a href="https://www.fitbase.de/mitgliederbereich/module/augenfit/videos/palmieren/?%%login_string%%"><img class="aligncenter" title="Zur Übungseinheit" alt="Zur Übungseinheit" src="https://www.fitbase.de/wp-content/uploads/button_sn.png" width="189" height="39" /></a></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Nach einigen Minuten nehmen Sie bei noch geschlossenen Augen zuerst die Hände weg. Meist zeigt sich ein Rot - oder Orangeton vor den Augen. Dann blinzeln Sie mehrmals, öffnen die Augen und schauen in die Ferne. Strecken und dehnen Sie sich und gähnen Sie herzhaft, damit sich auch die Kiefermuskulatur entspannen kann. Frische Sehkraft und Konzentration stellen sich ein.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? Dass kommende Thema sind trockene Augen am PC…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item7004);

        $item7008 = new Weeklytask();
        $item7008->setFormat("richhtml");
        $item7008->setTag("Augen");
        $item7008->setCountPoint(1);
        $item7008->setName("Trockene Augen");
        $item7008->setCategory($this->getReference('category_augen'));
        $item7008->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur 14. Einheit Ihres Sehtrainings, die sich mit trockenen Augen beschäftigt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Trockene Augen - Kein Thema zum Weinen!</strong></p>
<ul>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Genug Wasser trinken</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Frische Raumluft mit mind. 45% Luftfeuchtigkeit</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Zugluft vermeiden und verrauchte Räume meiden</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Staubfreier Arbeitsplatz und Bildschirm</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Mit der Zunge das Zahnfleisch über den Schneidezähnen im Oberkiefer pressen</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Gut angepasste Kontaktlinsen oder Brille tragen</li>
</ul>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bewegte Augen sehen besser</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Lenken Sie spätestens alle 20 Minuten den Blick in die Ferne und machen langsam 10 ruhige Atemzüge. Mit den Augen einen weit weg gelegenen Gegenstand umfahren, z. B. die Umrisse eines Baumes oder Gebäudes.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Zwinkern dass der Arzt nicht kommt…</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Das kurze Schließen der Augen mit einem kompletten Lidschlag unterbricht das konzentrierte Starren und gönnt den Augen eine entspannte Minipause ohne Seheindrücke. Neuer Tränenfilm wird ausgeschüttet, benetzt und versorgt das Auge mit Sauerstoff. Der Lidschlag sollte leicht und locker und mindestens 15 mal pro Minute erfolgen.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>La Palma für eine kurze Reise…</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Der lateinische Begriff für die Handfläche meint eine Übung mit dem Namen Palmieren. Dazu werden die geschlossenen Augen mit den gewölbten Handflächen bedeckt. Die Augenmuskeln, der Augapfel und die Augenlinse entspannen und alle Sehzellen können neue Reserven von Sehpurpur auftanken. Die Vorstellung eines Wasserfalls oder saurer Speisen hilft, Tränen zu produzieren.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Gähnen erwünscht…</strong>
Gähnen, Recken und Strecken stimuliert Blutkreislauf und Atmung und führt dem Körper mehr Sauerstoff zu. Die Tränendrüsen in den Augenlidern werden aktiviert. Der Geist wird wacher und das Sehvermögen verbessert sich.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte palmieren Sie diese Woche jeden Tag 2 Mal.</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Ein Video zu dieser Übung finden Sie hier:</p>
<p style="text-align: center"><a href="https://www.fitbase.de/mitgliederbereich/module/augenfit/videos/palmieren/?%%login_string%%"><img class="aligncenter" title="Zur Übungseinheit" alt="Zur Übungseinheit" src="https://www.fitbase.de/wp-content/uploads/button_sn.png" width="189" height="39" /></a></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? Mit bewegtem Sehen…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item7008);

        $item7011 = new Weeklytask();
        $item7011->setFormat("richhtml");
        $item7011->setTag("Augen");
        $item7011->setCountPoint(1);
        $item7011->setName("Bewegtes Sehen");
        $item7011->setCategory($this->getReference('category_augen'));
        $item7011->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur 15. Einheit Ihres Sehtrainings, die sich mit Bewegtem Sehen beschäftigt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Auch wenn wir den Blick auf etwas ruhen lassen, sind die Augen aktiv. Winzig kleine Blickbewegungen, sogenannte Saccaden lassen die Augen hin und her springen. Diese unbewussten Blickbewegungen gehören zum natürlichen Sehen und verhindern, dass immer die gleichen Sehzellen in der Netzhaut beansprucht werden.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Dadurch werden einseitige Belastungen der Netzhautzellen vermieden und das Sehen bleibt lebendig.</p>
<p style="margin: 0px;font-size: 14px;color: #333333;font-weight: normal;padding: 0px 0px 20px;line-height: 22px;text-align: center"><img class="size-full wp-image-7012 aligncenter" alt="bewegtes sehen" src="https://www.fitbase.de/wp-content/uploads/bewegtes-sehen.png" width="247" height="248" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Aufgabe: Überprüfen Sie die Ihr natürliches Sehen mit obigem Bild. Mit entspanntem Blick bewegen sich die Blätter. Starren Sie jedoch darauf, kommt die Bewegung zum Stillstand.</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Bei langer Bildschirmarbeit sind oft nicht nur die großen äußeren Augenmuskeln unbewegt, sondern auch die kleinen Saccadentätigkeiten reduziert.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Als Folge davon kann das Sehen unklar werden und die Augenmuskulatur verspannt, so dass eventuell sogar Fehlsichtigkeiten daraus resultieren können. Die Verarbeitung der Seheindrücke im Gehirn wird beim Starren extrem beansprucht.Ungünstige Einflüsse von extrem fokussierten Sehen wirken auch auf Herzschlag und Atmung.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Entspanntes Arbeiten in der Nähe bedeutet bewegtes Sehen. Blickbewegungen, Lidschläge, Wechsel zwischen Ferne und Nähe und eine ergonomische Ausstattung des Arbeitsplatzes, die entspannte Körperhaltungen möglich machen, verhindern Sehstress.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? Wir zeigen Ihnen, wie die Augenlinse scharf stellt…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"></p>
EOT
        );
        $manager->persist($item7011);

        $item7015 = new Weeklytask();
        $item7015->setFormat("richhtml");
        $item7015->setTag("Augen");
        $item7015->setCountPoint(1);
        $item7015->setName("Akkommodation");
        $item7015->setCategory($this->getReference('category_augen'));
        $item7015->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur 16. Einheit Ihres Sehtrainings, die sich mit dem Scharfstellen der Augenlinse beschäftigt. Um in den verschiedenen Entfernungen scharf sehen zu können, verändert sich die Augenlinse in ihrer Krümmung. Dazu arbeitet die innere Augenmuskulatur, Ziliarmuskel genannt, der mit Bändern an der Augenlinse befestigt ist.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Durch Zug an den Bändern wird die Augenlinse für die Ferne ganz flach gezogen. Der Ziliarmuskel ist dabei entspannt.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Beim Blick in die Nähe werden die Bänder lose und die Augenlinse kann in ihre stark gewölbte und entspannte Form kommen. Jetzt ist der Ziliarmuskel angespannt.</p>
<p style="margin: 0px;font-size: 14px;color: #333333;font-weight: normal;padding: 0px 0px 20px;line-height: 22px;text-align: center"><img class="size-full wp-image-7016 aligncenter" alt="akkomodation" src="https://www.fitbase.de/wp-content/uploads/akkomodation.png" width="508" height="285" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Gleichzeitig mit der Scharfeinstellung der Augenlinse reagiert die Pupille. Sie wird beim Blick in die Nähe für höhere Tiefenschärfe kleiner. Die Augen werden von den äußeren Augenmuskeln nach innen ausgerichtet , was mit Konvergenz bezeichnet wird.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Diese Kopplung geschieht unbewusst über das vegetative Nervensystem.Im Gehirn sind in der Verarbeitung der Seheindrücke weitreichende kognitive Prozesse wie Aufmerksamkeit, Erinnerung und Bewusstsein verbunden.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Akkommodation im wörtlichen Sinn bedeutet Anpassung. Bekannte innere Bilder werden mit der neuen Wahrnehmung abgeglichen.
Wir sehen nur das, was wir kennen im Sinne von Erkennen.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><em>Wie geht es weiter? Wir fassen das Gelernte einmal zusammen und nähern uns dem Ende…</em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item7015);

        $item7018 = new Weeklytask();
        $item7018->setFormat("richhtml");
        $item7018->setTag("Augen");
        $item7018->setCountPoint(1);
        $item7018->setName("Abschluss");
        $item7018->setCategory($this->getReference('category_augen'));
        $item7018->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">herzlich Willkommen zur 17. und letzten Einheit Ihres Sehtrainings, die die wichtigsten Inhalte noch einmal zusammenfasst.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Vielleicht ist es das Vorhandensein der verschiedenen Gegensätze und der Bewegung im Sehen, das so viele unterschiedliche Wahrnehmungsmöglichkeiten bietet.</p>
<ul>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Scharfes und unscharfes Sehen sind gleichzeitig vorhanden und werden verschieden verarbeitet in der Ratio- und Emotionsgehirnhälfte</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Sehen in Ferne und Nähe wechselt im Körper die Zustände des vegetativen Nervensystems von Anspannung und Entspannung</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Persönliche Erfahrung in jedem Augen-Blick, die Zuordnung der Assoziationen des Limbischen Systems schaffen ein individuelles Sehen</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Bewegung trainiert Muskeln und Augenlinse und hält die Versorgung des Auges mit Tränen und Sauerstoff aufrecht</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Fehlsichtigkeitensind trainierbar durch Muskel- und mentale Kraft</li>
	<li style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0">Sehen ist viel mehr als scharfes Erkennen - die Augen als Spiegel der Seele</li>
</ul>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte vergessen Sie den heutigen Reminder nicht und investieren Sie 4 Minuten in Ihre Augengesundheit. Vielen Dank!</strong></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item7018);

        $item7021 = new Weeklytask();
        $item7021->setFormat("richhtml");
        $item7021->setTag("Augen");
        $item7021->setCountPoint(1);
        $item7021->setName("Das Ende");
        $item7021->setCategory($this->getReference('category_augen'));
        $item7021->setContent(<<<EOT
[back_to_parent text="Zurück zur Übersicht“]<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">vielen Dank für Ihre Teilnahme an unserem Online-Training. Wir hoffen, Ihnen viele interessante theoretische und praktische Inhalte vermittelt zu haben, so dass Sie mit klarem Blick in die Zukunft schauen können.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Bitte nehmen Sie das Blatt Papier zur Hand, wo Sie zu Beginn notiert haben, welche Probleme Sie – gelegentlich oder häufig - mit den Augen haben. Können Sie Verbesserungen feststellen? Gibt es Bereiche, die Sie mit unseren gezeigten Übungen positiv beeinflussen können?
Unser Online-Kurs endet hiermit. Vielen Dank für Ihre Teilnahme!</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><strong>Bitte führen Sie auch weiterhin täglich 1-2 Augen-Übungen durch. Ihre Augen und Ihre Sehkraft werden es Ihnen danken!</strong></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Sie haben jetzt noch eine Woche Zugriff auf die Inhalte des AugenCoaches. Wir hoffen, dass Ihnen der Coach sowohl geholfen als auch Spaß gemacht hat und wünschen Ihnen beste Gesundheit.</p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px"><img class="aligncenter size-medium wp-image-4587" alt="Wiegels" src="https://www.fitbase.de/wp-content/uploads/Wiegels-225x300.png" width="225" height="300" /></p>
<p style="margin: 0;font-size: 14px;color: #333333;font-weight: normal;padding: 0;line-height: 22px;padding-bottom: 20px">Ihre Alexandra Wiegels &amp; Ihr Fitbase Team</p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Sie erhalten diese E-Mail als Teilnehmer von Fitbase. Der Inhalt dieser E-Mail ist urheberrechtlich geschützt und nur für Ihren persönlichen Gebrauch bestimmt. </em></p>
<p style="text-align: center;margin: 0;font-size: 12px;color: #333333;font-weight: normal;padding: 0;line-height: 12px"><em>Copyright © 2013 Fitbase.de Alle Rechte vorbehalten.</em></p>
EOT
        );
        $manager->persist($item7021);


        $manager->flush();
    }

}
