<?php

namespace Fitbase\Bundle\WeeklytaskBundle\DataFixture\ORM;
;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Fitbase\Bundle\WeeklytaskBundle\Entity\WeeklyquizQuestion;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadWeeklyquizQuestionData extends AbstractFixture implements OrderedFixtureInterface
{
    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 2;
    }

    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetaData(get_class(new WeeklyquizQuestion()))->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item20 = new WeeklyquizQuestion();
        $item20->setQuiz($this->getReference('weeklyquiz_1'));
        $item20->setName("Frage 1");
        $item20->setType("checkbox");
        $item20->setDescription("Welche der beiden Aussagen ist korrekt?");
        $item20->setCountPoint(1);
        $manager->persist($item20);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_20', $item20);

        $item21 = new WeeklyquizQuestion();
        $item21->setQuiz($this->getReference('weeklyquiz_1'));
        $item21->setName("Frage 2");
        $item21->setType("checkbox");
        $item21->setDescription("Welche der folgenden Aussagen ist korrekt?");
        $item21->setCountPoint(1);
        $manager->persist($item21);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_21', $item21);


        $item23 = new WeeklyquizQuestion();
        $item23->setQuiz($this->getReference('weeklyquiz_1'));
        $item23->setName("Frage 3");
        $item23->setType("checkbox");
        $item23->setDescription("Welchen Abstand sollte man bei einer Bildschirmgröße von 21 Zoll (54 cm) mindestens Einhalten?");
        $item23->setCountPoint(1);
        $manager->persist($item23);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_23', $item23);

        $item24 = new WeeklyquizQuestion();
        $item24->setQuiz($this->getReference('weeklyquiz_2'));
        $item24->setName("Frage 1");
        $item24->setType("checkbox");
        $item24->setDescription("Aus welchem Teil des Körpers sollte die Bewegung der Maus erfolgen?");
        $item24->setCountPoint(1);
        $manager->persist($item24);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_24', $item24);

        $item25 = new WeeklyquizQuestion();
        $item25->setQuiz($this->getReference('weeklyquiz_2'));
        $item25->setName("Frage 2");
        $item25->setType("checkbox");
        $item25->setDescription("Was erleichtert die korrekte Mausbewegung?");
        $item25->setCountPoint(2);
        $manager->persist($item25);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_25', $item25);

        $item26 = new WeeklyquizQuestion();
        $item26->setQuiz($this->getReference('weeklyquiz_2'));
        $item26->setName("Frage 3");
        $item26->setType("checkbox");
        $item26->setDescription("Wodurch wird das Karpaltunnel-Syndrom meist hervorgerufen?");
        $item26->setCountPoint(1);
        $manager->persist($item26);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_26', $item26);

        $item27 = new WeeklyquizQuestion();
        $item27->setQuiz($this->getReference('weeklyquiz_8'));
        $item27->setName("Frage 1");
        $item27->setType("checkbox");
        $item27->setDescription("Warum kann es bei einer 'schlafen' Körperhaltung über längerem Zeitraum zu Haltungsschäden und Beschwerden kommen?");
        $item27->setCountPoint(1);
        $manager->persist($item27);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_27', $item27);

        $item28 = new WeeklyquizQuestion();
        $item28->setQuiz($this->getReference('weeklyquiz_8'));
        $item28->setName("Frage 2");
        $item28->setType("checkbox");
        $item28->setDescription("Was sind Bestandteile einer aufrechten Körperhaltung im Stehen? (Mehrfachantwort möglich)");
        $item28->setCountPoint(2);
        $manager->persist($item28);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_28', $item28);

        $item29 = new WeeklyquizQuestion();
        $item29->setQuiz($this->getReference('weeklyquiz_8'));
        $item29->setName("Frage 3");
        $item29->setType("checkbox");
        $item29->setDescription("Welche der folgenden Aussagen sind korrekt?");
        $item29->setCountPoint(1);
        $manager->persist($item29);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_29', $item29);

        $item30 = new WeeklyquizQuestion();
        $item30->setQuiz($this->getReference('weeklyquiz_5'));
        $item30->setName("Frage 1");
        $item30->setType("checkbox");
        $item30->setDescription("Was versteht man unter der \"Steh-Sitz-Dynamik\"?");
        $item30->setCountPoint(1);
        $manager->persist($item30);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_30', $item30);

        $item31 = new WeeklyquizQuestion();
        $item31->setQuiz($this->getReference('weeklyquiz_5'));
        $item31->setName("Frage 2");
        $item31->setType("checkbox");
        $item31->setDescription("Welche Aussagen sind über die Einrichtung eines  ergonomischen Arbeitsplatzes FALSCH?");
        $item31->setCountPoint(1);
        $manager->persist($item31);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_31', $item31);

        $item32 = new WeeklyquizQuestion();
        $item32->setQuiz($this->getReference('weeklyquiz_5'));
        $item32->setName("Frage 3");
        $item32->setType("checkbox");
        $item32->setDescription("Bei welchen Merkmalen ist die Tischhöhe ergonomisch sinnvoll eingerichtet?");
        $item32->setCountPoint(1);
        $manager->persist($item32);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_32', $item32);

        $item33 = new WeeklyquizQuestion();
        $item33->setQuiz($this->getReference('weeklyquiz_3'));
        $item33->setName("Frage 1");
        $item33->setType("checkbox");
        $item33->setDescription("Wo sollte die Tastatur am besten platziert werden, bzw. wo sollte sie sich optimaler Weise befinden?");
        $item33->setCountPoint(1);
        $manager->persist($item33);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_33', $item33);

        $item34 = new WeeklyquizQuestion();
        $item34->setQuiz($this->getReference('weeklyquiz_3'));
        $item34->setName("Frage 2");
        $item34->setType("checkbox");
        $item34->setDescription("Welche der folgenden Aussagen ist korrekt?");
        $item34->setCountPoint(1);
        $manager->persist($item34);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_34', $item34);

        $item35 = new WeeklyquizQuestion();
        $item35->setQuiz($this->getReference('weeklyquiz_3'));
        $item35->setName("Frage 3");
        $item35->setType("checkbox");
        $item35->setDescription("Was kann passieren, wenn man mit abgenicktem Handgelenk die Tastatur bedient?");
        $item35->setCountPoint(1);
        $manager->persist($item35);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_35', $item35);

        $item36 = new WeeklyquizQuestion();
        $item36->setQuiz($this->getReference('weeklyquiz_4'));
        $item36->setName("Frage 1");
        $item36->setType("checkbox");
        $item36->setDescription("Was versteht man unter dem Begriff des „Dynamischen Sitzens“?");
        $item36->setCountPoint(1);
        $manager->persist($item36);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_36', $item36);

        $item37 = new WeeklyquizQuestion();
        $item37->setQuiz($this->getReference('weeklyquiz_4'));
        $item37->setName("Frage 2");
        $item37->setType("checkbox");
        $item37->setDescription("Wie viel Grad sollte man bei einem „Offenen Sitzwinkel“ einnehmen?");
        $item37->setCountPoint(1);
        $manager->persist($item37);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_37', $item37);

        $item38 = new WeeklyquizQuestion();
        $item38->setQuiz($this->getReference('weeklyquiz_4'));
        $item38->setName("Frage 3");
        $item38->setType("checkbox");
        $item38->setDescription("Wie sollten die Füße bei einer ergonomischen Sitzhaltung aufgestellt werden?");
        $item38->setCountPoint(1);
        $manager->persist($item38);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_38', $item38);

        $item39 = new WeeklyquizQuestion();
        $item39->setQuiz($this->getReference('weeklyquiz_6'));
        $item39->setName("Frage 1");
        $item39->setType("checkbox");
        $item39->setDescription("Beenden Sie folgenden Satz: Die Kopfstütze hat dann die richtige Höhe, wenn...");
        $item39->setCountPoint(1);
        $manager->persist($item39);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_39', $item39);

        $item40 = new WeeklyquizQuestion();
        $item40->setQuiz($this->getReference('weeklyquiz_6'));
        $item40->setName("Frage 2");
        $item40->setType("checkbox");
        $item40->setDescription("Wie sollte die Rückenlehne des Autositzes am besten eingestellt sein?");
        $item40->setCountPoint(1);
        $manager->persist($item40);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_40', $item40);

        $item41 = new WeeklyquizQuestion();
        $item41->setQuiz($this->getReference('weeklyquiz_6'));
        $item41->setName("Frage 3");
        $item41->setType("checkbox");
        $item41->setDescription("Nachdem der Autositz ergonomisch richtig eingestellt wurde: Welche Aussagen sind korrekt?");
        $item41->setCountPoint(1);
        $manager->persist($item41);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_41', $item41);

        $item42 = new WeeklyquizQuestion();
        $item42->setQuiz($this->getReference('weeklyquiz_7'));
        $item42->setName("Frage 1");
        $item42->setType("checkbox");
        $item42->setDescription("Was ist Voraussetzung für eine aufrechte Sitzhaltung?");
        $item42->setCountPoint(1);
        $manager->persist($item42);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_42', $item42);

        $item43 = new WeeklyquizQuestion();
        $item43->setQuiz($this->getReference('weeklyquiz_7'));
        $item43->setName("Frage 2");
        $item43->setType("checkbox");
        $item43->setDescription("In welcher Reihenfolge erfolgt das Aufrichten für eine aufrechte Sitzhaltung?");
        $item43->setCountPoint(1);
        $manager->persist($item43);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_43', $item43);

        $item44 = new WeeklyquizQuestion();
        $item44->setQuiz($this->getReference('weeklyquiz_7'));
        $item44->setName("Frage 3");
        $item44->setType("checkbox");
        $item44->setDescription("Was sind KEINE Merkmale des aufrechten Sitzens?");
        $item44->setCountPoint(1);
        $manager->persist($item44);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_44', $item44);

        $item45 = new WeeklyquizQuestion();
        $item45->setQuiz($this->getReference('weeklyquiz_9'));
        $item45->setName("Frage 1");
        $item45->setType("checkbox");
        $item45->setDescription("Was erleichtert das Atmen?");
        $item45->setCountPoint(1);
        $manager->persist($item45);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_45', $item45);

        $item46 = new WeeklyquizQuestion();
        $item46->setQuiz($this->getReference('weeklyquiz_9'));
        $item46->setName("Frage 2");
        $item46->setType("checkbox");
        $item46->setDescription("Welcher Muskel für das Atmen am wichtigsten?");
        $item46->setCountPoint(1);
        $manager->persist($item46);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_46', $item46);

        $item47 = new WeeklyquizQuestion();
        $item47->setQuiz($this->getReference('weeklyquiz_9'));
        $item47->setName("Frage 3");
        $item47->setType("checkbox");
        $item47->setDescription("Welche Atemtechnik ist die Beste?");
        $item47->setCountPoint(1);
        $manager->persist($item47);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_47', $item47);

        $item48 = new WeeklyquizQuestion();
        $item48->setQuiz($this->getReference('weeklyquiz_10'));
        $item48->setName("Frage 1");
        $item48->setType("checkbox");
        $item48->setDescription("Das Atmen bewegt die Wirbelsäule. Welche der folgenden Aussagen über das Einatmen sind korrekt?");
        $item48->setCountPoint(1);
        $manager->persist($item48);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_48', $item48);

        $item49 = new WeeklyquizQuestion();
        $item49->setQuiz($this->getReference('weeklyquiz_10'));
        $item49->setName("Frage 2");
        $item49->setType("checkbox");
        $item49->setDescription("as Atmen bewegt die Wirbelsäule. Welche der folgenden Aussagen über das Ausatmen sind korrekt?");
        $item49->setCountPoint(1);
        $manager->persist($item49);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_49', $item49);

        $item50 = new WeeklyquizQuestion();
        $item50->setQuiz($this->getReference('weeklyquiz_10'));
        $item50->setName("Frage 3");
        $item50->setType("checkbox");
        $item50->setDescription("Beenden Sie den folgenden Satz korrekt: Das Atmen...");
        $item50->setCountPoint(1);
        $manager->persist($item50);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_50', $item50);

        $item51 = new WeeklyquizQuestion();
        $item51->setQuiz($this->getReference('weeklyquiz_11'));
        $item51->setName("Frage 1");
        $item51->setType("checkbox");
        $item51->setDescription("Was sind Gründe für ein Verlust der Vollatmung?");
        $item51->setCountPoint(1);
        $manager->persist($item51);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_51', $item51);

        $item52 = new WeeklyquizQuestion();
        $item52->setQuiz($this->getReference('weeklyquiz_11'));
        $item52->setName("Frage 2");
        $item52->setType("checkbox");
        $item52->setDescription("Welche Atmung hilft Stress zu eliminieren?");
        $item52->setCountPoint(1);
        $manager->persist($item52);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_52', $item52);

        $item53 = new WeeklyquizQuestion();
        $item53->setQuiz($this->getReference('weeklyquiz_11'));
        $item53->setName("Frage 3");
        $item53->setType("checkbox");
        $item53->setDescription("Was ist das Hauptproblem einer Fehlatmung?");
        $item53->setCountPoint(1);
        $manager->persist($item53);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_53', $item53);

        $item54 = new WeeklyquizQuestion();
        $item54->setQuiz($this->getReference('weeklyquiz_12'));
        $item54->setName("Frage 1");
        $item54->setType("checkbox");
        $item54->setDescription("Was können Sie präventiv gegen ein RSI-Syndrom unternehmen?");
        $item54->setCountPoint(1);
        $manager->persist($item54);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_54', $item54);

        $item56 = new WeeklyquizQuestion();
        $item56->setQuiz($this->getReference('weeklyquiz_12'));
        $item56->setName("Frage 2");
        $item56->setType("checkbox");
        $item56->setDescription("Beenden Sie den Satz korrekt: Stress und ein verspannter Nacken…");
        $item56->setCountPoint(1);
        $manager->persist($item56);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_56', $item56);

        $item57 = new WeeklyquizQuestion();
        $item57->setQuiz($this->getReference('weeklyquiz_12'));
        $item57->setName("Frage 3");
        $item57->setType("checkbox");
        $item57->setDescription("Welche Atemtechnik kann schädlich für den Körper sein?");
        $item57->setCountPoint(1);
        $manager->persist($item57);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_57', $item57);

        $item58 = new WeeklyquizQuestion();
        $item58->setQuiz($this->getReference('weeklyquiz_15'));
        $item58->setName("Frage 1");
        $item58->setType("checkbox");
        $item58->setDescription("Was kann man zur Gewohnheit werden lassen?");
        $item58->setCountPoint(1);
        $manager->persist($item58);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_58', $item58);

        $item59 = new WeeklyquizQuestion();
        $item59->setQuiz($this->getReference('weeklyquiz_15'));
        $item59->setName("Frage 2");
        $item59->setType("checkbox");
        $item59->setDescription("Wie lange dauert es ungefähr, bis eine wiederholte Tätigkeit zur Gewohnheit geworden ist?");
        $item59->setCountPoint(1);
        $manager->persist($item59);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_59', $item59);

        $item60 = new WeeklyquizQuestion();
        $item60->setQuiz($this->getReference('weeklyquiz_15'));
        $item60->setName("Frage 3");
        $item60->setType("checkbox");
        $item60->setDescription("Warum entwickelt unser Gehirn Gewohnheiten?");
        $item60->setCountPoint(1);
        $manager->persist($item60);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_60', $item60);

        $item61 = new WeeklyquizQuestion();
        $item61->setQuiz($this->getReference('weeklyquiz_16'));
        $item61->setName("Frage 1");
        $item61->setType("checkbox");
        $item61->setDescription("Welche der folgenden Aspekte stellen Methoden zum Erlernen und Ändern von Gewohnheiten dar?");
        $item61->setCountPoint(1);
        $manager->persist($item61);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_61', $item61);

        $item62 = new WeeklyquizQuestion();
        $item62->setQuiz($this->getReference('weeklyquiz_16'));
        $item62->setName("Frage 2");
        $item62->setType("checkbox");
        $item62->setDescription("Finden Sie den Fehler im folgenden Abschnitt: 
„Um sich  Gewohnheiten anzutrainieren, bedarf es lange Übung und viele Wiederholungen. Wenn man dabei einen Tag vergisst, die Tätigkeit zu wiederholen, ist der gesamte Trainingsfortschritt verloren und es muss von vorne angefangen werden.“");
        $item62->setCountPoint(1);
        $manager->persist($item62);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_62', $item62);

        $item63 = new WeeklyquizQuestion();
        $item63->setQuiz($this->getReference('weeklyquiz_16'));
        $item63->setName("Frage 3");
        $item63->setType("checkbox");
        $item63->setDescription("Was erleichtert das Erlernen von Gewohnheiten? (allgemein gesehen)");
        $item63->setCountPoint(1);
        $manager->persist($item63);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_63', $item63);

        $item64 = new WeeklyquizQuestion();
        $item64->setQuiz($this->getReference('weeklyquiz_17'));
        $item64->setName("Frage 1");
        $item64->setType("checkbox");
        $item64->setDescription("Welche der 4 kennengelernten Methoden ist am wirkungsvollsten?");
        $item64->setCountPoint(1);
        $manager->persist($item64);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_64', $item64);

        $item65 = new WeeklyquizQuestion();
        $item65->setQuiz($this->getReference('weeklyquiz_17'));
        $item65->setName("Frage 2");
        $item65->setType("checkbox");
        $item65->setDescription("Mit welchen speziellen Maßnahmen, kann man die Methode „Fokus“ optimal umsetzen?");
        $item65->setCountPoint(1);
        $manager->persist($item65);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_65', $item65);

        $item66 = new WeeklyquizQuestion();
        $item66->setQuiz($this->getReference('weeklyquiz_17'));
        $item66->setName("Frage 3");
        $item66->setType("radiobutton");
        $item66->setDescription("Ist die folgende Aussage korrekt oder falsch?
„Die aufgezeigten Methoden zum Ändern und Erlernen von Gewohnheiten müssen in einer bestimmten und festgelegten Reihenfolge praktiziert werden.“");
        $item66->setCountPoint(1);
        $manager->persist($item66);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_66', $item66);

        $item67 = new WeeklyquizQuestion();
        $item67->setQuiz($this->getReference('weeklyquiz_18'));
        $item67->setName("Frage 1");
        $item67->setType("checkbox");
        $item67->setDescription("Wofür ist die Linke Gehirnhälfte verantwortlich?");
        $item67->setCountPoint(1);
        $manager->persist($item67);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_67', $item67);

        $item68 = new WeeklyquizQuestion();
        $item68->setQuiz($this->getReference('weeklyquiz_18'));
        $item68->setName("Frage 2");
        $item68->setType("checkbox");
        $item68->setDescription("Wofür ist die Rechte Gehirnhälfte verantwortlich?");
        $item68->setCountPoint(1);
        $manager->persist($item68);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_68', $item68);

        $item69 = new WeeklyquizQuestion();
        $item69->setQuiz($this->getReference('weeklyquiz_18'));
        $item69->setName("Frage 3");
        $item69->setType("checkbox");
        $item69->setDescription("Finden Sie den Fehler in der folgenden Aussage:
„Nutzt man nur die linke Gehirnhälfte, dauert es sehr viel länger, etwas zu lernen bzw. sich zu konzentrieren. Gelingt es uns jedoch, die beiden Gehirnhälften zu verknüpfen können wir uns besser konzentrieren und effektiver arbeiten.“");
        $item69->setCountPoint(1);
        $manager->persist($item69);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_69', $item69);

        $item70 = new WeeklyquizQuestion();
        $item70->setQuiz($this->getReference('weeklyquiz_19'));
        $item70->setName("Frage 1");
        $item70->setType("checkbox");
        $item70->setDescription("Bei den meisten Menschen dominiert bei kognitiven Prozessen die eine Gehirnhälfte. Welche der folgenden Aussagen sind korrekt?");
        $item70->setCountPoint(1);
        $manager->persist($item70);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_70', $item70);

        $item71 = new WeeklyquizQuestion();
        $item71->setQuiz($this->getReference('weeklyquiz_19'));
        $item71->setName("Frage 2");
        $item71->setType("checkbox");
        $item71->setDescription("Stellen Sie sich vor, Sie sitzen im Büro und telefonieren mit einem  verärgerten Kunden, der nicht zurückgerufen wurde. Sie überprüfen also parallel im System die eingespeicherte Nummer. Währenddessen kommt Ihr Kollege in das Büro  und fragt Sie, wann denn das Meeting losgehe.
Welche Gehirnhälfte wird bei einer solchen Multitasking-Situation vor allem aktiviert?");
        $item71->setCountPoint(1);
        $manager->persist($item71);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_71', $item71);

        $item72 = new WeeklyquizQuestion();
        $item72->setQuiz($this->getReference('weeklyquiz_19'));
        $item72->setName("Frage 3");
        $item72->setType("checkbox");
        $item72->setDescription("Welche Gehirnhälfte ist primär verantwortlich, wenn Sie mit einem Hammer einen Nagel einschlagen sollen?");
        $item72->setCountPoint(1);
        $manager->persist($item72);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_72', $item72);

        $item74 = new WeeklyquizQuestion();
        $item74->setQuiz($this->getReference('weeklyquiz_20'));
        $item74->setName("Frage 1");
        $item74->setType("checkbox");
        $item74->setDescription("Was versteht man unter Überkreuzbewegungen?");
        $item74->setCountPoint(1);
        $manager->persist($item74);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_74', $item74);

        $item76 = new WeeklyquizQuestion();
        $item76->setQuiz($this->getReference('weeklyquiz_20'));
        $item76->setName("Frage 2");
        $item76->setType("checkbox");
        $item76->setDescription("Beenden Sie den folgenden Satz korrekt:
Die Körpermittellinie...");
        $item76->setCountPoint(1);
        $manager->persist($item76);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_76', $item76);

        $item77 = new WeeklyquizQuestion();
        $item77->setQuiz($this->getReference('weeklyquiz_20'));
        $item77->setName("Frage 3");
        $item77->setType("checkbox");
        $item77->setDescription("Welche der folgenden Aussagen sind korrekt?");
        $item77->setCountPoint(1);
        $manager->persist($item77);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_77', $item77);

        $item78 = new WeeklyquizQuestion();
        $item78->setQuiz($this->getReference('weeklyquiz_21'));
        $item78->setName("Frage 1");
        $item78->setType("radiobutton");
        $item78->setDescription("Wie viele Energiepunkte besitzt das Außenohr?");
        $item78->setCountPoint(1);
        $manager->persist($item78);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_78', $item78);

        $item79 = new WeeklyquizQuestion();
        $item79->setQuiz($this->getReference('weeklyquiz_21'));
        $item79->setName("Frage 2");
        $item79->setType("checkbox");
        $item79->setDescription("Welche Aussagen zur „Denkmütze“ sind korrekt?");
        $item79->setCountPoint(1);
        $manager->persist($item79);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_79', $item79);

        $item80 = new WeeklyquizQuestion();
        $item80->setQuiz($this->getReference('weeklyquiz_21'));
        $item80->setName("Frage 3");
        $item80->setType("radiobutton");
        $item80->setDescription("Wie erreicht man die Aktivierung der \"Denkmütze\"?");
        $item80->setCountPoint(1);
        $manager->persist($item80);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_80', $item80);

        $item81 = new WeeklyquizQuestion();
        $item81->setQuiz($this->getReference('weeklyquiz_24'));
        $item81->setName("Frage 1");
        $item81->setType("radiobutton");
        $item81->setDescription("Was ist die HÄUFIGSTE Ursache für Rückenschmerzen?");
        $item81->setCountPoint(1);
        $manager->persist($item81);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_81', $item81);

        $item82 = new WeeklyquizQuestion();
        $item82->setQuiz($this->getReference('weeklyquiz_24'));
        $item82->setName("Frage 2");
        $item82->setType("checkbox");
        $item82->setDescription("Welche Maßnahmen begünstigen den Genesungsprozess bei Rückenschmerzen?");
        $item82->setCountPoint(1);
        $manager->persist($item82);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_82', $item82);

        $item83 = new WeeklyquizQuestion();
        $item83->setQuiz($this->getReference('weeklyquiz_24'));
        $item83->setName("Frage 3");
        $item83->setType("radiobutton");
        $item83->setDescription("Ist folgender Satz korrekt, oder falsch?
„So lange Beschwerden noch relativ “frisch” sind, d.h. nicht länger als 4 – 6 Wochen andauern, stehen die Chancen ziemlich gut, dass nach wenigen Wochen wieder alles in Ordnung ist.“");
        $item83->setCountPoint(1);
        $manager->persist($item83);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_83', $item83);

        $item84 = new WeeklyquizQuestion();
        $item84->setQuiz($this->getReference('weeklyquiz_25'));
        $item84->setName("Frage 1");
        $item84->setType("radiobutton");
        $item84->setDescription("Welche Funktion hat Schmerz?");
        $item84->setCountPoint(1);
        $manager->persist($item84);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_84', $item84);

        $item85 = new WeeklyquizQuestion();
        $item85->setQuiz($this->getReference('weeklyquiz_25'));
        $item85->setName("Frage 2");
        $item85->setType("checkbox");
        $item85->setDescription("Finden Sie in folgender Aussage den Fehler:
„Wir verfügen damit über einen Schmerzsinn, da das Rückenmark oder das Gehirn bestimmt, ob die Meldung der Rezeptoren als Schmerz interpretiert wird oder nicht.“");
        $item85->setCountPoint(1);
        $manager->persist($item85);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_85', $item85);

        $item86 = new WeeklyquizQuestion();
        $item86->setQuiz($this->getReference('weeklyquiz_25'));
        $item86->setName("Frage 3");
        $item86->setType("radiobutton");
        $item86->setDescription("Bedeuten Rückenschmerzen gleichzeitig eine Schädigung des Rückens?");
        $item86->setCountPoint(1);
        $manager->persist($item86);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_86', $item86);

        $item87 = new WeeklyquizQuestion();
        $item87->setQuiz($this->getReference('weeklyquiz_26'));
        $item87->setName("Frage 1");
        $item87->setType("checkbox");
        $item87->setDescription("Welche Schmerzarten gibt es?");
        $item87->setCountPoint(1);
        $manager->persist($item87);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_87', $item87);

        $item88 = new WeeklyquizQuestion();
        $item88->setQuiz($this->getReference('weeklyquiz_26'));
        $item88->setName("Frage 2");
        $item88->setType("checkbox");
        $item88->setDescription("Welche Aussagen über den Alarmschmerz sind korrekt?");
        $item88->setCountPoint(1);
        $manager->persist($item88);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_88', $item88);

        $item89 = new WeeklyquizQuestion();
        $item89->setQuiz($this->getReference('weeklyquiz_26'));
        $item89->setName("Frage 3");
        $item89->setType("checkbox");
        $item89->setDescription("Welche Aussagen über den Leistungsschmerz sind korrekt?");
        $item89->setCountPoint(1);
        $manager->persist($item89);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_89', $item89);

        $item90 = new WeeklyquizQuestion();
        $item90->setQuiz($this->getReference('weeklyquiz_27'));
        $item90->setName("Frage 1");
        $item90->setType("checkbox");
        $item90->setDescription("Was sind die Hauptursachen für Rückenschmerzen?");
        $item90->setCountPoint(1);
        $manager->persist($item90);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_90', $item90);

        $item91 = new WeeklyquizQuestion();
        $item91->setQuiz($this->getReference('weeklyquiz_27'));
        $item91->setName("Frage 2");
        $item91->setType("checkbox");
        $item91->setDescription("Welche Maßnahmen sind wichtig, um Rückenschmerzen entgegenzuwirken?");
        $item91->setCountPoint(1);
        $manager->persist($item91);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_91', $item91);

        $item92 = new WeeklyquizQuestion();
        $item92->setQuiz($this->getReference('weeklyquiz_27'));
        $item92->setName("Frage 3");
        $item92->setType("checkbox");
        $item92->setDescription("Beenden Sie den Satz korrekt: 
„Dauerhafter Bewegungsmangel sorgt für...“");
        $item92->setCountPoint(1);
        $manager->persist($item92);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_92', $item92);

        $item93 = new WeeklyquizQuestion();
        $item93->setQuiz($this->getReference('weeklyquiz_28'));
        $item93->setName("Frage 1");
        $item93->setType("checkbox");
        $item93->setDescription("Wie entstehen Verspannungen?");
        $item93->setCountPoint(1);
        $manager->persist($item93);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_93', $item93);

        $item94 = new WeeklyquizQuestion();
        $item94->setQuiz($this->getReference('weeklyquiz_28'));
        $item94->setName("Frage 2");
        $item94->setType("checkbox");
        $item94->setDescription("Was sollte man bei Verspannungen tun?");
        $item94->setCountPoint(1);
        $manager->persist($item94);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_94', $item94);

        $item95 = new WeeklyquizQuestion();
        $item95->setQuiz($this->getReference('weeklyquiz_28'));
        $item95->setName("Frage 3");
        $item95->setType("checkbox");
        $item95->setDescription("Welche der folgenden Aussagen über Verspannungen sind FALSCH?");
        $item95->setCountPoint(1);
        $manager->persist($item95);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_95', $item95);

        $item96 = new WeeklyquizQuestion();
        $item96->setQuiz($this->getReference('weeklyquiz_29'));
        $item96->setName("Frage 1");
        $item96->setType("checkbox");
        $item96->setDescription("Was können Folgen einer Verspannung sein?");
        $item96->setCountPoint(1);
        $manager->persist($item96);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_96', $item96);

        $item97 = new WeeklyquizQuestion();
        $item97->setQuiz($this->getReference('weeklyquiz_29'));
        $item97->setName("Frage 2");
        $item97->setType("checkbox");
        $item97->setDescription("Was bedeutet es, wenn ein Muskel übersäuert?");
        $item97->setCountPoint(1);
        $manager->persist($item97);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_97', $item97);

        $item98 = new WeeklyquizQuestion();
        $item98->setQuiz($this->getReference('weeklyquiz_29'));
        $item98->setName("Frage 3");
        $item98->setType("checkbox");
        $item98->setDescription("Ist der folgende Satz korrekt oder falsch?
„Durch mangelnde oder fehlerhafte Beanspruchung verkürzen bzw. verspannen sich die Muskeln und können die Wirbelsäule nicht mehr ausreichend schützen und die Gelenke nicht mehr führen.“");
        $item98->setCountPoint(1);
        $manager->persist($item98);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_98', $item98);

        $item99 = new WeeklyquizQuestion();
        $item99->setQuiz($this->getReference('weeklyquiz_30'));
        $item99->setName("Frage 1");
        $item99->setType("checkbox");
        $item99->setDescription("Was passiert mit den Nerven, wenn der Körper unter Bewegungsmangel leidet?");
        $item99->setCountPoint(1);
        $manager->persist($item99);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_99', $item99);

        $item100 = new WeeklyquizQuestion();
        $item100->setQuiz($this->getReference('weeklyquiz_30'));
        $item100->setName("Frage 2");
        $item100->setType("checkbox");
        $item100->setDescription("Was kann zu einer gesundheitsschädigende Reizung der Nerven führen?");
        $item100->setCountPoint(1);
        $manager->persist($item100);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_100', $item100);

        $item101 = new WeeklyquizQuestion();
        $item101->setQuiz($this->getReference('weeklyquiz_30'));
        $item101->setName("Frage 3");
        $item101->setType("checkbox");
        $item101->setDescription("Wie heißt der größter Nerv im menschlichen Körper, der oft für Probleme sorgt?");
        $item101->setCountPoint(1);
        $manager->persist($item101);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_101', $item101);

        $item102 = new WeeklyquizQuestion();
        $item102->setQuiz($this->getReference('weeklyquiz_31'));
        $item102->setName("Frage 1");
        $item102->setType("checkbox");
        $item102->setDescription("Wodurch wird eine Sehnenscheidenentzündung meist hervorgerufen?");
        $item102->setCountPoint(1);
        $manager->persist($item102);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_102', $item102);

        $item103 = new WeeklyquizQuestion();
        $item103->setQuiz($this->getReference('weeklyquiz_31'));
        $item103->setName("Frage 2");
        $item103->setType("radiobutton");
        $item103->setDescription("Ist die folgende Antwort korrekt oder falsch?
„Stress und zu wenig Pausen am Arbeitsplatz können ein RSI-Syndrom verstärken.“");
        $item103->setCountPoint(1);
        $manager->persist($item103);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_103', $item103);

        $item104 = new WeeklyquizQuestion();
        $item104->setQuiz($this->getReference('weeklyquiz_31'));
        $item104->setName("Frage 3");
        $item104->setType("checkbox");
        $item104->setDescription("Was ist ein RSI-Syndrom?");
        $item104->setCountPoint(1);
        $manager->persist($item104);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_104', $item104);

        $item105 = new WeeklyquizQuestion();
        $item105->setQuiz($this->getReference('weeklyquiz_32'));
        $item105->setName("Frage 1");
        $item105->setType("checkbox");
        $item105->setDescription("Was ist eine Sehnenscheidenentzündung?");
        $item105->setCountPoint(1);
        $manager->persist($item105);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_105', $item105);

        $item106 = new WeeklyquizQuestion();
        $item106->setQuiz($this->getReference('weeklyquiz_32'));
        $item106->setName("Frage 2");
        $item106->setType("checkbox");
        $item106->setDescription("Was ist ein Karpaltunnelsyndrom?");
        $item106->setCountPoint(1);
        $manager->persist($item106);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_106', $item106);

        $item107 = new WeeklyquizQuestion();
        $item107->setQuiz($this->getReference('weeklyquiz_32'));
        $item107->setName("Frage 3");
        $item107->setType("checkbox");
        $item107->setDescription("Welche Aussagen sind korrekt?");
        $item107->setCountPoint(1);
        $manager->persist($item107);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_107', $item107);

        $item108 = new WeeklyquizQuestion();
        $item108->setQuiz($this->getReference('weeklyquiz_33'));
        $item108->setName("Frage 1");
        $item108->setType("checkbox");
        $item108->setDescription("Was können Sie präventiv gegen ein RSI-Syndrom unternehmen?");
        $item108->setCountPoint(1);
        $manager->persist($item108);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_108', $item108);

        $item109 = new WeeklyquizQuestion();
        $item109->setQuiz($this->getReference('weeklyquiz_33'));
        $item109->setName("Frage 2");
        $item109->setType("checkbox");
        $item109->setDescription("Welches der folgenden Präventivmaßnahmen gehört zum „Dynamischen Arbeiten“?");
        $item109->setCountPoint(1);
        $manager->persist($item109);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_109', $item109);

        $item110 = new WeeklyquizQuestion();
        $item110->setQuiz($this->getReference('weeklyquiz_33'));
        $item110->setName("Frage 3");
        $item110->setType("checkbox");
        $item110->setDescription("Finden Sie den Fehler in folgender Aussage:
 „Ideal wäre der Wechsel von verschiedenen Eingabegeräten über den Tag hinweg, um eine einseitige Beanspruchung einzelner Muskeln, Sehnen und Nerven zu gewährleisten.“");
        $item110->setCountPoint(1);
        $manager->persist($item110);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_110', $item110);

        $item111 = new WeeklyquizQuestion();
        $item111->setQuiz($this->getReference('weeklyquiz_34'));
        $item111->setName("Frage 1");
        $item111->setType("radiobutton");
        $item111->setDescription("Wie viele Bandscheiben besitzt der menschliche Körper?");
        $item111->setCountPoint(1);
        $manager->persist($item111);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_111', $item111);

        $item112 = new WeeklyquizQuestion();
        $item112->setQuiz($this->getReference('weeklyquiz_34'));
        $item112->setName("Frage 2");
        $item112->setType("checkbox");
        $item112->setDescription("Wo im menschlichen Körper befinden sich die Bandscheiben?");
        $item112->setCountPoint(1);
        $manager->persist($item112);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_112', $item112);

        $item113 = new WeeklyquizQuestion();
        $item113->setQuiz($this->getReference('weeklyquiz_34'));
        $item113->setName("Frage 3");
        $item113->setType("checkbox");
        $item113->setDescription("In wie vielen Fällen sind für Rückenschmerzen die Bandscheiben verantwortlich?");
        $item113->setCountPoint(1);
        $manager->persist($item113);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_113', $item113);

        $item114 = new WeeklyquizQuestion();
        $item114->setQuiz($this->getReference('weeklyquiz_35'));
        $item114->setName("Frage 1");
        $item114->setType("checkbox");
        $item114->setDescription("Was passiert mit den Bandscheiben, wenn zu einem Bandscheibenvorfall kommt?");
        $item114->setCountPoint(1);
        $manager->persist($item114);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_114', $item114);

        $item115 = new WeeklyquizQuestion();
        $item115->setQuiz($this->getReference('weeklyquiz_35'));
        $item115->setName("Frage 2");
        $item115->setType("checkbox");
        $item115->setDescription("Damit die Bandscheiben lange gesund bleiben müssen sie bewegt werden. Was bewirkt diese Bewegung?");
        $item115->setCountPoint(1);
        $manager->persist($item115);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_115', $item115);

        $item116 = new WeeklyquizQuestion();
        $item116->setQuiz($this->getReference('weeklyquiz_35'));
        $item116->setName("Frage 3");
        $item116->setType("checkbox");
        $item116->setDescription("Wie kommt es zu den schrecklichen Schmerzen bei einem Bandscheibenvorfall?");
        $item116->setCountPoint(1);
        $manager->persist($item116);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_116', $item116);

        $item117 = new WeeklyquizQuestion();
        $item117->setQuiz($this->getReference('weeklyquiz_36'));
        $item117->setName("Frage 1");
        $item117->setType("checkbox");
        $item117->setDescription("Welche der folgenden Aussagen sind falsch?");
        $item117->setCountPoint(1);
        $manager->persist($item117);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_117', $item117);

        $item118 = new WeeklyquizQuestion();
        $item118->setQuiz($this->getReference('weeklyquiz_36'));
        $item118->setName("Frage 2");
        $item118->setType("checkbox");
        $item118->setDescription("Wann ist der Druck der Bandscheiben optimal verteilt?");
        $item118->setCountPoint(1);
        $manager->persist($item118);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_118', $item118);

        $item119 = new WeeklyquizQuestion();
        $item119->setQuiz($this->getReference('weeklyquiz_36'));
        $item119->setName("Frage 3");
        $item119->setType("checkbox");
        $item119->setDescription("Beenden Sie den folgenden Satz korrekt:
„Wenn der Galertkern austritt, aber kein Nerv betroffen ist,...“");
        $item119->setCountPoint(1);
        $manager->persist($item119);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_119', $item119);

        $item120 = new WeeklyquizQuestion();
        $item120->setQuiz($this->getReference('weeklyquiz_37'));
        $item120->setName("Frage 1");
        $item120->setType("checkbox");
        $item120->setDescription("Wie kann man die Bandscheibe entlasten?");
        $item120->setCountPoint(1);
        $manager->persist($item120);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_120', $item120);

        $item121 = new WeeklyquizQuestion();
        $item121->setQuiz($this->getReference('weeklyquiz_37'));
        $item121->setName("Frage 2");
        $item121->setType("checkbox");
        $item121->setDescription("Worauf sollte bei den vorgeschlagenen Übungen geachtet werden?");
        $item121->setCountPoint(1);
        $manager->persist($item121);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_121', $item121);

        $item122 = new WeeklyquizQuestion();
        $item122->setQuiz($this->getReference('weeklyquiz_37'));
        $item122->setName("Frage 3");
        $item122->setType("checkbox");
        $item122->setDescription("Was wird außerdem noch mit den Übungen erreicht?");
        $item122->setCountPoint(1);
        $manager->persist($item122);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_122', $item122);

        $item123 = new WeeklyquizQuestion();
        $item123->setQuiz($this->getReference('weeklyquiz_38'));
        $item123->setName("Frage 1");
        $item123->setType("checkbox");
        $item123->setDescription("Welche Funktionen besitzen die Bandscheiben?");
        $item123->setCountPoint(1);
        $manager->persist($item123);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_123', $item123);

        $item124 = new WeeklyquizQuestion();
        $item124->setQuiz($this->getReference('weeklyquiz_38'));
        $item124->setName("Frage 2");
        $item124->setType("checkbox");
        $item124->setDescription("Mit was könnte man den Galertkern vergleichen?");
        $item124->setCountPoint(1);
        $manager->persist($item124);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_124', $item124);

        $item125 = new WeeklyquizQuestion();
        $item125->setQuiz($this->getReference('weeklyquiz_38'));
        $item125->setName("Frage 3");
        $item125->setType("radiobutton");
        $item125->setDescription("Ist folgende Aussage korrekt oder falsch?
„Aufgrund des Körpergewicht wird das Wasser beim Stehen aus der Bandscheibe gedrückt. Aus diesem Grund sind Menschen morgens 2-3 cm größer als abends.“");
        $item125->setCountPoint(1);
        $manager->persist($item125);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_125', $item125);

        $item126 = new WeeklyquizQuestion();
        $item126->setQuiz($this->getReference('weeklyquiz_39'));
        $item126->setName("Frage 1");
        $item126->setType("checkbox");
        $item126->setDescription("Welche Ziele verfolgt die Progressiver Muskelentspannung (PMR)?");
        $item126->setCountPoint(1);
        $manager->persist($item126);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_126', $item126);

        $item127 = new WeeklyquizQuestion();
        $item127->setQuiz($this->getReference('weeklyquiz_39'));
        $item127->setName("Frage 2");
        $item127->setType("checkbox");
        $item127->setDescription("Wie soll man nach dem PMR Spannungs- & Entspannungszustände im Körper bewusster wahrnehmen?");
        $item127->setCountPoint(1);
        $manager->persist($item127);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_127', $item127);

        $item128 = new WeeklyquizQuestion();
        $item128->setQuiz($this->getReference('weeklyquiz_39'));
        $item128->setName("Frage 3");
        $item128->setType("radiobutton");
        $item128->setDescription("In welcher Reihenfolge wird der Zyklus des PMR angewendet?");
        $item128->setCountPoint(1);
        $manager->persist($item128);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_128', $item128);

        $item129 = new WeeklyquizQuestion();
        $item129->setQuiz($this->getReference('weeklyquiz_40'));
        $item129->setName("Frage 1");
        $item129->setType("checkbox");
        $item129->setDescription("Wie lange sollte die Anspannungsphase bei der Progressiven Muskelentspannung andauern?");
        $item129->setCountPoint(1);
        $manager->persist($item129);
        $manager->flush();
        // add reference for object to load with order > 2
        // to load weeklyquiz question answers
        $this->addReference('weeklyquiz_question_129', $item129);
    }

}
