<?php

namespace Fitbase\Bundle\WeeklytaskBundle\DataFixture\ORM;
;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Fitbase\Bundle\WeeklytaskBundle\Entity\Weeklyquiz;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadWeeklyquiz extends AbstractFixture implements OrderedFixtureInterface
{

    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 1;
    }

    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetaData(get_class(new Weeklyquiz()))->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item13=new Weeklyquiz();
        $item13->setId(13);
        $item13->setFormat("richhtml");
        $item13->setName("Quiz zur ersten Wochenaufgabe");
        $item13->setDescription(<<<EOT
<img class="alignleft wp-image-1536 size-medium" width="300" height="204" alt="wa5_richtig-sitzen" src="http://online-rueckenschule.de/wp-content/uploads/wa5_richtig-sitzen-300x204.jpg" />
Dieses Quiz ist aus dem Bereich<strong> ergonomische Arbeitsplatzgestaltung</strong>
und fragt die richtige
<strong>Ausrichtung des Bildschirmes</strong>
ab.
EOT
        );
        $item13->setCountPoint(1);
        $manager->persist($item13);
        $manager->flush();
        $this->addReference('weeklyquiz_1', $item13);

        $item14=new Weeklyquiz();
        $item14->setId(14);
        $item14->setFormat("richhtml");
        $item14->setName("Quiz zur 2. Wochenaufgabe");
        $item14->setDescription(<<<EOT
<strong><a href="http://online-rueckenschule.de/wp-content/uploads/mouse1.jpg">
<img src="http://online-rueckenschule.de/wp-content/uploads/mouse1-300x172.jpg" alt="mouse" width="300" height="172" class="alignleft wp-image-1828 size-medium" /></a> Ergonomische Arbeitsplatzgestaltung:</strong> In dieser Wochenaufgabe geht es um die<strong>richtige Handhaltung</strong> (der Maus).
EOT
        );
        $item14->setCountPoint(1);
        $manager->persist($item14);
        $manager->flush();
        $this->addReference('weeklyquiz_2', $item14);

        $item15=new Weeklyquiz();
        $item15->setId(15);
        $item15->setFormat("richhtml");
        $item15->setName("Quiz zur 8. Wochenaufgabe");
        $item15->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/Screen-Shot-2012-06-08-at-11_00_01-PM.png"><img src="http://online-rueckenschule.de/wp-content/uploads/Screen-Shot-2012-06-08-at-11_00_01-PM-198x300.png" alt="Screen-Shot-2012-06-08-at-11_00_01-PM" width="198" height="300" class="alignleft wp-image-1533 size-medium" /></a> Dieses Quiz ist aus dem Bereich der<strong> Aufrechte Körperhaltung</strong> und stellt Fragen zur Aufrechte<strong>Körperhaltung im Stand</strong>.
EOT
        );
        $item15->setCountPoint(1);
        $manager->persist($item15);
        $manager->flush();
        $this->addReference('weeklyquiz_8', $item15);


        $item16=new Weeklyquiz();
        $item16->setId(16);
        $item16->setFormat("richhtml");
        $item16->setName("Quiz zur 5. Wochenaufgabe");
        $item16->setDescription(<<<EOT
<strong><a href="http://online-rueckenschule.de/wp-content/uploads/PC1-300x184.jpg">
<img src="http://online-rueckenschule.de/wp-content/uploads/PC1-300x184.jpg" alt="PC1-300x184" width="300" height="184" class="alignleft wp-image-1526 size-full" /></a></strong> Dieses Quiz ist aus dem Bereich der<strong> Ergonomische Arbeitsplatzgestaltung </strong> und stellt Fragen zum ergonomische<strong>Sitzen am Schreibtisch</strong>.
EOT
        );
        $item16->setCountPoint(1);
        $manager->persist($item16);
        $manager->flush();
        $this->addReference('weeklyquiz_5', $item16);

        $item17=new Weeklyquiz();
        $item17->setId(17);
        $item17->setFormat("richhtml");
        $item17->setName("Quiz zur 3. Wochenaufgabe");
        $item17->setDescription(<<<EOT
<strong><a href="http://online-rueckenschule.de/wp-content/uploads/keyboard_right.jpg">
<img src="http://online-rueckenschule.de/wp-content/uploads/keyboard_right-300x166.jpg" alt="keyboard_right" width="300" height="166" class="alignleft wp-image-1832 size-medium" /></a></strong> Dieses Quiz ist aus dem Bereich der<strong> Ergonomische Arbeitsplatzgestaltung</strong> und stellt Fragen zur ergonomischen<strong> Be</strong><strong> dienung der Tastatur</strong>.
EOT
        );
        $item17->setCountPoint(1);
        $manager->persist($item17);
        $manager->flush();
        $this->addReference('weeklyquiz_3', $item17);


        $item18=new Weeklyquiz();
        $item18->setId(18);
        $item18->setFormat("richhtml");
        $item18->setName("Quiz zur 4. Wochenaufgabe");
        $item18->setDescription(<<<EOT
<strong><a href="http://online-rueckenschule.de/wp-content/uploads/richtigsitzen_abbildung1.jpg">
<img src="http://online-rueckenschule.de/wp-content/uploads/richtigsitzen_abbildung1-163x300.jpg" alt="richtigsitzen_abbildung" width="163" height="300" class="alignleft wp-image-1835 size-medium" /></a></strong> Dieses Quiz ist aus dem Bereich der<strong>Ergonomische Arbeitsplatzgestaltung </strong> und stellt Fragen über das ergonomische<strong>Sitzen am Arbeitsplatz.</strong>
EOT
        );
        $item18->setCountPoint(1);
        $manager->persist($item18);
        $manager->flush();
        $this->addReference('weeklyquiz_4', $item18);

        $item19=new Weeklyquiz();
        $item19->setId(19);
        $item19->setFormat("richhtml");
        $item19->setName("Quiz zur 6. Wochenaufgabe");
        $item19->setDescription(<<<EOT
<strong><a href="http://online-rueckenschule.de/wp-content/uploads/car-seat-300x237.jpg">
<img src="http://online-rueckenschule.de/wp-content/uploads/car-seat-300x237.jpg" alt="car-seat-300x237" width="300" height="237" class="alignleft wp-image-1513 size-full" /></a></strong> Dieses Quiz ist aus dem Bereich der<strong> Ergonomischen Arbeitsplatzgestaltung </strong> und stellt Fragen über die ergonomische<strong>Einstellung des Autositzes.</strong>
EOT
        );
        $item19->setCountPoint(1);
        $manager->persist($item19);
        $manager->flush();
        $this->addReference('weeklyquiz_6', $item19);


        $item20=new Weeklyquiz();
        $item20->setId(20);
        $item20->setFormat("richhtml");
        $item20->setName("Quiz zur 7. Wochenaufgabe");
        $item20->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/posture_2_officephysio.jpg">
<img src="http://online-rueckenschule.de/wp-content/uploads/posture_2_officephysio-284x300.jpg" alt="posture_2_officephysio" width="284" height="300" class="alignleft wp-image-1847 size-medium" /></a><a href="\" http:="" online-rueckenschule="" de="" wp-content="" uploads="" posture_2_officephysio="" jpg=""></a>Dieses Quiz ist aus dem Bereich der<strong>Körperhaltung</strong>und stellt Fragen zur <strong>Aufrechten Sitzhaltung</strong>.
EOT
        );
        $item20->setCountPoint(1);
        $manager->persist($item20);
        $manager->flush();
        $this->addReference('weeklyquiz_7', $item20);


        $item21=new Weeklyquiz();
        $item21->setId(21);
        $item21->setFormat("richhtml");
        $item21->setName("Quiz zur 9. Wochenaufgabe");
        $item21->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/atmung_de.jpg">
<img src="http://online-rueckenschule.de/wp-content/uploads/atmung_de-300x256.jpg" alt="atmung_de" width="300" height="256" class="alignleft wp-image-1851 size-medium" /></a><a href="\" http:="" online-rueckenschule="" de="" wp-content="" uploads="" atmung_de-300x256="" jpg=""></a>Dieses Quiz ist aus dem Bereich der<strong>Atmung</strong> und fragt<strong>allgemeine Merkmale</strong> über die Atmung ab.
EOT
        );
        $item21->setCountPoint(1);
        $manager->persist($item21);
        $manager->flush();
        $this->addReference('weeklyquiz_9', $item21);

        $item22=new Weeklyquiz();
        $item22->setId(22);
        $item22->setFormat("richhtml");
        $item22->setName("Quiz zur 10. Wochenaufgabe");
        $item22->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/einatmen.jpg">
<img src="http://online-rueckenschule.de/wp-content/uploads/einatmen-300x209.jpg" alt="einatmen" width="300" height="209" class="alignleft wp-image-1857 size-medium" /></a><a href="\" http:="" online-rueckenschule="" de="" wp-content="" uploads="" einatmen="" jpg=""></a>Dieses Quiz ist aus dem Bereich der<strong>Atmung</strong> und stellt hauptsächlich Fragen zur<strong>Atmungsauswirkung auf die Wirbelsäule</strong>.
EOT
        );
        $item22->setCountPoint(1);
        $manager->persist($item22);
        $manager->flush();
        $this->addReference('weeklyquiz_10', $item22);

        $item23=new Weeklyquiz();
        $item23->setId(23);
        $item23->setFormat("richhtml");
        $item23->setName("Quiz zur 11. Wochenaufgabe");
        $item23->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/atmung_de.jpg">
<img src="http://online-rueckenschule.de/wp-content/uploads/atmung_de-300x256.jpg" alt="atmung_de" width="300" height="256" class="alignleft wp-image-1851 size-medium" /></a>Dieses Quiz ist aus dem Bereich der<strong>Atmung</strong> und stellt Fragen zur <strong>Fehlatmung</strong>.<a href="\" http:="" online-rueckenschule="" de="" wp-content="" uploads="" atmung_de="" jpg=""></a>
EOT
        );
        $item23->setCountPoint(1);
        $manager->persist($item23);
        $manager->flush();
        $this->addReference('weeklyquiz_11', $item23);

        $item24=new Weeklyquiz();
        $item24->setId(24);
        $item24->setFormat("richhtml");
        $item24->setName("Quiz zur 12. Wochenaufgabe");
        $item24->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/mind.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/mind-286x300.png" alt="mind" width="286" height="300" class="alignleft wp-image-1908 size-medium" /></a>Dieses Quiz ist eigentlich aus dem Bereich der Atmung. Nichtsdestotrotz soll es als kurze<strong>Wiederholung</strong> der letzten Wochen dienen und stellt fragen über die<strong>Ergonomie am Arbeitsplatz</strong>, die<strong>Atmung</strong> und<strong>Verspannungen</strong>.<a href="http://online-rueckenschule.de/wp-content/uploads/mind.png"></a>
EOT
        );
        $item24->setCountPoint(1);
        $manager->persist($item24);
        $manager->flush();
        $this->addReference('weeklyquiz_12', $item24);

        $item25=new Weeklyquiz();
        $item25->setId(25);
        $item25->setFormat("richhtml");
        $item25->setName("Quiz zur 15. Wochenaufgabe");
        $item25->setDescription(<<<EOT
Dieses Quiz ist aus dem Bereich der<strong>Gewohnheit</strong> und stellt<strong>allgemeine Fragen</strong>
zu dem Thema.<a href="http://online-rueckenschule.de/wp-content/uploads/top.jpg">
<img src="http://online-rueckenschule.de/wp-content/uploads/top-150x150.jpg" alt="top" width="150" height="150" class="alignleft wp-image-1903 size-thumbnail" /></a><a href="\" http:="" online-rueckenschule="" de="" wp-content="" uploads="" top-300x198="" jpg=""></a>
EOT
        );
        $item25->setCountPoint(1);
        $manager->persist($item25);
        $manager->flush();
        $this->addReference('weeklyquiz_15', $item25);

        $item26=new Weeklyquiz();
        $item26->setId(26);
        $item26->setFormat("richhtml");
        $item26->setName("Quiz zur 16. Wochenaufgabe");
        $item26->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/priority1.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/priority1.png" alt="priority" width="282" height="238" class="alignleft wp-image-1899 size-full" /></a>  Dieses Quiz ist aus dem Bereich der<strong>Gewohnheit</strong> und stellt Fragen über das Ändern und<strong> Erlernen von Gewohnheiten</strong>.<a href="\" http:="" online-rueckenschule="" de="" wp-content="" uploads="" priority1="" png=""></a>
EOT
        );
        $item26->setCountPoint(1);
        $manager->persist($item26);
        $manager->flush();
        $this->addReference('weeklyquiz_16', $item26);

        $item27=new Weeklyquiz();
        $item27->setId(27);
        $item27->setFormat("richhtml");
        $item27->setName("Quiz zur 17. Wochenaufgabe");
        $item27->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/mind.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/mind-286x300.png" alt="mind" class="alignleft wp-image-1908 size-medium" height="300" width="286" /></a>Dieses Quiz ist aus dem Bereich der<strong>Gewohnheit</strong> und stellt Fragen über die<strong>Methoden</strong>, wie diese verändert oder erlernt werden können.
EOT
        );
        $item27->setCountPoint(1);
        $manager->persist($item27);
        $manager->flush();
        $this->addReference('weeklyquiz_17', $item27);


        $item28=new Weeklyquiz();
        $item28->setId(28);
        $item28->setFormat("richhtml");
        $item28->setName("Quiz zur 18. Wochenaufgabe");
        $item28->setDescription(<<<EOT
Dieses Quiz ist aus dem Bereich der<strong>Konzentration</strong> und stellt Fragen zu den Aufgaben der beiden
<strong>Gehirnhälften</strong>.<a href="http://online-rueckenschule.de/wp-content/uploads/gehirnhaelften.png"><img src="http://online-rueckenschule.de/wp-content/uploads/gehirnhaelften-300x134.png" alt="gehirnhaelften" width="300" height="134" class="alignleft wp-image-1914 size-medium" /></a><a href="\" http:="" online-rueckenschule="" de="" wp-content="" uploads="" gehirnhaelften="" png=""></a>
EOT
        );
        $item28->setCountPoint(1);
        $manager->persist($item28);
        $manager->flush();
        $this->addReference('weeklyquiz_18', $item28);


        $item29=new Weeklyquiz();
        $item29->setId(29);
        $item29->setFormat("richhtml");
        $item29->setName("Quiz zur 19. Wochenaufgabe");
        $item29->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa19.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa19-300x200.png" alt="wa19" width="300" height="200" class="alignleft wp-image-1922 size-medium" /></a>
Dieses Quiz ist aus dem Bereich der<strong>Konzentration</strong>  und stellt Fragen zu den beiden<strong>Gehirnhälften</strong>.<a href="http://online-rueckenschule.de/wp-content/uploads/wa19.png"></a>
EOT
        );
        $item29->setCountPoint(1);
        $manager->persist($item29);
        $manager->flush();
        $this->addReference('weeklyquiz_19', $item29);


        $item30=new Weeklyquiz();
        $item30->setId(30);
        $item30->setFormat("richhtml");
        $item30->setName("Quiz zur 20. Wochenaufgabe");
        $item30->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa20_1_mittellinie.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa20_1_mittellinie.png" alt="wa20_1_mittellinie" width="99" height="250" class="alignleft wp-image-1927 size-full" /></a> Diese Quiz ist aus dem Bereich des Themas -<strong> Gehirn</strong> und stellt Fragen zu den<strong>Kreuzbewegungen</strong>.<a href="http://online-rueckenschule.de/wp-content/uploads/wa20_1_mittellinie.png">
</a><a href="http://online-rueckenschule.de/wp-content/uploads/wa20_1_mittellinie.png"></a>
<a href="http://online-rueckenschule.de/wp-content/uploads/wa20_1_mittellinie.png"></a><a href="\" http:="" online-rueckenschule="" de="" wp-content="" uploads="" wa20_1_mittellinie="" png=""></a>
EOT
        );
        $item30->setCountPoint(1);
        $manager->persist($item30);
        $manager->flush();
        $this->addReference('weeklyquiz_20', $item30);


        $item31=new Weeklyquiz();
        $item31->setId(31);
        $item31->setFormat("richhtml");
        $item31->setName("Quiz zur 21. Wochenaufgabe");
        $item31->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa21_denkmuetze.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa21_denkmuetze-300x221.png" alt="wa21_denkmuetze" width="300" height="221" class="alignleft wp-image-1938 size-medium" /></a> Dieses Quiz ist aus dem Bereich der<strong>Konzentration</strong> und stellt Fragen zur<strong>"Denkmütze"</strong><a href="\" http:="" online-rueckenschule="" de="" wp-content="" uploads="" wa21_denkmuetze="" png=""></a>
EOT
        );
        $item31->setCountPoint(1);
        $manager->persist($item31);
        $manager->flush();
        $this->addReference('weeklyquiz_21', $item31);


        $item32=new Weeklyquiz();
        $item32->setId(32);
        $item32->setFormat("richhtml");
        $item32->setName("Quiz zur 24. Wochenaufgabe");
        $item32->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa24.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa24-198x300.png" alt="wa24" width="198" height="300" class="alignleft wp-image-1954 size-medium" /></a> Dieses Quiz ist aus dem Bereich<strong>Rückenschmerzen</strong> und stellt Fragen zu <strong>Ursachen und Maßnahmen</strong>.<a href="\" http:="" online-rueckenschule="" de="" wp-content="" uploads="" wa24="" png=""></a>
EOT
        );
        $item32->setCountPoint(1);
        $manager->persist($item32);
        $manager->flush();
        $this->addReference('weeklyquiz_24', $item32);


        $item33=new Weeklyquiz();
        $item33->setId(33);
        $item33->setFormat("richhtml");
        $item33->setName("Quiz zur 25. Wochenaufgabe");
        $item33->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa24.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa24-198x300.png" alt="wa24" width="198" height="300" class="alignleft wp-image-1954 size-medium" /></a> Dieses Quiz ist aus dem Bereich<strong>Rückenschmerzen</strong> und stellt Fragen zum<strong>Schmerz</strong>.<a href="\" http:="" online-rueckenschule="" de="" wp-content="" uploads="" wa24="" png=""></a>
EOT
        );
        $item33->setCountPoint(1);
        $manager->persist($item33);
        $manager->flush();
        $this->addReference('weeklyquiz_25', $item33);


        $item34=new Weeklyquiz();
        $item34->setId(34);
        $item34->setFormat("richhtml");
        $item34->setName("Quiz zur 26. Wochenaufgabe");
        $item34->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa26.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa26-300x207.png" alt="wa26" width="300" height="207" class="alignleft wp-image-1966 size-medium" /></a> Dieses Quiz ist aus dem Bereich<strong> Beschwerden</strong> und stellt Fragen zu den verschiedenen<strong>Schmerzarten</strong>.<a href="\" http:="" online-rueckenschule="" de="" wp-content="" uploads="" wa26="" png=""></a>
EOT
        );
        $item34->setCountPoint(1);
        $manager->persist($item34);
        $manager->flush();
        $this->addReference('weeklyquiz_26', $item34);


        $item35=new Weeklyquiz();
        $item35->setId(35);
        $item35->setFormat("richhtml");
        $item35->setName("Quiz zur 27. Wochenaufgabe");
        $item35->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa27.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa27-300x220.png" alt="wa27" width="300" height="220" class="alignleft wp-image-1970 size-medium" /></a>Dieses Quiz ist aus dem Bereich<strong>Beschwerden</strong> und stellt Fragen zum<strong>Bewegungsmangel</strong>.<a href="\" http:="" online-rueckenschule="" de="" wp-content="" uploads="" wa27="" png=""></a>
EOT
        );
        $item35->setCountPoint(1);
        $manager->persist($item35);
        $manager->flush();
        $this->addReference('weeklyquiz_27', $item35);


        $item38=new Weeklyquiz();
        $item38->setId(38);
        $item38->setFormat("richhtml");
        $item38->setName("Quiz zur 28. Wochenaufgabe");
        $item38->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa5_sitting-wrong1.jpg">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa5_sitting-wrong1-300x223.jpg" alt="wa5_sitting wrong" width="300" height="223" class="alignleft wp-image-1839 size-medium" /></a>Dieses Quiz ist aus dem Bereich<strong>Rückenschmerzen</strong> und stellt Fragen zu<strong>Verspannungen</strong>.<a href="http://online-rueckenschule.de/wp-content/uploads/wa5_sitting-wrong1.jpg"></a>
EOT
        );
        $item38->setCountPoint(1);
        $manager->persist($item38);
        $manager->flush();
        $this->addReference('weeklyquiz_28', $item38);


        $item39=new Weeklyquiz();
        $item39->setId(39);
        $item39->setFormat("richhtml");
        $item39->setName("Quiz zur 29. Wochenaufgabe");
        $item39->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/frau-stretching-300x285.jpg">
<img src="http://online-rueckenschule.de/wp-content/uploads/frau-stretching-300x285.jpg" alt="frau-stretching-300x285" width="300" height="285" class="alignleft wp-image-1785 size-full" /></a>  Dieses Quiz ist aus dem Bereich der<strong>Beschwerden</strong> und stellt Fragen zur<strong>Übersäuerung</strong> und zur<strong>Muskelschwäche</strong>.
EOT
        );
        $item39->setCountPoint(1);
        $manager->persist($item39);
        $manager->flush();
        $this->addReference('weeklyquiz_29', $item39);


        $item40=new Weeklyquiz();
        $item40->setId(40);
        $item40->setFormat("richhtml");
        $item40->setName("Quiz zur 30. Wochenaufgabe");
        $item40->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa30.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa30-300x160.png" alt="wa30" width="300" height="160" class="alignleft wp-image-1986 size-medium" /></a> Dieses Quiz ist aus dem Bereich
<strong>Beschwerden</strong> und stellt Fragen zu den<strong>Nerven</strong>.
EOT
        );
        $item40->setCountPoint(1);
        $manager->persist($item40);
        $manager->flush();
        $this->addReference('weeklyquiz_30', $item40);


        $item41=new Weeklyquiz();
        $item41->setId(41);
        $item41->setFormat("richhtml");
        $item41->setName("Quiz zur 31. Wochenaufgabe");
        $item41->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa31.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa31-300x177.png" alt="wa31" width="300" height="177" class="alignleft wp-image-1991 size-medium" /></a> Dieses Quiz ist aus dem Bereich der<strong>Nerven</strong> und stellt Fragen zum<strong>Hand - und Armbereich</strong>.
EOT
        );
        $item41->setCountPoint(1);
        $manager->persist($item41);
        $manager->flush();
        $this->addReference('weeklyquiz_31', $item41);


        $item42=new Weeklyquiz();
        $item42->setId(42);
        $item42->setFormat("richhtml");
        $item42->setName("Quiz zur 32. Wochenaufgabe");
        $item42->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa31.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa31-300x177.png" alt="wa31" width="300" height="177" class="alignleft wp-image-1991 size-medium" /></a> Dieses Quiz ist aus dem Bereich der<strong>Nerven</strong> und stellt Fragen zur<strong>Sehnenscheidenentzündung</strong> und dem<strong>Karpaltunnelsyndroms</strong>.
EOT
        );
        $item42->setCountPoint(1);
        $manager->persist($item42);
        $manager->flush();
        $this->addReference('weeklyquiz_32', $item42);


        $item43=new Weeklyquiz();
        $item43->setId(43);
        $item43->setFormat("richhtml");
        $item43->setName("Quiz zur 33. Wochenaufgabe");
        $item43->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa31.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa31-300x177.png" alt="wa31" width="300" height="177" class="alignleft wp-image-1991 size-medium" /></a> Dieses Quiz ist aus dem Bereich der<strong>Nerven</strong> und stellt Fragen zu<strong>präventiven Maßnahmen</strong> gegen RSI.
EOT
        );
        $item43->setCountPoint(1);
        $manager->persist($item43);
        $manager->flush();
        $this->addReference('weeklyquiz_33', $item43);


        $item44=new Weeklyquiz();
        $item44->setId(44);
        $item44->setFormat("richhtml");
        $item44->setName("Quiz zur 34. Wochenaufgabe");
        $item44->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa341.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa341-182x300.png" alt="wa34" width="182" height="300" class="alignleft wp-image-2004 size-medium" /></a> Dieses Quiz ist aus dem Bereich der<strong>Bandscheiben</strong> und stellt Fragen zu allgemeinen...
EOT
        );
        $item44->setCountPoint(1);
        $manager->persist($item44);
        $manager->flush();
        $this->addReference('weeklyquiz_34', $item44);


        $item45=new Weeklyquiz();
        $item45->setId(45);
        $item45->setFormat("richhtml");
        $item45->setName("Quiz zur 35. Wochenaufgabe");
        $item45->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa36_31.png"><img src="http://online-rueckenschule.de/wp-content/uploads/wa36_31-300x135.png" alt="wa36_3" width="300" height="135" class="alignleft wp-image-2021 size-medium" /></a> Dieses Quiz ist aus dem Bereich<strong>Beschwerden</strong> und stellt Fragen zu den<strong>Bandscheiben</strong>.
EOT
        );
        $item45->setCountPoint(1);
        $manager->persist($item45);
        $manager->flush();
        $this->addReference('weeklyquiz_35', $item45);


        $item46=new Weeklyquiz();
        $item46->setId(46);
        $item46->setFormat("richhtml");
        $item46->setName("Quiz zur 36. Wochenaufgabe");
        $item46->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa361.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa361.png" alt="wa36" width="222" height="233" class="alignleft wp-image-2015 size-full" /></a> Dieses Quiz ist aus dem Bereich der<strong>Beschwerden</strong> und stellt Fragen zum<strong>Bandscheibenvorfall</strong>.
EOT
        );
        $item46->setCountPoint(1);
        $manager->persist($item46);
        $manager->flush();
        $this->addReference('weeklyquiz_36', $item46);


        $item47=new Weeklyquiz();
        $item47->setId(47);
        $item47->setFormat("richhtml");
        $item47->setName("Quiz zur 37. Wochenaufgabe");
        $item47->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa38.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa38-300x164.png" alt="wa38" width="300" height="164" class="alignleft wp-image-2036 size-medium" /></a> Diese Quiz ist aus dem Bereich der<strong>Beschwerden</strong>  und stellt Fragen zu den<strong>Übungen für die Bandscheiben</strong>.
EOT
        );
        $item47->setCountPoint(1);
        $manager->persist($item47);
        $manager->flush();
        $this->addReference('weeklyquiz_37', $item47);


        $item48=new Weeklyquiz();
        $item48->setId(48);
        $item48->setFormat("richhtml");
        $item48->setName("Quiz zur 38. Wochenaufgabe");
        $item48->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa361.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa361.png" alt="wa36" width="222" height="233" class="alignleft wp-image-2015 size-full" /></a> Dieses Quiz ist aus dem Bereich der<strong>Beschwerden</strong> und stellt Fragen zur Wiederholung der<strong>Bandscheiben</strong>."
EOT
        );
        $item48->setCountPoint(1);
        $manager->persist($item48);
        $manager->flush();
        $this->addReference('weeklyquiz_38', $item48);


        $item49=new Weeklyquiz();
        $item49->setId(49);
        $item49->setFormat("richhtml");
        $item49->setName("Quiz zur 39. Wochenaufgabe");
        $item49->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa39.png">
<img src="http://online-rueckenschule.de/wp-content/uploads/wa39-300x197.png" alt="wa39" width="300" height="197" class="alignleft wp-image-2041 size-medium" /></a> Dieses Quiz ist aus dem Bereich der<strong>Entspannung</strong> und stellt Fragen zur<strong>Muskelentspannung</strong>.
EOT
        );
        $item49->setCountPoint(1);
        $manager->persist($item49);
        $manager->flush();
        $this->addReference('weeklyquiz_39', $item49);


        $item50=new Weeklyquiz();
        $item50->setId(50);
        $item50->setFormat("richhtml");
        $item50->setName("Quiz zur 40. Wochenaufgabe");
        $item50->setDescription(<<<EOT
<a href="http://online-rueckenschule.de/wp-content/uploads/wa39.png"><img src="http://online-rueckenschule.de/wp-content/uploads/wa39-300x197.png" alt="wa39" width="300" height="197" class="alignleft wp-image-2041 size-medium" /></a> Dieses Quiz ist aus dem Bereich der<strong>Entspannung</strong> und stellt Fragen zur Wiederholung von der<strong>Progressiven</strong><strong> Muskelenstpannung</strong>.
EOT
        );
        $item50->setCountPoint(1);
        $manager->persist($item50);

        $manager->flush();
        $this->addReference('weeklyquiz_40', $item50);

        $manager->flush();
    }

}
