<?php

namespace Fitbase\Bundle\ExerciseBundle\DataFixture\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Fitbase\Bundle\ExerciseBundle\Entity\Exercise;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadRuecken1Data extends AbstractFixture implements OrderedFixtureInterface
{
    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 2;
    }

    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetaData(get_class(new Exercise()))->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item615 = new Exercise();
        $item615->setName("1. Mobilisation – Schulter öffnen");
        $item615->setFormat("richhtml");
        $item615->setTag("Rücken");
        $item615->setImage($this->getReference('picture_615.jpeg'));
        $item615->setVideo($this->getReference('video_615.webm'));
        $item615->setGallery($this->getReference('picture_615'));
        $item615->setCategory($this->getReference('category_ruecken'));
        $item615->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px">Schulter öffnen</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Mobilisation</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Heben Sie die Arme an, so dass sie seitlich einen 90° Winkel zum Oberkörper bilden</li>
	<li>Die Unterarme bilden ebenfalls einen 90° Winkel zu den Unterarmen</li>
	<li>Führen Sie die Arme nun leicht nach vorn und soweit es geht nach hinten ohne die Winkel zu verändern</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">10 Wiederholungen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul class="list-unstyled">
	<li>Oberer Rücken</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg">
<img src="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg" alt="" />
</a>
</div>
</div>
EOT
        );
        $manager->persist($item615);

        $item616 = new Exercise();
        $item616->setName("1. Mobilisation – Seitwärts beugen");
        $item616->setFormat("richhtml");
        $item616->setTag("Rücken");
        $item616->setImage($this->getReference('picture_616.jpeg'));
        $item616->setVideo($this->getReference('video_616.webm'));
        $item616->setGallery($this->getReference('picture_616'));
        $item616->setCategory($this->getReference('category_ruecken'));
        $item616->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Seitwärts beugen</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Mobilisation</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Bitte stehen/sitzen Sie aufrecht und strecken Sie die Arme nach oben</li>
	<li>Für die rechte Seite: Fassen Sie nun mit dem linken Arm das rechte Handgelenk über dem Kopf</li>
	<li>Führen Sie nun den Oberkörper zur linken Seite indem Sie oberhalb der Hüfte abknicken</li>
	<li>Begeben Sie sich anschließend wieder in die Ausgangsposition</li>
	<li>5 Wiederholungen, dann entsprechend die andere Seite</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">5 Wiederholungen pro Seite</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul>
	<li>Oberer Rücken</li>
	<li>Bauchmuskeln</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg"><img src="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg" alt="" /></a>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/03_bauchmuskeln.jpg"><img src="/wp-content/uploads/muskelgruppen/03_bauchmuskeln.jpg" alt="" /></a>
</div>
</div>
EOT
        );
        $manager->persist($item616);

        $item617 = new Exercise();
        $item617->setName("1. Mobilisation – Brustrotation");
        $item617->setFormat("richhtml");
        $item617->setTag("Rücken");
        $item617->setImage($this->getReference('picture_617.jpeg'));
        $item617->setVideo($this->getReference('video_617.webm'));
        $item617->setGallery($this->getReference('picture_617'));
        $item617->setCategory($this->getReference('category_ruecken'));
        $item617->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Brustrotation</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Mobilisation</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Bitte stehen/sitzen Sie aufrecht</li>
	<li>Heben Sie die Unterarme auf Schulterhöhe und winkeln Sie die Unterarme im rechten Winkel an</li>
	<li>Rotieren Sie nun aus dem Rumpf heraus ohne das Becken zu bewegen so weit es geht nach links und rechts</li>
	<li>10x zu jeder Seite</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">10 Wiederholungen pro Seite</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul>
	<li>Mittlerer Rücken</li>
	<li>Bauchmuskeln</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg"><img src="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg" alt="" /></a>
</div>
</div>
EOT
        );
        $manager->persist($item617);

        $item618 = new Exercise();
        $item618->setName("1. Mobilisation – Brustwirbelsäule mobilisieren");
        $item618->setFormat("richhtml");
        $item618->setTag("Rücken");
        $item618->setImage($this->getReference('picture_618.jpeg'));
        $item618->setVideo($this->getReference('video_618.webm'));
        $item618->setGallery($this->getReference('picture_618'));
        $item618->setCategory($this->getReference('category_ruecken'));
        $item618->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Brustwirbelsäule mobilisieren</h4>
Bitte führen Sie diese Übung im Sitzen durch
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Mobilisation</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Lassen Sie die Arm locker nach unten hängen und drehen Sie die Daumen nach Innen</li>
	<li>Bewegen Sie das Brustbein in Richtung Becken und machen Sie einen runden Rücken dabei</li>
	<li>Anschließend aus dieser Position die Wirbelsäule maximal aufrichten, indem Sie das Brustbein nach vorne oben bewegen und gleichzeitig die Daumen nach außen drehen</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">20 Wiederholungen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul class="list-unstyled">
	<li>Mittlerer Rücken</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg"><img src="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg" alt="" /></a>
</div>
</div>
EOT
        );
        $manager->persist($item618);

        $item619 = new Exercise();
        $item619->setName("2. Kräftigung – Butterfly");
        $item619->setFormat("richhtml");
        $item619->setTag("Rücken");
        $item619->setImage($this->getReference('picture_619.jpeg'));
        $item619->setVideo($this->getReference('video_619.webm'));
        $item619->setGallery($this->getReference('picture_619'));
        $item619->setCategory($this->getReference('category_ruecken'));
        $item619->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Butterfly</h4>
Bitte führen Sie diese Übung im Sitzen durch
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Kräftigung</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Neigen Sie den Oberkörper leicht nach vorne</li>
	<li>Legen Sie die Hände von außen an die Knie und spreizen Sie die Ellenbogen ab</li>
	<li>Üben Sie mit den Händen Druck auf die Knie aus und halten Sie mit den Knien dagegen</li>
	<li>Der Druck der Arme wird nun stärker und schiebt die Beine zusammen</li>
	<li>Dann wiederum wird der Druck der Beine stärker und schiebt die Beine wieder auseinander</li>
	<li>Die Übung sollte etwas anstrengend sein. Kriterium: Leicht außer Atem geraten und etwas schwitzen. Sollten Ihre Muskeln anfangen zu zittern, ist das ein normales Zeichen dafür, dass die Muskulatur arbeitet.</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">15 Wiederholungen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul class="list-unstyled">
	<li>Brustmuskulatur</li>
	<li>Oberarme</li>
	<li>Oberschenkel</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/08_brust.jpg">
<img src="/wp-content/uploads/muskelgruppen/08_brust.jpg" alt="" />
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/15_oberarm_oberschenkel.jpg">
<img src="/wp-content/uploads/muskelgruppen/15_oberarm_oberschenkel.jpg" alt="" />
</a>
</div>
</div>
EOT
        );
        $manager->persist($item619);

        $item620 = new Exercise();
        $item620->setName("2. Kräftigung – Nackenschaukeln");
        $item620->setFormat("richhtml");
        $item620->setTag("Rücken");
        $item620->setImage($this->getReference('picture_620.jpeg'));
        $item620->setVideo($this->getReference('video_620.webm'));
        $item620->setGallery($this->getReference('picture_620'));
        $item620->setCategory($this->getReference('category_ruecken'));
        $item620->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Nackenschaukeln</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Kräftigung</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Hände greifen unter dem Brustbein ineinander, wobei die Hand zu welcher Seite Sie bewegen von oben greift</li>
	<li>Vom Ellbogen aus den Arm zur Seite ziehen, bis der Oberarm horizontal steht</li>
	<li>Nach 10 Wdh. greift die andere Hand von oben und Sie wiederholen die Übung entsprechend mit der anderen Seite</li>
	<li>Die Übung sollte etwas anstrengend sein. Kriterium: Leicht außer Atem geraten und etwas schwitzen. Sollten Ihre Muskeln anfangen zu zittern, ist das ein normales Zeichen dafür, dass die Muskulatur arbeitet.</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">10 Wiederholungen pro Seite</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul>
	<li>Nackenmuskulatur</li>
	<li>Oberarme</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/01_nackenmuskeln.jpg"><img src="/wp-content/uploads/muskelgruppen/01_nackenmuskeln.jpg" alt="" /></a>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/04_oberarm.jpg"><img src="/wp-content/uploads/muskelgruppen/04_oberarm.jpg" alt="" /></a>
</div>
</div>
EOT
        );
        $manager->persist($item620);

        $item621 = new Exercise();
        $item621->setName("2. Kräftigung – Schreibtisch Liegestütz");
        $item621->setFormat("richhtml");
        $item621->setTag("Rücken");
        $item621->setImage($this->getReference('picture_621.jpeg'));
        $item621->setVideo($this->getReference('video_621.webm'));
        $item621->setGallery($this->getReference('picture_621'));
        $item621->setCategory($this->getReference('category_ruecken'));
        $item621->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Schreibtisch Liegestütz</h4>
Bitte führen Sie diese Übung im Stehen durch
<p style="margin-top: -15px;">[back_to_parent]</p>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Kräftigung</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Bitte die Knie leicht gebeugt und den Rücken gerade um ca. 60° nach vorne geneigt hinstellen</li>
	<li>Die Hände in etwa schulterbreit gerade auf die Tischplatte stellen, die Ellenbogen leicht angewinkelt und das Gewicht auf die Arme verlagern</li>
	<li>Dann das Brustbein soweit nach unten in Richtung Tisch bewegen, bis die Ellenbogen auf Höhe des Rumpfes sind</li>
	<li>Dann aus den Armen wieder hoch drücken, bis die Arme fast gestreckt sind</li>
	<li>Die Übung sollte etwas anstrengend sein. Kriterium: Leicht außer Atem geraten und etwas schwitzen. Sollten Ihre Muskeln anfangen zu zittern, ist das ein normales Zeichen dafür, dass die Muskulatur arbeitet.</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">2 x 10 Wiederholungen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul class="list-unstyled">
	<li>Brustmuskulatur</li>
	<li>Oberarme</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/09_brust_oberarm.jpg"><img src="/wp-content/uploads/muskelgruppen/09_brust_oberarm.jpg" alt="" /></a>
</div>
</div>
EOT
        );
        $manager->persist($item621);

        $item622 = new Exercise();
        $item622->setName("2. Kräftigung – Einigeln – volle Streckung");
        $item622->setFormat("richhtml");
        $item622->setTag("Rücken");
        $item622->setImage($this->getReference('picture_622.jpeg'));
        $item622->setVideo($this->getReference('video_622.webm'));
        $item622->setGallery($this->getReference('picture_622'));
        $item622->setCategory($this->getReference('category_ruecken'));
        $item622->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Einigeln – volle Streckung</h4>
Bitte führen Sie diese Übung im Sitzen durch
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Kräftigung</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Den Oberkörper ca. 45° nach vorne neigen und die Hände hinter dem Kopf verschränken</li>
	<li>Dann die Ellenbogen zur Mitte des Beckens führen und dabei die Wirbelsäule "einrollen"</li>
	<li>Dann die Ellenbogen nach hinten oben führen, die Wirbelsäule strecken und die Oberarme im rechten Winkel zum Körper halten</li>
	<li>Den Oberkörper weiterhin ca. 45° nach vorne neigen</li>
	<li>Die Übung sollte etwas anstrengend sein. Kriterium: Leicht außer Atem geraten und etwas schwitzen. Sollten Ihre Muskeln anfangen zu zittern, ist das ein normales Zeichen dafür, dass die Muskulatur arbeitet.</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">15 Wiederholungen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul class="list-unstyled">
	<li>Mittlerer Rücken</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg"><img src="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg" alt="" /></a>
</div>
</div>
EOT
        );
        $manager->persist($item622);

        $item623 = new Exercise();
        $item623->setName("2. Kräftigung – Latissimus im Sitz");
        $item623->setFormat("richhtml");
        $item623->setTag("Rücken");
        $item623->setImage($this->getReference('picture_623.jpeg'));
        $item623->setVideo($this->getReference('video_623.webm'));
        $item623->setGallery($this->getReference('picture_623'));
        $item623->setCategory($this->getReference('category_ruecken'));
        $item623->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Latissimus im Sitz</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Kräftigung</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Die Hände vor dem Körper so ineinander legen, dass jeweils ein Finger der rechten Hand auf einem Finger der linken Hand liegt</li>
	<li>Die Arme sind halb ausgestreckt, die Ellenbogen zeigen nach außen, die Schultern unten lassen</li>
	<li>Dann die Ellenbogen nach innen ziehen, so dass Druck auf den Fingern entsteht</li>
	<li>Jetzt die Hände zum Körper bewegen und ausatmen</li>
	<li>Ohne Druck die Hände wieder nach vorne bewegen und einatmen</li>
	<li>Die Übung sollte etwas anstrengend sein. Kriterium: Leicht außer Atem geraten und etwas schwitzen. Sollten Ihre Muskeln anfangen zu zittern, ist das ein normales Zeichen dafür, dass die Muskulatur arbeitet.</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">15 Wiederholungen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul>
	<li>Mittlerer Rücken</li>
	<li>Oberarme</li>
	<li>Brustmuskulatur</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg">
<img src="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg" alt="" /></a>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/09_brust_oberarm.jpg">
<img src="/wp-content/uploads/muskelgruppen/09_brust_oberarm.jpg" alt="" /></a>
</div>
</div>
EOT
        );
        $manager->persist($item623);

        $item624 = new Exercise();
        $item624->setName("2. Kräftigung – Trapezius im Sitz");
        $item624->setFormat("richhtml");
        $item624->setTag("Rücken");
        $item624->setImage($this->getReference('picture_624.jpeg'));
        $item624->setVideo($this->getReference('video_624.webm'));
        $item624->setGallery($this->getReference('picture_624'));
        $item624->setCategory($this->getReference('category_ruecken'));
        $item624->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Trapezius im Sitz</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Kräftigung</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Die Hände vor dem Körper so aufeinander legen, dass sie ineinander greifen</li>
	<li>Die Arme sind ausgestreckt, die Ellbogen zeigen nach außen, die Schultern unten lassen</li>
	<li>Dann Druck aufbauen, indem die Ellbogen nach außen gezogen werden</li>
	<li>Jetzt die Hände zum Körper bewegen und ausatmen</li>
	<li>Ohne Druck die Hände wieder nach vorne bewegen und einatmen</li>
	<li>5x die Hände nach vorne, 5x nach unten und 5x nach oben bewegen</li>
	<li>Die Übung sollte etwas anstrengend sein. Kriterium: Leicht außer Atem geraten und etwas schwitzen. Sollten Ihre Muskeln anfangen zu zittern, ist das ein normales Zeichen dafür, dass die Muskulatur arbeitet.</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">15 Wiederholungen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul>
	<li>Mittlerer Rücken</li>
	<li>Brustmuskulatur</li>
	<li>Oberarme</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg"><img src="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg" alt="" /></a>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/09_brust_oberarm.jpg"><img src="/wp-content/uploads/muskelgruppen/09_brust_oberarm.jpg" alt="" /></a>
</div>
</div>
EOT
        );
        $manager->persist($item624);

        $item625 = new Exercise();
        $item625->setName("3. Dehnen – Seitwärts Drehung");
        $item625->setFormat("richhtml");
        $item625->setTag("Rücken");
        $item625->setImage($this->getReference('picture_625.jpeg'));
        $item625->setVideo($this->getReference('video_625.webm'));
        $item625->setGallery($this->getReference('picture_625'));
        $item625->setCategory($this->getReference('category_ruecken'));
        $item625->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px">Seitwärts Drehung</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Dehnen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Für die linke Seite: Bitte schlagen Sie das linke Bein über das rechte</li>
	<li>Legen Sie nun die rechte Hand auf die Außenseite des linken Knies</li>
	<li>Führen Sie nun den ausgestreckten linken Arm auf Schulterhöhe so weit nach hinten, dass Sie einen Dehnungsreiz spüren</li>
	<li>Drehen Sie anschließend den Kopf nach rechts, um den Dehnungsreiz zu verstärken</li>
	<li>ca. 25 Sekunden halten</li>
	<li>Entsprechend die andere Seite</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">25 Sekunden pro Seite</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul class="list-unstyled">
	<li>Mittlerer Rücken</li>
	<li>Bauchmuskulatur</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg"><img src="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg" alt="" /></a>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/03_bauchmuskeln.jpg"><img src="/wp-content/uploads/muskelgruppen/03_bauchmuskeln.jpg" alt="" /></a>
</div>
</div>
EOT
        );
        $manager->persist($item625);

        $item626 = new Exercise();
        $item626->setName("3. Dehnen – Trizeps");
        $item626->setFormat("richhtml");
        $item626->setTag("Rücken");
        $item626->setImage($this->getReference('picture_626.jpeg'));
        $item626->setVideo($this->getReference('video_626.webm'));
        $item626->setGallery($this->getReference('picture_626'));
        $item626->setCategory($this->getReference('category_ruecken'));
        $item626->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px"> Trizeps </h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall"> Dehnen </p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Rechte Seite: den rechten Arm angewinkelt neben dem Kopf halten, so dass der Ellenbogen in Richtung Decke zeigt</li>
	<li>Mit der linken Hand den rechten Ellenbogen greifen und den Arm hinter den Kopf ziehen, bis ein Dehnungsreiz im Arm und dem seitlichen Rücken zu spüren ist</li>
	<li>25 Sekunden halten</li>
	<li>Entsprechend mit der anderen Seite</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">25 Sekunden pro Arm</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul class="list-unstyled">
	<li>Oberarme</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/04_oberarm.jpg"><img src="/wp-content/uploads/muskelgruppen/04_oberarm.jpg" alt="" /></a></div>
</div>
EOT
        );
        $manager->persist($item626);

        $item627 = new Exercise();
        $item627->setName("3. Dehnen – Brustmuskel Dehnen");
        $item627->setFormat("richhtml");
        $item627->setTag("Rücken");
        $item627->setImage($this->getReference('picture_627.jpeg'));
        $item627->setVideo($this->getReference('video_627.webm'));
        $item627->setGallery($this->getReference('picture_627'));
        $item627->setCategory($this->getReference('category_ruecken'));
        $item627->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px">Brustmuskel Dehnen</h4>
Bitte führen Sie diese Übung im Stehen durch
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall"> Dehnen </p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Rechte Seite: Im Stand den rechten Ellenbogen in einem 100° Winkel gegen eine Wand, einen Türrahmen o.ä. halten</li>
	<li>Dann den Oberkörper zur linken Seite wegdrehen, bis ein Dehnungsreiz im rechten Brustmuskel zu spüren ist</li>
	<li>25 Sekunden halten</li>
	<li>Entsprechend mit der anderen Seite</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">25 Sekunden pro Arm</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul class="list-unstyled">
	<li>Brustmuskulatur</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/08_brust.jpg"><img src="/wp-content/uploads/muskelgruppen/08_brust.jpg" alt="" /></a></div>
</div>
EOT
        );
        $manager->persist($item627);

        $item628 = new Exercise();
        $item628->setName("3. Dehnen – Seitwärts beugen Dehnung");
        $item628->setFormat("richhtml");
        $item628->setTag("Rücken");
        $item628->setImage($this->getReference('picture_628.jpeg'));
        $item628->setVideo($this->getReference('video_628.webm'));
        $item628->setGallery($this->getReference('picture_628'));
        $item628->setCategory($this->getReference('category_ruecken'));
        $item628->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Seitwärts beugen Dehnung</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Dehnen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Bitte stehen/sitzen Sie aufrecht und strecken Sie die Arm nach oben</li>
	<li>Für die rechte Seite: Fassen Sie nun mit dem linken Arm das rechte Handgelenk über dem Kopf</li>
	<li>Führen Sie nun den Oberkörper zur linken Seite indem Sie oberhalb der Hüfte abknicken bis Sie einen Dehnungsreiz spüren</li>
	<li>Halten Sie diese Position für ca. 25 Sekunden</li>
	<li>Begeben Sie sich anschließend wieder in die Ausgangsposition</li>
	<li>Entsprechend die andere Seite</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">25 Sekunden pro Seite</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul>
	<li>Mittlerer Rücken</li>
	<li>Bauchmuskulatur</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg"><img src="/wp-content/uploads/muskelgruppen/07_mittlerer_ruecken.jpg" alt="" /></a>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/03_bauchmuskeln.jpg"><img src="/wp-content/uploads/muskelgruppen/03_bauchmuskeln.jpg" alt="" /></a>
</div>
</div>
EOT
        );
        $manager->persist($item628);

        $item629 = new Exercise();
        $item629->setName("3. Dehnen – Supraspinatus/ Schulterblattmuskulatur");
        $item629->setFormat("richhtml");
        $item629->setTag("Rücken");
        $item629->setImage($this->getReference('picture_629.jpeg'));
        $item629->setVideo($this->getReference('video_629.webm'));
        $item629->setGallery($this->getReference('picture_629'));
        $item629->setCategory($this->getReference('category_ruecken'));
        $item629->setDescription(<<<EOT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Supraspinatus/ Schulterblattmuskulatur</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Dehnen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Rechte Seite: Legen Sie die rechte Hand auf die linke Schulter</li>
	<li>Greifen Sie mit der linken Hand den rechten Oberarm</li>
	<li>Ziehen Sie dann den rechten Ellenbogen zur linken Schulter, bis Sie einen Dehnungsreiz spüren</li>
	<li>25 Sekunden halten und dann langsam lösen</li>
	<li>Entsprechend die andere Seite</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">25 Sekunden je Seite</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul class="list-unstyled">
	<li>Oberer Rücken</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg"><img src="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg" alt="" /></a>
</div>
</div>
EOT
        );
        $manager->persist($item629);


        $manager->flush();
    }

}
