<?php

namespace Fitbase\Bundle\ExerciseBundle\DataFixture\ORM;
;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use Doctrine\ORM\Mapping\ClassMetadata;
use Fitbase\Bundle\ExerciseBundle\Entity\Exercise;

/**
 * Generated by Webonaute\DoctrineFixtureGenerator.
 *
 */
class LoadRuecken3Data extends AbstractFixture implements OrderedFixtureInterface
{
    /**
     * Set loading order.
     *
     * @return int
     */
    public function getOrder()
    {
        return 2;
    }

    /**
     * {@inheritDoc}
     */
    public function load(ObjectManager $manager)
    {
        $manager->getClassMetaData(get_class(new Exercise()))->setIdGeneratorType(ClassMetadata::GENERATOR_TYPE_NONE);

        $item602 = new Exercise();
        $item602->setName("1. Mobilisation – Kopfschaukeln");
        $item602->setFormat("richhtml");
        $item602->setTag("Rücken");
        $item602->setImage($this->getReference('picture_602.jpeg'));
        $item602->setVideo($this->getReference('video_602.webm'));
        $item602->setGallery($this->getReference('picture_602'));
        $item602->setDescription(<<<CONTENT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Kopfschaukeln</h4>
Bitte führen Sie diese Übung im Sitzen durch.
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Mobilisation</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Lassen Sie die Arme locker hängen und legen Sie die Hände auf die Oberschenkel</li>
	<li>Führen Sie mit dem Kopf eine Halbkreis-Bewegung durch</li>
	<li>Das Kinn soll dabei möglichst dicht an der Brust geführt werden</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">10 mal zu jeder Seite</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
Nackenmuskulatur</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/01_nackenmuskeln.jpg"><img src="/wp-content/uploads/muskelgruppen/01_nackenmuskeln.jpg" alt="" /></a>
</div>
</div>
CONTENT
        );
        $manager->persist($item602);

        $item603 = new Exercise();
        $item603->setName("1. Mobilisation – Schulterkreisen");
        $item603->setFormat("richhtml");
        $item603->setTag("Rücken");
        $item603->setImage($this->getReference('picture_603.jpeg'));
        $item603->setVideo($this->getReference('video_603.webm'));
        $item603->setGallery($this->getReference('picture_603'));
        $item603->setDescription(<<<CONTENT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Schulterkreisen</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen.
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Mobilisation</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Kreisen Sie mit den Schultern von vorne nach hinten</li>
	<li>Betonen Sie dabei die Bewegungsrichtung nach hinten unten</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">15 Wiederholungen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
Oberer Rücken</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg">
<img src="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg" alt="" />
</a>
</div>
</div>
CONTENT
        );
        $manager->persist($item603);

        $item604 = new Exercise();
        $item604->setName("1. Mobilisation – Schulter öffnen");
        $item604->setFormat("richhtml");
        $item604->setTag("Rücken");
        $item604->setImage($this->getReference('picture_604.jpeg'));
        $item604->setVideo($this->getReference('video_604.webm'));
        $item604->setGallery($this->getReference('picture_604'));
        $item604->setDescription(<<<CONTENT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Schulter öffnen</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen.
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Mobilisation</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Heben Sie die Arme an, so dass sie seitlich einen 90° Winkel zum Oberkörper bilden</li>
	<li>Die Unterarme bilden ebenfalls einen 90° Winkel zu den Unterarmen</li>
	<li>Führen Sie die Arme nun leicht nach vorn und soweit es geht nach hinten ohne die Winkel zu verändern</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">10 Wiederholungen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
oberer Rücken
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg"><img src="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg" alt="" /></a>
</div>
</div>
CONTENT
        );
        $manager->persist($item604);

        $item605 = new Exercise();
        $item605->setName("1. Mobilisation – Seitwärts beugen");
        $item605->setFormat("richhtml");
        $item605->setTag("Rücken");
        $item605->setImage($this->getReference('picture_605.jpeg'));
        $item605->setVideo($this->getReference('video_605.webm'));
        $item605->setGallery($this->getReference('picture_605'));
        $item605->setDescription(<<<CONTENT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Seitwärts beugen</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen.
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Mobilisation</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Bitte stehen/sitzen Sie aufrecht und strecken Sie die Arme nach oben</li>
	<li>Für die rechte Seite: Fassen Sie nun mit dem linken Arm das rechte Handgelenk über dem Kopf</li>
	<li>Führen Sie nun den Oberkörper zur linken Seite indem Sie oberhalb der Hüfte abknicken</li>
	<li>Begeben Sie sich anschließend wieder in die Ausgangsposition</li>
	<li>5 Wiederholungen, dann entsprechend die andere Seite</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">5 Wiederholungen pro Seite</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul>
	<li>Oberer Rücken</li>
	<li>Bauchmuskeln</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg"><img src="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg" alt="" /></a>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/03_bauchmuskeln.jpg"><img src="/wp-content/uploads/muskelgruppen/03_bauchmuskeln.jpg" alt="" /></a>
</div>
</div>
CONTENT
        );
        $manager->persist($item605);

        $item606 = new Exercise();
        $item606->setName("2. Kräftigung – Biceps/Trapezius am Tisch");
        $item606->setFormat("richhtml");
        $item606->setTag("Rücken");
        $item606->setImage($this->getReference('picture_606.jpeg'));
        $item606->setVideo($this->getReference('video_606.webm'));
        $item606->setGallery($this->getReference('picture_606'));
        $item606->setDescription(<<<CONTENT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Biceps/Trapezius am Tisch</h4>
Bitte führen Sie diese Übung im Sitzen durch.
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Kräftigung</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Den Oberkörper leicht nach vorne neigen</li>
	<li>Die Handflächen von unten an den Tisch drücken</li>
	<li>Unter Druck den Oberkörper nach vorne ziehen, wobei Sie das Brustbein nach vorne/oben bewegen</li>
	<li>Die Übung sollte etwas anstrengend sein. Kriterium: Leicht außer Atem geraten und etwas schwitzen. Sollten Ihre Muskeln anfangen zu zittern, ist das ein normales Zeichen dafür, dass die Muskulatur arbeitet.</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">15 Wiederholungen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul>
	<li>Oberer Rücken</li>
	<li>Oberarme</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg"><img src="/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg" alt="" /></a>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/04_oberarm.jpg"><img src="/wp-content/uploads/muskelgruppen/04_oberarm.jpg" alt="" /></a>
</div>
</div>
CONTENT
        );
        $manager->persist($item606);

        $item607 = new Exercise();
        $item607->setName("2. Kräftigung – Dips");
        $item607->setFormat("richhtml");
        $item607->setTag("Rücken");
        $item607->setImage($this->getReference('picture_607.jpeg'));
        $item607->setVideo($this->getReference('video_607.webm'));
        $item607->setGallery($this->getReference('picture_607'));
        $item607->setDescription(<<<CONTENT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style = "margin-bottom: 4px;"> Dips</h4>
    Bitte führen Sie diese Übung im Sitzen durch.
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span> Art der Übung </span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Art der Übung </h4>
<p class="tall"> Kräftigung</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span> Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li> Stellen Sie die Handflächen etwas mehr als Schulterbreit auf den Tisch </li>
	<li> Üben Sie Druck mit den Handflächen auf die Tischplatte aus </li>
	<li> Dabei das Brustbein noch weiter nach vorne/oben bewegen und einatmen,</li>
	<li> Mit der Ausatmung zurück in die Grundhaltung </li>
	<li> Die Übung sollte etwas anstrengend sein. Kriterium: Leicht außer Atem geraten und etwas schwitzen. Sollten Ihre Muskeln anfangen zu zittern, ist das ein normales Zeichen dafür, dass die Muskulatur arbeitet.</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span> Anzahl der Wiederholung </span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Anzahl der Wiederholungen </h4>
<p class="tall"> 15 Wiederholungen </p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span> Beanspruchte Muskelbereiche </span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Beanspruchte Muskelbereiche </h4>
<ul>
	<li> Oberer Rücken </li>
	<li> Oberarme</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href = "/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg"><img src = "/wp-content/uploads/muskelgruppen/02_oberer_ruecken.jpg" alt = "" /></a>
<a class="exercise-picture-zoom area" href = "/wp-content/uploads/muskelgruppen/04_oberarm.jpg"><img src = "/wp-content/uploads/muskelgruppen/04_oberarm.jpg" alt = "" /></a>
</div>
</div>
CONTENT
        );
        $manager->persist($item607);

        $item608 = new Exercise();
        $item608->setName("2. Kräftigung – Kopfwiderstand dynamisch vorne");
        $item608->setFormat("richhtml");
        $item608->setTag("Rücken");
        $item608->setImage($this->getReference('picture_608.jpeg'));
        $item608->setVideo($this->getReference('video_608.webm'));
        $item608->setGallery($this->getReference('picture_608'));
        $item608->setDescription(<<<CONTENT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Kopfwiderstand dynamisch vorne</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen.
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Kräftigung</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Führen Sie eine Hand an das Kinn</li>
	<li>Schieben Sie Ihren Kopf gegen den Widerstand der Hand auf einer gedachten horizontalen Linie nach vorne</li>
	<li>Der ausgeübte Druck sollte nicht zu stark sein und langsam ansteigen</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">2 x 5 Wiederholungen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul class="list-unstyled">
	<li>Nackenmuskulatur</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/01_nackenmuskeln. jpg"><img src="/wp-content/uploads/muskelgruppen/01_nackenmuskeln. jpg" alt="" /></a>
</div>
</div>
CONTENT
        );
        $manager->persist($item608);

        $item609 = new Exercise();
        $item609->setName("2. Kräftigung – Kopfwiderstand seitlich");
        $item609->setFormat("richhtml");
        $item609->setTag("Rücken");
        $item609->setImage($this->getReference('picture_609.jpeg'));
        $item609->setVideo($this->getReference('video_609.webm'));
        $item609->setGallery($this->getReference('picture_609'));
        $item609->setDescription(<<<CONTENT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style = "margin-bottom: 4px"> Kopfwiderstand seitlich </h4>
    Sie können diese Übung im Stehen oder im Sitzen durchführen.
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span> Art der Übung </span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Art der Übung </h4>
<p class="tall"> Kräftigung </p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span> Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li> Führen Sie die rechte Hand zur rechten Schläfe und bauen Sie einen leicht stärker werdenden Druck auf </li>
	<li> Den Druck ca. 10 Sekunden halten </li>
	<li> Entsprechend links </li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span> Anzahl der Wiederholung </span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Anzahl der Wiederholungen </h4>
<p class="tall"> 10 Sekunden pro Seite </p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span> Beanspruchte Muskelbereiche </span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Beanspruchte Muskelbereiche </h4>
<ul class="list-unstyled">
	<li> Nackenmuskulatur</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href = "/wp-content/uploads/muskelgruppen/01_nackenmuskeln.jpg"><img src = "/wp-content/uploads/muskelgruppen/01_nackenmuskeln.jpg" alt = "" /></a>
</div>
</div>
CONTENT
        );
        $manager->persist($item609);

        $item610 = new Exercise();
        $item610->setName("3. Dehnen – Dehnung kurze Nackenmuskulatur");
        $item610->setFormat("richhtml");
        $item610->setTag("Rücken");
        $item610->setImage($this->getReference('picture_610.jpeg'));
        $item610->setVideo($this->getReference('video_610.webm'));
        $item610->setGallery($this->getReference('picture_610'));
        $item610->setDescription(<<<CONTENT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px">Dehnung kurze Nackenmuskulatur</h4>
Bitte führen Sie diese Übung im Sitzen durch.
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Dehnen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Mit beiden Händen den Hinterkopf umgreifen</li>
	<li>Dann die Halswirbelsäule vorsichtig in die Beugung drücken</li>
	<li>Dabei das Kinn Richtung Brustbein bewegen, bis Sie einen Dehnungsreiz im Nacken und zwischen den Schulterblättern verspüren</li>
	<li>Die Ellenbogen zeigen dabei nach vorn</li>
	<li>25 Sekunden halten</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">25 Sekunden</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul class="list-unstyled">
	<li>Nackenmuskulatur</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/01_nackenmuskeln. jpg"><img src="/wp-content/uploads/muskelgruppen/01_nackenmuskeln. jpg" alt="" /></a>
</div>
</div>
CONTENT
        );
        $manager->persist($item610);

        $item611 = new Exercise();
        $item611->setName("3. Dehnen – Hand-Unterarmdehnung");
        $item611->setFormat("richhtml");
        $item611->setTag("Rücken");
        $item611->setImage($this->getReference('picture_611.jpeg'));
        $item611->setVideo($this->getReference('video_611.webm'));
        $item611->setGallery($this->getReference('picture_611'));
        $item611->setDescription(<<<CONTENT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style = "margin-bottom: 4px;"> 3. Dehnen – Hand-Unterarmdehnung </h4>
    Bitte führen Sie diese Übung im Stehen durch.
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span> Art der Übung </span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Art der Übung </h4>
<p class="tall"> Dehnung</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span> Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li> Bitte stehen/sitzen Sie aufrecht </li>
	<li> Strecken Sie den rechten Arm aus und lassen Sie die Hand locker nach unten hängen </li>
	<li> Üben Sie nun mit der linken Hand leichten Druck auf die rechte Hand aus, bis Sie einen Dehnungsreiz spüren </li>
	<li> ca. 10 Sekunden halten </li>
	<li> Anschließend drehen Sie die Hand nach außen </li>
	<li> Üben Sie nun erneut Druck aus, bis Sie einen Dehnungsreiz spüren </li>
	<li> ca. 10 Sekunden halten </li>
	<li> entsprechend die andere Seite </li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span> Anzahl der Wiederholung </span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Anzahl der Wiederholungen </h4>
<p class="tall"> 20 Sekunden halten je Seite </p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span> Beanspruchte Muskelbereiche </span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Beanspruchte Muskelbereiche </h4>
<ul>
	<li> Unterarme</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href = "/wp-content/uploads/muskelgruppen/06_unterarm.jpg"><img src = "/wp-content/uploads/muskelgruppen/06_unterarm.jpg" alt = "" /></a>
</div>
</div>
CONTENT
        );
        $manager->persist($item611);

        $item612 = new Exercise();
        $item612->setName("3. Dehnen – Nacken Dehnen");
        $item612->setFormat("richhtml");
        $item612->setTag("Rücken");
        $item612->setImage($this->getReference('picture_612.jpeg'));
        $item612->setVideo($this->getReference('video_612.webm'));
        $item612->setGallery($this->getReference('picture_612'));
        $item612->setDescription(<<<CONTENT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Nacken Dehnen</h4>
Sie können diese Übung im Stehen oder im Sitzen durchführen.
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Dehnen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Linke Seite: rechtes Ohr ohne zu rotieren in Richtung rechte Schulter bewegen</li>
	<li>Dann den linken Arm in Richtung Boden schieben, so dass Sie einen Dehnungsreiz in der Nackenmuskulatur verspüren</li>
	<li>Den Handrücken nach oben ziehen, um den Dehnungsreiz zu verstärken</li>
	<li>25 Sekunden halten</li>
	<li>Entsprechend mit der anderen Seite</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">25 Sekunden pro Seite</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul class="list-unstyled">
	<li>Nackenmuskeln</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/01_nackenmuskeln. jpg"><img src="/wp-content/uploads/muskelgruppen/01_nackenmuskeln. jpg" alt="" /></a>
</div>
</div>
CONTENT
        );
        $manager->persist($item612);

        $item613 = new Exercise();
        $item613->setName("3. Dehnen – Nackendehnung Variante");
        $item613->setFormat("richhtml");
        $item613->setTag("Rücken");
        $item613->setImage($this->getReference('picture_613.jpeg'));
        $item613->setVideo($this->getReference('video_613.webm'));
        $item613->setGallery($this->getReference('picture_613'));
        $item613->setDescription(<<<CONTENT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style = "margin-bottom: 4px;"> Nackendehnung Variante </h4>
    Sie können diese Übung im Stehen oder im Sitzen durchführen.
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span> Art der Übung </span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Art der Übung </h4>
<p class="tall"> Dehnen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span> Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li> Bitte stehen/sitzen Sie aufrecht </li>
	<li> Linke Seite: rechtes Ohr ohne zu rotieren in Richtung rechte Schulter bewegen </li>
	<li> Dann den linken Arm in Richtung Boden schieben, so dass Sie einen Dehnungsreiz in der Nackenmuskulatur verspüren </li>
	<li> Den Handrücken nach oben ziehen, um den Dehnungsreiz zu verstärken </li>
	<li> 10 Sekunden halten </li>
	<li> Anschließend aus derselben Position das Kinn leicht zur Schulter drehen und nach unten schauen </li>
	<li> 10 Sekunden halten </li>
	<li> Dann aus derselben Position das Kinn leicht nach oben führen und zur Decke schauen </li>
	<li> 10 Sekunden halten </li>
	<li> Langsam lösen und entsprechend mit der anderen Seite </li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span> Anzahl der Wiederholung </span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Anzahl der Wiederholungen </h4>
<p class="tall"> 10 Sekunden je Position </p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span> Beanspruchte Muskelbereiche </span></i></div>
<div class="feature-box-info">
<h4 class="shorter"> Beanspruchte Muskelbereiche </h4>
<ul class="list-unstyled">
	<li> Nackenmuskulatur</li>
	<li> Unterarme</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href = "/wp-content/uploads/muskelgruppen/01_nackenmuskeln.jpg"><img src = "/wp-content/uploads/muskelgruppen/01_nackenmuskeln.jpg" alt = "" /></a>
<a class="exercise-picture-zoom area" href = "/wp-content/uploads/muskelgruppen/06_unterarm.jpg"><img src = "/wp-content/uploads/muskelgruppen/06_unterarm.jpg" alt = "" /></a>
</div>
</div>
CONTENT
        );
        $manager->persist($item613);

        $item614 = new Exercise();
        $item614->setName("3. Dehnen – Unterarmdehnung");
        $item614->setFormat("richhtml");
        $item614->setTag("Rücken");
        $item614->setImage($this->getReference('picture_614.jpeg'));
        $item614->setVideo($this->getReference('video_614.webm'));
        $item614->setGallery($this->getReference('picture_614'));
        $item614->setDescription(<<<CONTENT
<div class="row">
<div class="span4 col-md-4 column_last">
<h4 style="margin-bottom: 4px;">Unterarmdehnung</h4>
Bitte führen Sie diese Übung im Stehen durch.
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-info"><span>Art der Übung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Art der Übung</h4>
<p class="tall">Dehnen</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-tasks"><span>Durchführungsanleitung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Durchführungsanleitung</h4>
<ol class="numbered-list">
	<li>Die Finger zeigen zum Körper</li>
	<li>Dann die Ellenbogen durchdrücken und den Oberkörper soweit zurücklehnen, bis ein Dehnungsreiz in den Unterarmen zu spüren ist</li>
	<li>Diesen Reiz ca. 25 Sekunden aufrecht erhalten und dann langsam absetzen</li>
</ol>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-clock-o"><span>Anzahl der Wiederholung</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Anzahl der Wiederholungen</h4>
<p class="tall">25 Sekunden</p>
</div>
</div>
<div class="feature-box">
<div class="feature-box-icon"><i class="icon icon-male"><span>Beanspruchte Muskelbereiche</span></i></div>
<div class="feature-box-info">
<h4 class="shorter">Beanspruchte Muskelbereiche</h4>
<ul class="list-unstyled">
	<li>Unterarme</li>
</ul>
</div>
<div class="clear"></div>
</div>
<a class="exercise-picture-zoom area" href="/wp-content/uploads/muskelgruppen/06_unterarm. jpg"><img src="/wp-content/uploads/muskelgruppen/06_unterarm. jpg" alt="" /></a>
</div>
</div>
CONTENT
        );
        $manager->persist($item614);


        $manager->flush();
    }

}
