<?php

namespace Fitbase\Bundle\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserFocusCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserFocusCategoryRepository extends EntityRepository
{

}
