<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\PageBundle\Entity;

use Sonata\PageBundle\Entity\BaseSite as BaseSite;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class Site extends BaseSite
{

    /**
     * @var integer $id
     */
    protected $id;

    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * @var \Application\Sonata\UserBundle\Entity\Group
     */
    private $group;


    /**
     * Set group
     *
     * @param \Application\Sonata\UserBundle\Entity\Group $group
     * @return Site
     */
    public function setGroup(\Application\Sonata\UserBundle\Entity\Group $group = null)
    {
        $this->group = $group;

        return $this;
    }

    /**
     * Get group
     *
     * @return \Application\Sonata\UserBundle\Entity\Group 
     */
    public function getGroup()
    {
        return $this->group;
    }
    /**
     * @var string
     */
    private $scheme;


    /**
     * Set scheme
     *
     * @param string $scheme
     * @return Site
     */
    public function setScheme($scheme)
    {
        $this->scheme = $scheme;

        return $this;
    }

    /**
     * Get scheme
     *
     * @return string 
     */
    public function getScheme()
    {
        return $this->scheme;
    }
}
